### ISSUE TITLE
Sometimes TV is not powered off when Windows turns off the output

### ISSUE THREAD

**Issue by dechamps** [JPersson77/LGTVCompanion#10]
(LGTVCompanion 1.4.2 Windows 11 21H2 22000.376, NVidia 496.76)

I have a hard-to-reproduce issue where sometimes (not always), for no apparent reason, LGTVCompanion does not turn off the TV when Windows decides to turn off the display. I'm referring purely to the Windows display timeout here, not PC standby/shutdown.

I hacked together a build with additional verbose logging code around `PBT_POWERSETTINGCHANGE` events, and then waited until the issue occurred again. I noticed that when things behave correctly, Windows delivers a [`GUID_CONSOLE_DISPLAY_STATE`](https://docs.microsoft.com/en-us/windows/win32/power/power-setting-guids#GUID_CONSOLE_DISPLAY_STATE) event to LGTVCompanion with data 0x2 (dimmed), followed 15 seconds later by another `GUID_CONSOLE_DISPLAY_STATE` event with data 0x0 (off). So far so good.

When the issue occurs, LGTVCompanion does receive the first event (0x2 dimmed), but the second one (0x0 off) is nowhere to be found. I have no idea why.

LGTVCompanion currently treats 0x2 (dimmed) the same as 0x1 (on) and therefore does not turn off the display in this case.

(I checked if [`GUID_MONITOR_POWER_ON`](https://docs.microsoft.com/en-us/windows/win32/power/power-setting-guids#GUID_MONITOR_POWER_ON) had a similar problem. Sadly, the answer is yes.)

This probably deserves some more investigation, but if this doesn't go anywhere, a potential workaround is to treat 0x2 (dimmed) as "off". I don't think this would have any visible side effects, given that there is no actual dimming going on (at least not on my system). It would make the TV turn off 15 seconds too soon but that's arguably benign, and in fact it's a bit cleaner because this way the TV doesn't have time to briefly display its "No Signal" message.

**Comment by JPersson77** [comment]
Hi there, I think I've seen this behaviour too but very infrequently. Maye two or three times in total. 0x2(dimmed) is used I believe for laptop screens that dim down a bit before shutting off. I will investigate how the proposed change will affect the logic but it seems like you may be on to something. Thanks for helping out!

**Comment by JPersson77** [comment]
Hi again, I pushed a workaround for this issue in line with your suggestion (Improved logic for screen dimmed state)

**Comment by dechamps** [comment]
Well to be fair I was seeing this issue quite frequently before, but didn't observe it once in the last few days. The only thing I changed was I upgraded my NVidia drivers from 496.76 to 497.09, no idea if that has anything to do with it.

I'll keep running the old code for now just to see if the workaround will turn out to be useful or not.

**Comment by dechamps** [comment]
Okay so unfortunately the problem didn't go away (with the old code, that is). While I was trying to reproduce this problem, I was running a short monitor timeout (3 minutes) to try to make it more frequent. This backfired, as the shorter timeout appears to have made the problem impossible to reproduce. Now that I've reverted back to my normal screen timeout (20 minutes) the issue is back. That's quite the [heisenbug](https://en.wikipedia.org/wiki/Heisenbug)😕

Anyway, since the problem is clearly still there, I'll try the code from latest master which contains your workaround and see what happens.

**Comment by JPersson77** [comment]
Hiya, thanks for continued testing. I've been using the fix in latest master since some time now with no adverse effects so I hope it shall solve your issues. Getting ready to release a new version soon so will include this code change if you can verify it seems to solve your issues.

**Comment by JPersson77** [comment]
@dechamps was this resolved with the workaround? :)

**Comment by dechamps** [comment]
Well it still hasn't happened since, so I'd say I'm pretty confident it's working yes.
