### ISSUE TITLE
LG 47LB582T

### ISSUE THREAD

**Issue by akeilox** [JPersson77/LGTVCompanion#101]
Hi! Trying it for the first time with version 1.9 on Windows 11, the TV is LG 47LB582T

Connected via WiFi (no connection issue as both near the router) on the same LAN.

App detects the tv as [TV][LG]47LB582T but then I cant do anymore than that. The Test doesnt work along with Power Off/On.

I have looked for an option "Quickstart+" in the TV menus but cant locate, its pre 2021 model, likely 2015/2016 running WebOS.

Any other pointers on troubleshooting to get this to work? 
cheers

**Comment by JPersson77** [comment]
Hi @akeilox I don't know straight up if it's too old WebOS version. A quick google shows there was some frmware updates this year to check out if you didn't already https://www.lg.com/sg/support/software-firmware?csSalesCode=47LB582T.ATC

In the app, enable logging and open it after trying to power the device on/off to see what is going on. That might give some additional clues. Also confirm you pressed the "Apply" button please after configuring the device :)

**Comment by akeilox** [comment]
hey @JPersson77 thank you for the swift and very useful reply/tips.

The TV is already on the latest firmware ,confirmed.

When I enable logging, Apply, then open the log I see this (pairing key seems to be the culprit? cant find where the Quickstart option might be):

Tue 01:10:42 > LGTV Companion Service started (v 1.9.0) ---------------------------
Tue 01:10:42 > Configuration file successfully read
Tue 01:10:42 > Data path: C:\ProgramData\LGTV Companion\
Tue 01:10:42 > Device1, [TV][LG]47LB582T, with IP 192.168.0.216 initiated (Enabled:yes, WOL:2, PairingKey:n/a, MAC: C8:02:10:BB:2C:XX , VerifyHdmiInput:off, SetHdmiInput:off, BlankOnIdle:on(1m))
Tue 01:10:42 > Host IPs detected: 192.168.49.1, 192.168.121.1, 192.168.56.1, 192.168.0.213
Tue 01:10:42 > Setting shutdown parameter level 0x100
Tue 01:10:42 > ** System requests displays ON.
Tue 01:10:42 > Device1, spawning DisplayPowerOnThread().
Tue 01:10:42 > Device1, repeating WOL broadcast started to MAC: C8:02:10:BB:2C:XX using IP address: 192.168.0.216
Tue 01:10:42 > Device1, GetBestRoute2() selected interface index 10 LUID 1689399632855040 route protocol 2
Tue 01:10:42 > IPC, Daemon has started.
Tue 01:10:44 > Device1, GetBestRoute2() selected interface index 10 LUID 1689399632855040 route protocol 2
Tue 01:10:44 > Device1, WARNING! DisplayPowerOnThread(): connect: No connection could be made because the target machine actively refused it
Tue 01:10:46 > Device1, GetBestRoute2() selected interface index 10 LUID 1689399632855040 route protocol 2
Tue 01:10:46 > IPC, force power OFF: device1
Tue 01:10:46 > Device1, omitted DisplayPowerOffThread() (no pairing key).
Tue 01:10:48 > Device1, GetBestRoute2() selected interface index 10 LUID 1689399632855040 route protocol 2
Tue 01:10:50 > Device1, GetBestRoute2() selected interface index 10 LUID 1689399632855040 route protocol 2
Tue 01:10:50 > IPC, windows monitor topology was changed. Device1:OFF 
Tue 01:10:50 > Device1, omitted DisplayPowerOffThread() (no pairing key).
Tue 01:10:50 > Device1, WARNING! DisplayPowerOnThread(): connect: No connection could be made because the target machine actively refused it

**Comment by akeilox** [comment]
I have gone through the TV's settings and cant seem to locate anything that resembles remote/mobile/allow connection except Miracast. It appears its not gonna play, although I really wanted to since the TV is mounted right above the PC and idea of automating it got me excited.

**Comment by akeilox** [comment]
under Product/Service info screen:
Model/Type: 47LB582T-TB
Software version: 04.04.22
SDK version: 03.05
Browser Version: v6.00.00.e49900.4990
ESN: LGTV20132=21012480337
Widevine: LGTV13CMTK012501142

Does that say anything? I will look for service mode for the Remote to see if i can get more info.

**Comment by JPersson77** [comment]
Not really I'm afraid. But I can see the TV is from 2013-2014 and I can see references to controlling webos dating back 8 years so I think there might be a chance. Do you have anythig called "LG Connect Apps" you can enable?

From another repo here I find this text: "First, the device (eg your computer) must be on the same network as the TV. Second, you should enable the TV to broadcast itself as lgsmarttv.lan in the local network. This setting is under Network/LG Connect Apps. This is necessary in order for this module to find the TV on the network and allow apps to connect. You also need to be on the same network as the TV." (https://github.com/msloth/lgtv.js)

**Comment by akeilox** [comment]
I am definitely on the same LAN. I found LG Smart Apps (not LG connect apps) section where consent asked to install apps from their appstore (never used this before) but cant see any option to 'broadcast itself'.
I will get fresh new batteries to the remote and a long rj45 cable to wire it tomorrow (may be doesnt like wireless? although its perfect signal) and do another attempt to locating this possible "consent/allow"  section.
Will keep you updated here. Thank you @JPersson77

**Comment by JPersson77** [comment]
I don't think it's the app store that is referenced, Apparently it should be located under "network" settings (which make sense). I feel this should be achievable :) Good luck @akeilox and let know how it goes please

**Comment by JPersson77** [comment]
How did it go @akeilox ?

**Comment by akeilox** [comment]
Unfortunately I couldnt find any setting under network or otherwise to enable incoming connection. I have checked both Smart Apps and TV menu and the feature is nowhere to be found.

**Comment by JPersson77** [comment]
Allright, thanks for feedback. I will close this issue but feel free to reopen as needed
