### ISSUE TITLE
3.30.16 Firmware, G2 series no longer wake up or shutdown, app is useless atm

### ISSUE THREAD

**Issue by DangerPizzaSlice** [JPersson77/LGTVCompanion#104]
Worked fine untell 3.30.16, LG broke something or changed severely

**Comment by JPersson77** [comment]
Hi @DangerPizzaSlice you are correct. A fix is being tested currently and will be in the next release

**Comment by DangerPizzaSlice** [comment]
> Hi @DangerPizzaSlice you are correct. A fix is being tested currently and will be in the next release

good to know. thanks for the app and it's support, it is very handy

**Comment by JPersson77** [comment]
New version (v2) is up so I'm closing this issue. https://github.com/JPersson77/LGTVCompanion/releases

**Comment by DangerPizzaSlice** [comment]
> New version (v2) is up so I'm closing this issue. https://github.com/JPersson77/LGTVCompanion/releases

works great. genuinely grateful
