### ISSUE TITLE
LG webOS TV version 7.3.0-14 and 03.30.14 firmware is REAL?

### ISSUE THREAD

**Issue by deljohn08** [JPersson77/LGTVCompanion#108]
Recently we bought LG 55UQ7550PSF and check all information given us. At first my webOS is only 7.2.0-46 then when I see it now, it's currently put to 7.3.0-14 (mullet-mubben) with 03.30.14 firmware.

Why did it happen? even though I put the auto update off. Is there a chance my tv got hacked? Or the webOS currently I had is actually not real? 7.3.0-14 (mullet-mubben)..

Lately my neighbor got in to our modem router and randomize destroy our privacy and files. No Idea for real what could go wrong

**Comment by deljohn08** [comment]
For some reason I found out there is no notification we get when updates is done and we hope lg put away the deletion icon in notification because it's really important, maybe someone do bad. Thanku MR. and Ms.

**Comment by JPersson77** [comment]
I think you're safe. The TV was updated to a newer firmware for some reason and its normal. This app in version 2.0 should work normally with the TV with this firmware. You should probably contact LG support with your observations about the  otifications and auto-update as this application is not affiliated with LG and I cannot help with  those issues I'm afraid

**Comment by JPersson77** [comment]
Closing the issue
