### ISSUE TITLE
Idle Off not working for me

### ISSUE THREAD

**Issue by Chad711** [JPersson77/LGTVCompanion#110]
I'm not sure why this stopped working but I can't seem to figure out the issue. I've completely uninstalled/installed the newest version. I even deleted the device and added it again. I have confirmed IP address is correct. I set it to go black/off after 1 minute of idle. 

Any suggestions?

**Comment by JPersson77** [comment]
Usually this means something prevents idle and the most common reason seem to be a joystick or a ps5 controller. Open a command prompt and navigate to the installation directory and execute "LGTVdaemon.exe -show", watch the idle counter in the window that opens and start unplugging devices till the counter starts to increase. This should give some insight to what is going wrong.  Let me know how it goes please

**Comment by Chad711** [comment]
Hello, looks like it's my Fanatec Handbrake that is causing this. It's part of my sim rig. Is there a way to keep this plugged in and still use LG Companion?

**Comment by JPersson77** [comment]
Unfortunately some controllers do this. You will likely find it prevents the normal windows screensaver/screen off power stteigs too. Please see my input at the bottom of #58 for some additional info

**Comment by Chad711** [comment]
I see, thanks for the info

**Comment by JPersson77** [comment]
Closing the issue

**Comment by JPersson77** [comment]
Just leaving this here as there is some progress on the issue: https://www.techradar.com/news/its-finally-game-over-for-one-of-windows-11s-oldest-and-annoying-bugs

**Comment by Chad711** [comment]
awesome thanks! I just upgraded to W11 last week too. My sim rig stuff was
causing the issue. I have since just left it disconnected when not using it
to work around it.

**Comment by JPersson77** [comment]
No worries! I got a report that [KB5022845](https%3A%2F%2Fsupport.microsoft.com%2Fen-gb%2Ftopic%2Ffebruary-14-2023-kb5022845-os-build-22621-1265-90a807f4-d2e8-486e-8a43-d09e66319f38) fixed the similar issue he was experiencing with his 8bitdo controller 👍

**Comment by Chad711** [comment]
I have a question. I have a LG C1 and C2. I never used the companion app on
the C1 as most use was with a PS5. However I'm now using the companion app
for both TV's since I do some PC gaming on both. The companion app is
turning my C1 black (assuming idle timer) even though I'm playing games on
my PS5. Is there a way to stop the idle function when I'm on my PS5?

**Comment by Chad711** [comment]
Nevermind my last question. Guess I should look in options before asking! I
see I can set it to work when only certain HDMI port is in use.
