### ISSUE TITLE
Black screen is not displaying when idle over 1 minute

### ISSUE THREAD

**Issue by aphwong** [JPersson77/LGTVCompanion#115]
My screen will not turn black even the idle time over 1 minute.
And I found there is a 500 error in the log

<img width="344" alt="image" src="https://user-images.githubusercontent.com/43560054/219105855-fafe675c-0a97-4253-b922-180cc15b15f4.png">
<img width="254" alt="image" src="https://user-images.githubusercontent.com/43560054/219105909-64b12ff1-161c-482e-a2fb-c80112d48f15.png">

### **config.json**
`"LGTV Companion": {
        "AdhereDisplayTopology": true,
        "AutoUpdate": true,
        "BlankWhenIdle": true,
        "BlankWhenIdleDelay": 1,
        "ExtendedLog": true,
        "IdleFullscreen": true,
        "IdleWhiteListEnabled": false,
        "LocalEventLogRestartString": [
            "restart"
        ],
        "LocalEventLogShutdownString": [
            "shutdown",
            "power off",
            "重新啟動",
            "電源關閉",
            "關機"
        ],
        "PowerOnTimeOut": 40,
        "RemoteStream": true,
        "TopologyPreferPowerEfficient": true,
        "Version": 2
    }`

### **And here is the Log with 500 error**
Thu 01:11:00 > Device1, Setting HDMI input: 1
Thu 01:11:02 > Device1, repeating WOL broadcast ended
Thu 01:11:08 > IPC, windows monitor topology was changed. Device1:ON 
Thu 01:11:08 > Device1, spawning DisplayPowerOnThread().
Thu 01:11:08 > Device1, repeating WOL broadcast started to MAC: 4C:BA:D7:F0:33:A0 using IP address: 192.168.50.223
Thu 01:11:08 > Device1, GetBestRoute2() selected interface index 10 LUID 1689399699963904 route protocol 2
Thu 01:11:08 > [DEBUG] (SSL) ON response 1: {"type":"registered","id":"register_0","payload":{"client-key":"de2a76befe296a5e9a7c1a98bd7d030f"}}
Thu 01:11:08 > [DEBUG] (SSL) ON response 2: {"type":"error","id":"2","error":"500 Application error","payload":{"returnValue":false,"state":"Active","errorCode":"-102","errorText":"The current sub state must be 'screen off'"}}
Thu 01:11:08 > [DEBUG] (SSL) ON response 3: {"type":"response","id":"1","payload":{"state":"Active","returnValue":true}}
Thu 01:11:08 > Device1, power state is: ON
Thu 01:11:10 > Device1, repeating WOL broadcast ended

**Comment by JPersson77** [comment]
Hi, you can disregard that error. To find out why user idle mode is not triggered I would recommend you to execute "LGTVdaemon.exe -show" from the install directory. This will show a status window for the daemon. Observera the log and see if there is something preventing user idle mode. You can also see a timer which should increase when the PC is idle. If the timer is not ticking/increasing then you most likely have some usb device preventing it. If so try unplugging devices till you find the culprit. I've seen reports of ps5 controls and some joysticks causing this

**Comment by aphwong** [comment]
Yes, It’s caused by the joystick.
Black screen shown when I’ve removed the joystick from USB port.

**Comment by JPersson77** [comment]
Its a microsoft bug. It will prevent the normal screensaver etc too. See the link i posted above where techradar reports that its finally being fixed
