### ISSUE TITLE
Cannot connect wired PC to wireless TV

### ISSUE THREAD

**Issue by Jassida15** [JPersson77/LGTVCompanion#116]
Laptops connect fine. They do not scan but work manually.

When first installed it lists the model name without [WebOS] prefix. The ip and mac address are completely wrong.

When scanned it finds 2 televisions (I have 1). The prefix is [webOS]. 1 has the correct details, the second one lists an IP address that is 100% not on my network. I have fixed an ip.

I apply settings that work on the laptops but nothing happens.

Windows 11 lists 3 LG TVs in network

**Comment by JPersson77** [comment]
Hi @Jassida15 the app retreive the data from the windows "Digital Media Devices" vlass. You can find these entries in the device manager under the heading "Digital Media Devices".  Check to see what entires you have there and report back please. Maybe the logic in the app can be refined

**Comment by Jassida15** [comment]
Thanks I just have 1 listed. [LG] webOS TV etc.

**Comment by JPersson77** [comment]
Sorry, forgot that you need to go to the View menu and check "Show hidden devices"

**Comment by Jassida15** [comment]
Ah, now I have 2.

http://192.168.1.188:1256/ - Not greyed out. My fixed ip
http://192.168.1.182:1846/ - Greyed out. Nothing on my network with this ip

Thanks for helping so quickly

**Comment by JPersson77** [comment]
And if you now go to the properties for each of them and then to the "details" tab, and scroll down to "friendly name", what name do these devices have?

**Comment by Jassida15** [comment]
Sorry, I've just realised something. I had a panel swap which I'd forgotten about. Now I've deleted the greyed out device I just get one detected.

Still doesn't work though. Could a non running VPN cause it perhaps? I'm also running via powerline adapter.

Thanks.

**Comment by JPersson77** [comment]
Great then we know what that was about. Now to solve the other issue please enable logging, try the "test" function or similar and paste the log and config.json on pastebin or similar and paste the links here please

**Comment by Jassida15** [comment]
It's working now, thank you so much.

The json file had incorrect details and was not being overwritten. I deleted it and it recreated fine.

Just in case of interest, logging enabled does not create a log file anywhere that I can see

**Comment by JPersson77** [comment]
That's good to hear! The logfile should be in the same directory as the config.json (typically c:/programdata/lgtv companion/) and is called log.txt. you should also be able to access it from the options window by clicking on the link.

There is nothing written to the log just by checking the checkbox, you must also click apply in the main window. Can that be it?

**Comment by JPersson77** [comment]
Closing this due to missing feedback. Feel free to reopen as needed
