### ISSUE TITLE
Audio output device sometimes disappears

### ISSUE THREAD

**Issue by elduds** [JPersson77/LGTVCompanion#119]
Hi, 

Loving the application. Only real issue I have is that often after waking the TV, it no longer appears as a sound output device in Windows. Browsing to Device Manager and scanning for hardware changes resolves the issue and returns it to the default sound output.

Does anyone else experience this? If so perhaps an option to automatically refresh hardware after wake would be useful.

LG C2 42"
Edition	Windows 11 Pro
Version	22H2
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by JPersson77** [comment]
Hi@eldus, this is the first report of this issue. Does this happen when not using lgtv companion as well, i e when powering on manually?

**Comment by JPersson77** [comment]
You could probably engineer a solution with autohotkey and DevCon. Something like the below. Googlewords: "autohotkey wm_powerbroadcast", "devcon"

`GUID_CONSOLE_DISPLAY_STATE := "6FE69556-704A-47A0-8F24-C28D936FDA47"
h := RegisterPowerSettingNotification(GUID_CONSOLE_DISPLAY_STATE)

OnExit( Func("UnRegisterNotification").Bind(h) )
OnMessage(0x218, "WM_POWERBROADCAST")

RegisterPowerSettingNotification(GUID) {
    static DEVICE_NOTIFY_WINDOW_HANDLE := 0
    VarSetCapacity(UUID, 16, 0)
    DllCall("Rpcrt4\UuidFromString", Str, GUID, Ptr, &UUID)
Return DllCall("RegisterPowerSettingNotification", Ptr, A_ScriptHwnd, Ptr, &UUID, UInt, DEVICE_NOTIFY_WINDOW_HANDLE, Ptr)
}

UnRegisterNotification(handle) {
    DllCall("UnregisterPowerSettingNotification", Ptr, handle)
}

WM_POWERBROADCAST(wp, lp) {
    Data:=NumGet(lp+20,0,"UChar")
if (Data=1) {
  Run, C:\DevCon\DevCon.exe rescan,,Hide
}
}`

**Comment by weenan** [comment]
I do not recall having this issue with the same setup when I was using the TV speakers. I am now using external speakers via a DAC.

Are you using a soundcard or the HDMI audio driver of the GPU? Maybe try reinstalling the audio driver. AMD or Nvidia?

**Comment by elduds** [comment]
> Hi@eldus, this is the first report of this issue. Does this happen when not using lgtv companion as well, i e when powering on manually?

Yes, it also sometimes happens with "Manage this device" switched off in LG TV Companion. I've not figured out the exact set of criteria to trigger the issue and seems random now both with and without the companion enabled.

**Comment by elduds** [comment]
> Are you using a soundcard or the HDMI audio driver of the GPU? Maybe try reinstalling the audio driver. AMD or Nvidia?

Yes, I'm using HDMI NVIDIA High-Definition audio driver of the GPU. NVIDIA RTX4070Ti, but also happened with the 3070 I was using previously. I will have a play with the audio driver.

**Comment by elduds** [comment]
> Hi@eldus, this is the first report of this issue.

OK, sounds like this is something specific to my setup and if so isn't a useful feature for LGTVCompanion. Might leave the issue open to see if anyone else has similar problems?

**Comment by JPersson77** [comment]
Sounds good! See if devcon can automate some of it for you. Enabling "always ready" on the C2 can potentially help with the issue too

**Comment by elduds** [comment]
I've found a fix for this and it's not unique to LG TV Companion nor to LG TVs, but rather a problem with the way NVIDIA configures timeouts in their HDMI audio driver. The instructions here resolved the issue for me:

From https://www.reddit.com/r/ValveIndex/comments/c72pg0/comment/esmjkz4/:

> I got the instructions from here: https://h30434.www3.hp.com/t5/Notebook-Audio/3-seconds-delay-to-play-sounds-through-headphone/td-p/6631359/page/
>Find HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class{4d36e96c-e325-11ce-bfc1-08002be10318}\xxxx\PowerSettings
>Where 'xxxx' is one of keys which contains DriverDesc value 'Nvidia High Definition Audio'. (Mine was '0000')
>Note: There may be multiple ones containing PowerSettings, for example 'Realtek High Definition Audio'. Do not change those.
>Within PowerSettings, You'll find there are three binary values and set them to:
> ConservationIdleTime = ff ff ff ff;
> IdlePowerState = 00 00 00 00;
> PerformanceIdleTime = ff ff ff ff.
>Default values are all 00 00 00 00 which disables power settings, but driver somehow overrides it with 0a 00 00 00 which is 10 seconds (0x0a = 10) and is by default in driver.

I've been running with these settings for the past two days and have not seen a recurrence of the issue.

**Comment by elduds** [comment]
> > Are you using a soundcard or the HDMI audio driver of the GPU? Maybe try reinstalling the audio driver. AMD or Nvidia?
> 
> Yes, I'm using HDMI NVIDIA High-Definition audio driver of the GPU. NVIDIA RTX4070Ti, but also happened with the 3070 I was using previously. I will have a play with the audio driver.

Uninstalling and reinstalling the driver and using a different NVIDIA game ready driver package did not resolve the issue. See above for the ultimate fix.

**Comment by JPersson77** [comment]
That is an interesting find. I have connected an amp and projector to my PC and I have resorted to using SoundKeeper to play an unhearable sound to prevent the HDMI from timing out and this might solve that. Need to try :)

Thanks for feedback!

**Comment by JPersson77** [comment]
closing. feel free to reopen if needed
