### ISSUE TITLE
[Request amd Bug] Shortcut to turn off the panel; Donation button doesnt work

### ISSUE THREAD

**Issue by Mrozeko** [JPersson77/LGTVCompanion#122]
[Request]
LG TV's have a function in the selfcare Menu that only turn the panel off and not the TV.
It would be nice to have (or to set) a shortcut to turn the panel off.
maybe with this Luna command?

luna-send -n 1 'luna://com.webos.service.tvpower/power/turnOffScreen' '{}'

If i make a break or just leave my desk i always want to turn off the panel....

[BUG]

I clicked on "Support your local Software Developer" and clicked "Yes" to open the Browser but nothing happen.

**Comment by Mrozeko** [comment]
Thank you a lot!!! This is awesome!!! Maybe the donation button should be fixed :)

**Comment by JPersson77** [comment]
Hi @Mrozeko it should open the default browser. Not sure why that does not happen on your system. I will assume you have a default browser set? Maybe I can add a "copy link" option for occasions like this. Do you mind checking if you can access this link? [Paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=jorgen.persson@gmail.com&lc=US&item_name=Friendly+gift+for+the+development+of+LGTV+Companion&no_note=0&cn=&currency_code=EUR&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted")

**Comment by Mrozeko** [comment]
Hey JPERSSON,

i just set a different browser and the old browser back... It work now, so it was a local failure :/ sry... 
Thread can be closed :) Thank you for this awesome Tool!!!

**Comment by JPersson77** [comment]
Thanks too! :)
