### ISSUE TITLE
TV wakes but not getting signal

### ISSUE THREAD

**Issue by d1rtyyyy** [JPersson77/LGTVCompanion#126]
SETUP:
Windows 11 Intel i9 3090 ti via HDMI Ultra High Speed 8k 1 meter cable to LG C2 42" HDMI (eARC/ARC) Port 2

The TV wakes as soon as I touch the mouse/keyboard but it wakes to the splash screen of no input and I hear/see the PC wake up but it won't switch. If I leave it for like 2 minutes, it finally displays the desktop. I turned off FAST BOOT & Hibernate but acts the same. 
Anyone else had this issue?? 
Thanks!!

**Comment by JPersson77** [comment]
hi @dirtyy sorry for delayed feedback. So according to your description I read that the PC wakes up from sleep/hibernate when you move the mouse, which in turn triggers the lgtv companion app to turn the TV on. But there is no image being output from the graphics card for 2 minutes. If I understand you correctly then it sounds like the app works correctly but the graphics card is acting weird. I assume you have tried updating drivers etc. 

Or should I read that the automatic hdmi port switch by LGTV companion takes two minutes to finalise after the TV was powered on?

**Comment by d1rtyyyy** [comment]
Hi! Thank you so much for responding directly! That is correct, your app works perfectly, it's just after the TV powers on, it isn't receiving the signal from the PC for about 2 mins and sometimes not at all and I need to force shut-down with the power button because I cannot see the desktop. And yes, I keep the Nvidia drivers always updated because this is my gaming rig. To trouble-shoot, I turned off Fast Boot in Win11 as well as Hibernate but it didn't make any difference. I was really putting it out there on the forum to see if any others might have encountered this and if there was a resolution.

You have a GREAT app and it is very much appreciated for all your efforts!
I'll be sure to buy you a coffee! 😊

Thank You
Bram

________________________________

**Comment by JPersson77** [comment]
Allright thanks too Bram! Sounds like an annoying issue, wish I had more input for you

**Comment by d1rtyyyy** [comment]
Yes! It ended up being the SIMPLINK HDMI-CEC TV setting on the LG C2. Once I turned that on, it seems to be working flawlessly!
