### ISSUE TITLE
Error Turning On/Off multiple devices with batch file.

### ISSUE THREAD

**Issue by KiNGKiMO** [JPersson77/LGTVCompanion#128]
Hello,

![image](https://user-images.githubusercontent.com/11393200/226501685-1efef826-e277-4c47-8bf4-64a442b465ac.png)

I'm geeting this error "Failed to connect to named pipe. Service may be stopped" when I'm trying to turn on multiple devices with a batch file, thing is this batch files takes arguments and it's being executed from another app which we multi select devices and select to turn on/off.

So, if you execute "LGTV Companion.exe" multiple times so fast you get this error..
This can be replicated with a normal batch file like this:

`START "LGTV Companion" /D "C:\Program Files\LGTV Companion\" "LGTV Companion.exe" -poweroff Device1

START "LGTV Companion" /D "C:\Program Files\LGTV Companion\" "LGTV Companion.exe" -poweroff Device2

START "LGTV Companion" /D "C:\Program Files\LGTV Companion\" "LGTV Companion.exe" -poweroff Device3

START "LGTV Companion" /D "C:\Program Files\LGTV Companion\" "LGTV Companion.exe" -poweroff Device4
`

**Comment by JPersson77** [comment]
Hi, thanks for the bug report. I will look into it.

As a workaorund, if you can modify the script, the following should work: 

"LGTV Companion.exe" -poweroff device1 device2 device3 device4

And you can do this as well:

"LGTV Companion.exe" -poweroff device1 device2 device3 -poweron device4

Sounds like a cool setup :D

**Comment by KiNGKiMO** [comment]
Hello, thanks for such a great app..
I'm aware that LGTV Companion.exe takes multiple devices as arguments, but unfortunately this is not an option, the app we're using executes a batch file at Turn on/off events, so we've no options really, when we select multiple devices the batch is executed multiple times, each with TV number as parameter.

**Comment by JPersson77** [comment]
Looking into it

**Comment by JPersson77** [comment]
A fix has been implemented for the next release. You can download the dev build here if you would like to try it. Discord: https://discord.gg/7KkTPrP3fq

**Comment by KiNGKiMO** [comment]
Sure, will try it tonight...
Thank you so much.

**Comment by JPersson77** [comment]
v2.2.0 was published with the fix. I'll close this issue but feel free to repoen if needed
