### ISSUE TITLE
Companion not detecting game running

### ISSUE THREAD

**Issue by atledreier** [JPersson77/LGTVCompanion#129]
Lately I've seen the tv turn off (idle mode) when gaming, This happens in several games, even though there's plenty of input going on.
I don't know if this is a windows issue, or a Companion issue, but it sure is annoying to have to turn the tv back on while gaming. My other screens stay on.

**Comment by JPersson77** [comment]
Hi @atledreier can you please start a command prompt and execute **"c:/program files/ lgtv companion/LGTVdaemon.exe" -show**

This should display a status window where the idle timer is shown. This may be able to help identify what is going on and if there are particular input methods that are problematic.

Then if you can enable logging and copy it together with config.json to pastebin or similar and paste the link here I can have a look.

**Comment by atledreier** [comment]
Yes, sorry!

The counter was great, and the Companion is doing what it's supposed to. It something else that sends my computer into an idle state. The search continues.
I'll close this issue.
