### ISSUE TITLE
Idle Mode turning off without turning back on instantly.

### ISSUE THREAD

**Issue by thomastank** [JPersson77/LGTVCompanion#130]
I have been using LGTV Companion for roughly 2 months with no issues. Today  this started happening today. tried searching for a solution online but was unable to find any. Attached is the  log file. I made sure to have it happen much more consistently by having it set to 1 min intervals. I am able to wake with the remote however it instantly turns it back off. Sometimes does not come back without disabling it and turning it back on manually. Anyhow here's the log hope it is informative.

To be clear because my long explanation looks confusing to me. After the App enters User idle mode. instead of instantly turning the display back on it will not. however one time i was able to get it to recognize mouse and keyboard after 13 seconds and turn back on.
[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/11090189/Log.txt)

**Comment by thomastank** [comment]
the issue persisted after 9:28 i had to disable the feature to disable it. I can force it to happen  by enabling it again if you'd like. Also no I'm not running any vm or sandboxes.  When I can get it to work. It will take up 20 seconds or more to come back on its own, where it used to be instantly

**Comment by thomastank** [comment]
[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/11091532/Log.txt)
 caused it to happen once. turns off after 1 minute interval as i set it to that. then took 30 seconds roughly to come back on; unlike the instantaneous behavior of before.  i've not changed any settings from before or after

**Comment by JPersson77** [comment]
Hi, there are anomalies in the log but nothing conclusive yet. 
- the user mode daemon seems to be restarted every time the PC comes out of sleep. It should however only start on system boot. 
- the communication with the TV looks to be slow. It takes seconds between responses.
- between 0900 and 0928 there was some serious spamming of commands to the TV, which seems to be triggered by having set user idle to 0 minutes. I didn't think that it was possible to set it to 0. That would explain the issues you noticed, at that time. 

Can it be that you, for whatever reason, have multiple LGTVsvc.exe or LGTVdaemon.exe running (check in task manager)? Maybe try pulling the mains cord on the TV for a couple of minutes and then plug it back in. And restart the PC for good measure.

**Comment by thomastank** [comment]
![image](https://user-images.githubusercontent.com/19907160/228315759-2f200401-29f0-4350-9af4-b3802254b749.png)
 heres my task manager  im not sure if this is what you mean however ill pull the power plug on the tv to test it now.

**Comment by thomastank** [comment]
[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/11092438/Log.txt)
I doubt unplugging it and plugging it back in will show up here however heres the log file for it aswell.
however i figure this might be helpful. noticed no change after powering back on.

**Comment by JPersson77** [comment]
Can't see any change either in the log. 

So, since the issue started with the "0 minutes user idle" configuration at about 0900 it would make some logical sense that whatever issue there is now is a consequence following from that.

It was some serious network spam going on during that half hour so hence why I'm suggesting to also try restarting the PC, routers, TV etc in the hope of getting the normal response times of the TV over the LAN back. 

I have already added a bugfix/heck for invalid values upon loading from the configuration file for next release.

**Comment by thomastank** [comment]
I've reset the TV / computer multiple times. I will try the router now though!

**Comment by thomastank** [comment]
Resetting the router seemed to fix the issue! you are a smart person I am grateful for all your hard work and effort. ill be sure to get you a coffee sometime.

**Comment by JPersson77** [comment]
Lovely! Happy to get it working again!
