### ISSUE TITLE
Shortcuts to power off or reboot 

### ISSUE THREAD

**Issue by KrisDee1981** [JPersson77/LGTVCompanion#131]
Is it possible to power off or restart windows using some kind of shortcuts, so application actually doesn't turn off the TV.
I'm asking about this because restart sometimes turn off the screen, or I want to turn off computer, but still keep TV on.

**Comment by JPersson77** [comment]
Hi @KrisDee1981 

Not directly in the app, but you can easily do it in a .bat file or similar. For example you can do this to shutdown the computer and keep the screen on:

```
"C:/program files/lgtv companion/lgtv companion.exe" -autodisable device1
shutdown.exe /s /t 00
```

or this to restart the computer and ensure the screen is not turned off:

```
"C:/program files/lgtv companion/lgtv companion.exe" -autodisable device1
shutdown.exe /r /t 00
```

**Comment by KrisDee1981** [comment]
That's fantastic. What if I like to shutdown the computer, keep the screen on, and set HDMI4(My PS5😝)
Is it?
"C:/program files/lgtv companion/lgtv companion.exe" -autodisable device1 -sethdmi4
shutdown.exe /s /t 00

**Comment by JPersson77** [comment]
you almost got it 

"C:/program files/lgtv companion/lgtv companion.exe" -autodisable device1 -sethdmi4 device1
shutdown.exe /s /t 00

**Comment by KrisDee1981** [comment]
Thank you for your help.

**Comment by JPersson77** [comment]
Thanks too!
