### ISSUE TITLE
Sunshine (GameStream alt) option still waking up TV?

### ISSUE THREAD

**Issue by Hukuma1** [JPersson77/LGTVCompanion#133]
<img width="323" alt="lgsunshine" src="https://user-images.githubusercontent.com/54511555/232259579-8a77b429-e4bd-4134-b715-99ea3597b2bc.png">

I have the option for the TV to go to sleep if/when someone initiates a remote play session. It doesn't seem to be working. Nor do I see anything showing up in the log file.

Does LGTV Companion expect Sunshine to be installed via the service only by any chance? I am using a portable version install instead.

**Comment by JPersson77** [comment]
Hi @Hukuma1,

Short story, Sunshine needs to be installed and at minimum default logging must be enabled.

Longer story, there is no direct way for LGTV Companion to know when sunshine starts streaming (request was made to lizardbyte about this but they have a large todo) so at the moment the app relies on a registry key to get the installation path of sunshine, where the configuration  can be found. In the config the path to the log can be found.  And by parsing the log LGTV companion knows when sunshine has started streaming.

**Comment by Hukuma1** [comment]
Ah I see! Thank you for the quick reply. Makes sense. Any chance of knowing what the registry key is so people can manually point it to their `sunshine.log` location? The portable version of Sunshine doesn't make any registry entries unfortunately.

Also, not sure if this is out of scope for this project, but how would this setting affect if I play locally using my LG screen with someone remotely connecting to my Sunshine server for multiplayer? Would it still keep the screen on? Or would it turn off on any remote connections?

**Comment by JPersson77** [comment]
It is HKLM/SOFTWARE/LizardByte/Sunshine. I guess I could add an option for manually setting the .log location. Was sort of hoping that I'd get an official solution soon 📦 

Yeah you can expect the feature to turn the screen off, so if you are in front of the PC that is out of scope at the moment.

Seeing your edits, maybe there is a bug. Can I get the full log and also config.json please. Add them to pastebin or similar and paste links here

**Comment by JPersson77** [comment]
Hi @Hukuma1 any input on the above?

**Comment by Hukuma1** [comment]
Sorry for the delay. _It does work!_ Just tried the latest nightly and your latest release from 30 mins ago. I even put the default Sunshine settings back on for the log location (`Sunshine\config\sunshine.log`). 

There is about a 10 second delay though for the screen to go to sleep. Is this timer by design? Upon disconnect from Sunshine it does seem to wake up without any delay.

```
Thu 13:45:32 > LGTV Companion Daemon v2.2.0 is running.
Thu 13:45:32 > -daemon started
Thu 13:45:32 > System requests displays ON.
Thu 13:45:52 > Sunshine gamestream connected.
Thu 13:46:02 > -daemon remote_connect
Thu 13:46:27 > Sunshine gamestream disconnected.
Thu 13:46:28 > -daemon remote_disconnect
```

Also, when using it I'm testing it on iOS and if I hit back, without "quitting the app/server" (still connected to Sunshine host), the screen wakes up. If I resume app, it will again sleep the screen. Is it possible to not wake up the screen until the app is fully exited out? I am still technically connected to Sunshine server, it's just in a paused state. Not sure if Sunshine sends a different message when in this paused state or not, so maybe that's a limitation on their end.

Apart from that, the only thing that jumped out was that I couldn't move my mouse or press a button to turn my screen back on, in case I wanted to play remotely with someone on the same machine. Is turning on the screen with a remote my only option here?

**Comment by JPersson77** [comment]
Hi, 

no worries, thanks for the feedback! Looks like it is working as intended at the moment. Yes there is an intentional delay of about 10 secs to cover for situations where the display is powered on when streaming starts, this occurs f e with steam and RDP, don't remember how geforce experience did it. It's to avoid a race condition between screen on/off leading to an undefined state

It seems that sunshine stops streaming when you press back on the IOS device, even though it is still connected. I can check if it would be possible to have it as a user configurable option.

Yep, you cannot use your local mouse to power on the screen as the detection for that is disabled during a remote session, since otherwise the remote mouse input would wake the screen up. But you could f e quite easily set up a keyboard shortcut using the command line parameters to power on the screen so you don't have to reach for the remote.

**Comment by Hukuma1** [comment]
Nice, didn't think of the keyboard shortcut. Great tip, thank you!

Only other thing I noticed was if my screen was already off due to idle, it would still wake up and then go to sleep again on Sunshine connection. Is there a way to keep it asleep if it's idle to begin with?

**Comment by JPersson77** [comment]
You welcome! :) 

It is Sunshine powering on the attached monitors and not much to do to prevent I'm afraid

**Comment by Hukuma1** [comment]
Gotcha. Well, since everything seems to be working as intended will close this out. Thanks again! Keep up the great work on this. Really makes the TV amazing as a monitor.

**Comment by JPersson77** [comment]
Thanks too!!
