### ISSUE TITLE
Ability to change Picture Mode?

### ISSUE THREAD

**Issue by imagina9900** [JPersson77/LGTVCompanion#137]
Hi, 

First of all thanks for this excellent and useful app!

This is not an issue but an idea for an enhancement.

If it's possible to change the picture mode via software, wouldn't it be viable to create some sort of monitoring for specific windows processes and apply the picture mode when these  processes are running?

Main idea:

I start call of duty and my TV auto sets itself to Game Mode. When I close the game, it goes back to standard Picture Mode.

Thanks!

**Comment by JPersson77** [comment]
Hi @imagina9900, 

Thanks for the suggestion! This is the sort of thing I imagine would be an excellent application for the new external API/scripting support in v2.2. For example, a user defined script could scan the process list every five seconds and when a game is detected (by some means, f e processes in a certain folder, with a certain name, with a certain GPU usage etc) it would send a command to the TV via LGTV Companion to f e trigger a picture mode.

I'll keep this thread open and if you or anyone wants to give it a go I'll be glad to support

**Comment by imagina9900** [comment]
I can try and have a look myself, although I'm not the best dev out there. :)

Is there any documentation regarding the types of commands that I can sent to the TV via API? By looking at your examples in the scripts folder I can only see more "basic" actions like SYSTEM_DISPLAYS_OFF, etc.

Thanks!

**Comment by JPersson77** [comment]
Hi @imagina9900 that is nice. What you've seen is what you get at the moment, just to get a first version with support for external communications out and get some feedback in. The general idea, I think, is to eventually open up the LG API as much as possible so if you want to maybe have a look at this I wouldn't mind looking into how to best add the support for controlling the display modes.

**Comment by imagina9900** [comment]
I'm happy to do it as soon as you figure out how to add support for the display modes.

**Comment by imagina9900** [comment]
I would say it makes sense to keep the same approach, using the command line parameters to set this. This way you can ensure consistency throughout the app. 

I will also start doing some tests with autoIT scripting.

**Comment by JPersson77** [comment]
Heya, sorry bout the delay but I have a test version for you if you wanna hit up Discord? https://discord.gg/7KkTPrP3fq

**Comment by JPersson77** [comment]
closing due to the release of v3 where this has been implemented. Thanks for helping testing it
