### ISSUE TITLE
42" LG OLED Flex won't turn on manually or through Windows resume/wake.

### ISSUE THREAD

**Issue by CubicleGangster** [JPersson77/LGTVCompanion#138]
Have an LG C1, G2, and now an LG Flex.  LG Companion works as expected for the G2 , and power off commands work for the LG Flex, but power on does not work, nor does turning on from monitor wake/computer resume.  Work around is to use the button on the bottom of the monitor to power on and let LG Companion handle the power off portion.

**Comment by JPersson77** [comment]
Hi @CubicleGangster the app power on the TV by means of wake-on-lan. Not sure about the Flex but below are the instructions from the readme. Can you confirm you have enabled "on with mobile" (or the equivalent on the Flex). I will add it to the readme if you can let me know where the setting is located on the flex?! Cool device! :)

`Ensure that the TV can be woken via the network. For the CX line of displays this is accomplished by navigating to Settings (cog button on remote)->All Settings->Connection->Mobile Connection Management->TV On with Mobile, and then enable 'Turn On via Wi-Fi'. For C1 and C2 it's All Settings->General->Devices->External Devices->TV On With Mobile->Turn on via Wi-Fi. NOTE! This step is needed regardless of using WiFi or a cable.`

**Comment by CubicleGangster** [comment]
A quick firmware update, and it is working as intended now!  Mobile on was setup just like on my other LG screens, but it seems like the Flex needed a quick software update.  Loving the device and thank you for all the work you do...you make these amazing screens even better!
