### ISSUE TITLE
Feature requests here

### ISSUE THREAD

**Issue by catapultam-habeo** [JPersson77/LGTVCompanion#14]
Apologies for posting this as an issue rather than on the forum mentioned in the documentation; I don't speak Swedish at all, so didn't feel it was appropriate to join that community.

Would is be possible to add a feature to detect valid inputs on other HDMI port(s), and if lacking them, switch the input back to a specified HDMI port. (The example user story here would be switching back to a PC input after a game console is turned off.)

**Comment by JPersson77** [comment]
Hi, no worries. Thanks for the feature request. I have not investigated so don't know how practically feasible it is to detect a lack of input. It is not part of the current scope for the application. But I will think about it a bit

**Comment by aabdellah** [comment]
Would it be possible to switch TV HDMI input on PC wake to replicate HDMI-CEC behavior? 
Fo example sometimes my last input is Apple TV, but I would like the PC to change the input when I wake it like how the Apple TV changes the input when it's awake. That way, no need to change the input manually when PC wasn't the last input.

**Comment by JPersson77** [comment]
Hi aabdellah,

yeah that might well be sort of possible and fit with the app. Thanks for the suggestion!

@catapultam-habeo I hijack your thread and maybe we can keep feature requests in here, hope that is ok

**Comment by JPersson77** [comment]
@aabdellah check out v1.6.0. A feature was implemented to let the PC set display input on system boot or resume from low power mode. Does not trigger on user present as I did not really think that would be useful. Let me know how it works for you

**Comment by aabdellah** [comment]
@JPersson77 working perfect, no need to manually change any inputs now. Thanks for the fast implementation.

**Comment by WilliamLeGod** [comment]
Still I would love to have this feature "Would is be possible to add a feature to detect valid inputs on other HDMI port(s), and if lacking them, switch the input back to a specified HDMI port. (The example user story here would be switching back to a PC input after a game console is turned off.)"

**Comment by JPersson77** [comment]
I am not aware of any potential way to query the device for active inputs, but I will keep it in mind

**Comment by catapultam-habeo** [comment]
A version of this application that doesn't rely on a service or daemon, and can simply send commands would be hugely useful.

My particular use-case is to control the TV from a linux machine, but I imagine someone wanting to do something weird with windows scripting might have a use for it also.

**Comment by dechamps** [comment]
@catapultam-habeo If all you need is to send commands to the TV from a Linux command line, what you're looking for is [bscpylgtv](https://pypi.org/project/bscpylgtv/). For powering on the TV you can use any Wake-on-LAN tool (I recommend `etherwake`).

**Comment by jcronic420** [comment]
Is there a way to have it not turn off LG C1 when restarting pc? Maybe there is already an option, not sure. I only want it to turn off TV when shutting down.

**Comment by JPersson77** [comment]
Please confirm the "restart words" in the global options are configured
correctly. I e if you are on a us/uk version of windows you should ensure
there is a tick in the checkbox for "restart" only but if you have another
localisation of windows you need to tick the equivalent box for the word
which translate to "restart". You can click the "what's this?" link in the
options to read more about why you need to do this.

**Comment by jcronic420** [comment]
Yes only have restart checkbox selected. Still turns off TV when restarting.

**Comment by dechamps** [comment]
> My TV often goes into low powermode but it's essentially a dim screen, i'd like to just disable this option if possible as the TV likes to take a random delay amount of time to resume to the normal state from this low brightness state.

It looks like you are referring to [ABSL/TPC](https://tftcentral.co.uk/articles/oled-dimming-confusion-apl-abl-asbl-tpc-and-gsr-explained#ASBL-Auto-Static-Brightness-Limiter-also-known-as-TPC-Temporal-Peak-Luminance-Control). I'm not aware of any way to disable that remotely. The only known way of disabling ABSL/TPC is to use the LG service menu (which you can access using a service remote or something like [bscpylgtv](https://github.com/chros73/bscpylgtv)).

I guess LGTVCompanion could provide a "convenience" command to open the service menu remotely (which is in fact technically feasible), but I'm not sure if it's a good idea to encourage users to do that - you can cause serious problems if you mess with service menu options you don't understand, and some users worry about warranty implications.

**Comment by oooseun** [comment]
Sounds like it exactly, thanks! I'll look into it 👯

**Comment by JPersson77** [comment]
all feature requests here are implemented and the thread is not really used anymore so I'm closing it
