### ISSUE TITLE
Prevent Restart from Turning off TV

### ISSUE THREAD

**Issue by WilliamLeGod** [JPersson77/LGTVCompanion#142]
When I restart PC, it just happens really randomly but like 50/50 of the time it turns off TV. Is it possible to make a specific option for not turning off TV when PC restart? (Every settings in LG companion is at default - restart ticked but not shutdown and turn off)

Thanks for your hard work!

**Comment by JPersson77** [comment]
Hi, 

Firstly please check the log. There should be a log entry for each failed restart that the app could not determine if it is a shutdown or restart. Maybe upload the log so I can have a look. I've tweaked this a bit in the next release so try again then. 

Secondly, when the system shutdown/reboot is undeterminate the app will, as you have noticed, shut off the display. The only way currently to bypass that behaviour is to disable automatic management, for example via command line. 

I can think about whether it's feasible to implement what you have suggested but i'd rather fix the root problem. Mind you on all my PCs this works perfectly (although the actual mechanism can only be described as a necessary hack)

**Comment by JPersson77** [comment]
hi @WilliamLeGod see if v3.0.0 makes a difference please

**Comment by WilliamLeGod** [comment]
Fixed!!! You sir are a genius!

**Comment by JPersson77** [comment]
Closing - resolved
