### ISSUE TITLE
TV doesn't turn off when at desktop!

### ISSUE THREAD

**Issue by WilliamLeGod** [JPersson77/LGTVCompanion#143]
So whenever I'm in a game, sleep PC will turn off TV but when I'm at desktop, sleep NEVER turns off TV
Could you investigate this? (Latest version and everything at default, test works fine)

Thanks!

**Comment by JPersson77** [comment]
Hi, can you please upload log.txt and config.json to pastebin and paste the links here. Please also indicate relevant timestamps.

**Comment by JPersson77** [comment]
hi @WilliamLeGod any input wrt the above?

**Comment by WilliamLeGod** [comment]
Totally fixed bro! My dream came true!

**Comment by JPersson77** [comment]
Thanks for feedback! Closing this issue - resolved
