### ISSUE TITLE
LG C1 no longer able to be turned off or on from latest update

### ISSUE THREAD

**Issue by ThinkSalat** [JPersson77/LGTVCompanion#144]
My TV updated last night and the LGTV Companion said something about the topology being off. I have reconfigured completely and the test doesn't do anything anymore.

**Comment by JPersson77** [comment]
Hi @ThinkSalat please enable logging and paste the log here and I'll have a look

**Comment by ThinkSalat** [comment]
https://pastebin.com/gPsaFQ5A here you go. Thanks!

**Comment by JPersson77** [comment]
Hi again, the app cannot communicate with the TV at all it seems. Restart router/switches/access points maybe. It has helped some in the past so that's why I'm suggesting it (if you have already triple checked that the configuration is correct)

**Comment by ThinkSalat** [comment]
Turns out my ip and mac address changed. Must have been related to the
update. Strangely, I had deleted the previous configuration and hit scan
and it auto filled the incorrect information.

**Comment by JPersson77** [comment]
Yeah that is a bit weird that the MAC changed. Did it change from connecting via cable to wifi or the other way around possibly?

The Scan feature picks up the data from the digital media devices section of the device manager and if windows has not picked up  the changes then the app will pick up the wrong data indeed.

Happy it seems to be sorted!

**Comment by ThinkSalat** [comment]
Nothing changed aside from a typical update to the tv itself. But I couldn’t imagine that causing a change in mac address!On Jun 8, 2023, at 12:09 PM, JPersson77 ***@***.***> wrote:﻿
Yeah that is a bit weird that the MAC changed. Did it change from connecting via cable to wifi or the other way around possibly?
The Scan feature picks up the data from the digital media devices section of the device manager and if windows has not picked up  the changes then the app will pick up the wrong data indeed.
Happy it seems to be sorted!

**Comment by JPersson77** [comment]
closing due to being resolved
