### ISSUE TITLE
Pause LGTVCompanion

### ISSUE THREAD

**Issue by stealth93rt** [JPersson77/LGTVCompanion#146]
Is it possible to put a pause feature into this? Sometimes I want to watch a video on the C2 and I have to kill the process running for it to stop turning the TV off.

Appreciate the work on this - thanks!

**Comment by dechamps** [comment]
If you have "user idle mode management" enabled in the LGTVCompanion settings, then you are explicitly asking for LGTVCompanion to aggressively turn off the TV in the absence of user input, even when running full screen apps such as full screen video.

If you don't want this, and instead want to rely on standard Windows display power management (which will *not* turn off the display when using full screen apps), then you should disable "user idle mode management" and instead configure a Windows black screensaver and/or use the Windows display power timeout setting. LGTVCompanion will still turn off the TV if it detects that Windows wants to turn off the display. This may be more convenient than attempting to "pause" LGTVCompanion.

**Comment by stealth93rt** [comment]
Thank you I will test with this setting.

**Comment by JPersson77** [comment]
@dechamps make good points, I also suggest you try to first configure the app and the system so it does what you want. There are quite a few possibilitoes as well to configure user idle mode in the app to your likiing. To directly answer your initial question, you can use the command line interface to do what you ask for, check out the -autodisable and -autoenable command line
