### ISSUE TITLE
Latest 3.07 big issue for me!

### ISSUE THREAD

**Issue by WilliamLeGod** [JPersson77/LGTVCompanion#147]
In previous version, after first sleep success, wake pc up, then sleep again, up and again, TV off as expected but in this 3.07 latest version, the 2nd sleep, 3rd sleep never happen

Could you fix this?

Thanks for your hardwork

**Comment by JPersson77** [comment]
Hi @WilliamLeGod can you paste the log and config.json to pastebin, copy the links here and indicate the relevant time odes please and I will have a look

**Comment by WilliamLeGod** [comment]
Hi!

Pastebin is not available atm so I can't upload. Is there another way?

**Comment by JPersson77** [comment]
Can we talk on discord? https://discord.gg/7KkTPrP3fq

**Comment by WilliamLeGod** [comment]
Yes I'm chatting there now as same nick name here!

**Comment by JPersson77** [comment]
Hi @WilliamLeGod is the patched version still working better for you?

**Comment by WilliamLeGod** [comment]
Everything has been great so far. Thanks so much for your work!

**Comment by JPersson77** [comment]
Added a user configurable option in v3.1.5. Default should be fine. Closing the issue :)
