### ISSUE TITLE
1.5.0 no longer triggering sleep on WIndows 11 lock screen

### ISSUE THREAD

**Issue by crainger** [JPersson77/LGTVCompanion#15]
Hi,
since 1.5.0 update I've noticed sleep doesn't trigger on the windows 11 lock screen. Rolling back 1.4.2 fixes it.

**Comment by JPersson77** [comment]
Hi, thanks for you bug report. +Are you on a laptop or stationary PC? Does yuor PC not go to sleep at all, or does the screen not turn off in response to the PC going to sleep?

Can I trouble you to upload a log from v142 and v150 to pastebin and point out the timestamps when the issue is occuring?

**Comment by crainger** [comment]
I'm on a desktop which is connected to HDMI 1
TV is an LG 48CX
The PC was sleeping, but was the TV sleep was not trigger. It just showed the no signal 
I grabbed the logs. https://pastebin.com/9idTFYLp
My process was to 

- enable logging
- Win+L to lock my PC
- wait for the timeout on lockscreen which is 30 seconds I believe.
- wait for screen to "tick"
- move mouse to wake back up
- I installed 1.5.0
- Win+L to lock my PC
- wait for screen to "tick"
- move mouse to wake back up
- This worked ok. 
- So I enabled "Process power and screen off events when the display source is set to HDMI" :1
- Win+L to lock my PC
- wait for screen to "tick"
- move mouse to wake back up
- This did not work.
-  enabled "Process power and screen off events when the display source is set to HDMI" :1
- Win+L to lock my PC
- wait for screen to "tick"
- move mouse to wake back up
- This worked ok. 

So maybe just related to the "Process power and screen off events when the display source is set to HDMI" feature?

**Comment by crainger** [comment]
As per my other issue.
I think I worked it out. I thought my PC was connected to HDMI 1, but it is HDMI 2 (I moved it for WFH) so I have set the on;u process option to HDMI 1.
Apologies, it's all user error. I'm so embarrassed right now.
