### ISSUE TITLE
Latest 3.07 not waking up monitor sometimes

### ISSUE THREAD

**Issue by sammok83** [JPersson77/LGTVCompanion#150]
Hi,

Intermittently, my monitor is not waking up after going to sleep in idle mode. 
Used to work well before.
Here's the latest log as attached. Please refer to the last lines in the log.

[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/11881298/Log.txt)
Thanks.

**Comment by JPersson77** [comment]
Hi @sammok83 I can see that there are some instances when the PC/app has trouble communicating with the display (or at least it is slow). Can you please point out some time codes when the issue occurs though?

Are you using wifi or wired connection to the TV?

**Comment by sammok83** [comment]
I'm using wired connection to the TV (network cable).
The last lines are when it happens

**Comment by JPersson77** [comment]
Thanks,

I see a couple of these in the log:
```
Tue 20:33:56 > Device1, Best route to IP - interface index 43 LUID 6473924464345088 route protocol 3; r**oute is not local, aborting!**
Tue 20:34:15 > Device1, Best route to IP - interface index 10 LUID 1689399632855040 route protocol 2
```

My guess is then is that one of these interfaces
`Tue 17:21:27 > Host IPs detected: 192.168.1.100, 10.2.244.20`

...are for some reason not available /does not have connectivity at the time of starting to broadcast WOL packets. 

Can you try restarting router, switches, access points maybe? Reason I ask is becuase I've seen it solve similar situations.

**Comment by JPersson77** [comment]
See if v 3.1.5 improves your issue

**Comment by sammok83** [comment]
Ok will do. Thanks for the support.

**Comment by JPersson77** [comment]
hi @sammok83 any feedback wrt v 3.15 and the issue?

**Comment by sammok83** [comment]
@JPersson77 It does happen but I seldom see it like before. A router restart I think does the trick. Thanks. We can close this if you want.
