### ISSUE TITLE
Can Power Off [or ScreenOff] Command Be Sent To TV During Windows Restart?

### ISSUE THREAD

**Issue by githwithit** [JPersson77/LGTVCompanion#156]
Everything is great with LGTVCompanion 3.1.5 with an LG C2 and Windows 10 except this.

When I do a Windows Restart, the LG starts displaying bright slideshow images after Windows is off and during the BIOS boot up.

It would be nice if LGTVCompanion issued a PowerOff command to the LG at the tail end of the Windows shutdown process before the HDMI signal to the TV stops and the LG slideshow starts. [optionally, ScreenOff might be better]

If LGTVCompanion  worked liked this, a Windows restart would have a 60-90second (depending on BIOS boot time) period when the LG is powered off and blank, then it would power on when Windows starts up.

I get around this LG slideshow during restarts issue by just doing a Windows Shutdown then pressing my PC power button to start up.

No matter this small issue, thank you for an amazing program!

**Comment by JPersson77** [comment]
Hi @githwithit 

There are two things you could try

1) go to the global options of lgtv companion and uncheck all "restart words". This will lead to restarts operating like a system shutdown and your display should be powered off, which I think you want.

2) go to the TV options and disable the slideshow images. This will give you a black "no signal" image until windows comes back

**Comment by githwithit** [comment]
1) perfect! I was unsure about the Additional options/Shutdown checkboxes so I let them be initially. I will try unchecking Restart to power off the display when it has no signal.
2) thank you for the display gallery tip! I found out that for LG hitting the Mute button 3x times quickly brings up a hidden menu that includes an option for "No Signal Image" which is On by default, flip it Off and no more slideshow!

**Comment by githwithit** [comment]
1) perfect! I was unsure about the Additional options/Shutdown checkboxes so I let them be initially. I will try unchecking Restart to power off the display when it has no signal.
2) thank you for the display gallery tip! I found out that for LG hitting the Mute button 3x times quickly brings up a hidden menu that includes an option for "No Signal Image" which is On by default, flip it Off and no more slideshow!

**Comment by JPersson77** [comment]
Thanks too! :)

**Comment by githwithit** [comment]
Sorry to re-open this but unchecking Restart does not stick:
1) run LGTV Companion v3.1.5
2) my TV is listed in the popup, Manage this device is checked, click Options in lower left
3) Additional options, Shutdown restart - uncheck [the box is empty now], OK button becomes active, click OK
4) LGTV Companion v3.1.5 window, click Apply, close window
5) run LGTV Companion v3.1.5 again, click Options
6) Shutdown restart is Checked (it should be unchecked)

**Comment by JPersson77** [comment]
Hi, thanks! No worries! Just tried it and You are correct. The default value is applied. I'll patch it for next release. As a workaround you can try to manually add the following in config.json under "LGTV Companion":

        "LocalEventLogRestartString": [
            "bogus"
        ],

**Comment by githwithit** [comment]
Thanks for the lightning fast response! I look forward to next update.
