### ISSUE TITLE
1.5.0 new idle feature not tiggering

### ISSUE THREAD

**Issue by crainger** [JPersson77/LGTVCompanion#16]
I haven't been able to get the idle feature to trigger with 1.5.0 under Windows 11.

I was testing using a 1 min timer at just the Windows desktop.

**Comment by JPersson77** [comment]
Hi, ok. First verify that LGTVdaemon.exe is running in the task manager once logged in (this is a user mode feature). It should be ran automatically. Can you then please start the LGTVdaemon.exe with commandline parameter "-show" and then observe the output. The "seconds ago" should increase when idle. At the minute mark the log shouild say -daemon useridle. Let me know how it goes please.

**Comment by crainger** [comment]
I think I worked it out. I thought my PC was connected to HDMI 1, but it is HDMI 2 (I moved it for WFH) so I have set the on;u process option to HDMI 1.
Apologies, it's all user error. I'm so embarrassed right now.

**Comment by JPersson77** [comment]
Ah that makes sense, don't be embarrassed it is easy to overlook stuff! Happy you figured it out mate! Thanks for your feedback!
