### ISSUE TITLE
Documentation improvement for "Always ready" feature

### ISSUE THREAD

**Issue by cristibctr** [JPersson77/LGTVCompanion#162]
When clicking on the "What's this?" button in the "Multi-monitor support (2022 models and onwards)" the note states that the feature is available on all 2022 models "(2022-models, A2, B2, C2 etc)" but I think this is only available on the C2 and G2 models from 2022. Due to limited online information on this matter, I cannot be entirely certain though it would be beneficial to make this adjustment to prevent others from investing unnecessary hours, like I did, attempting to troubleshoot issues with their TVs (I possess a B2 model).

**Comment by JPersson77** [comment]
Hi @cristibctr thanks for your feedback. For sure I will update the help text. Since I don't have access to all models (obviously) it's assumptions sometimes. Good to know B2 does not have "always ready"

**Comment by JPersson77** [comment]
Updated the in-app documentation /what's this? linke to reflect this information. Issue closed
