### ISSUE TITLE
PC hangs or reboots when screen goes to sleep mode

### ISSUE THREAD

**Issue by Antoon1955** [JPersson77/LGTVCompanion#163]
It worked fine form a while.
I'm not sure but the trouble might have started after updating to AMD driver 23.8.1.
Any idea how to fix this?

**Comment by JPersson77** [comment]
Hi @Antoon1955 why do you suspect this has to do with LGTV Companion? Can you provide more details and preferrably how to reproduce

**Comment by Antoon1955** [comment]
Thanks for the response!
I stopped the LGTV process  and the issue didn't occur anymore. But now I switched it back on and it also doesn't occur anymore. 
Maybe it is just the AMD driver. I'll monitor  this issue and see what I learn.

**Comment by Antoon1955** [comment]
It's not LGTV. It's something between Microsoft and AMD .

**Comment by Antoon1955** [comment]
Closed
