### ISSUE TITLE
TV test works but it's refusing to idle

### ISSUE THREAD

**Issue by Chaython** [JPersson77/LGTVCompanion#164]
Windows corrupted so I reinstalled it
I installed LGcompanion and resetup
The test is working but it only powers down/turns on, the inactive/idle feature is not working.

**Comment by JPersson77** [comment]
Maybe something on your pc is preventing idle. Execute c:/program files/lgtvdaemon.exe -show to get the daemon status window which has an idle counter. See if unplugging peripherals etc helps

**Comment by Chaython** [comment]
Here is my log, all of my configuration is the same except I tried IP or subnet etc, I also tried wired and wireless and currently have it connected to both.
I tried deleting connected device history, but it never prompts for resyncing when running lg companion
and because the test works IDK why the normal idle process isn't.


Sun 16:41:49 > LGTV Companion Service started (v 3.1.5) ---------------------------
Sun 16:41:49 > Data path: C:\ProgramData\LGTV Companion\
Sun 16:41:49 > Device1, LG B2 65, with IP 10.0.0.29 initiated (Enabled:yes, NewConn:yes, WOL:3, SubnetMask:255.255.255.0, PairingKey:00f6b023c93f4b6aed536c8e89c1b709, MAC: AC:5A:F0:BD:14:B3 AC:B6:87:45:56:C6 , VerifyHdmiInput:1, SetHdmiInput:4, BlankOnIdle:on(2m))
Sun 16:41:49 > Host IP detected: 10.0.0.116
Sun 16:41:49 > Shutdown timing: default
Sun 16:41:49 > Device1, spawning Thread_SendRequest().
Sun 16:41:49 > ** System requests displays ON.
Sun 16:41:49 > Device1, spawning Thread_DisplayOn().
Sun 16:41:49 > Device1, repeating WOL broadcast started to MAC: AC5AF0BD14B3 using broadcast address: 10.0.0.255
Sun 16:41:50 > Device1, [DEBUG] (SSL) REQ response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:41:50 > Device1, [DEBUG] (SSL) ON response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:41:50 > Device1, [DEBUG] (SSL) REQ response 2: {"type":"response","id":1,"payload":{"returnValue":true,"id":"com.webos.app.hdmi4","sessionId":"Y29tLndlYm9zLmFwcC5oZG1pNA=="}}
Sun 16:41:50 > Device1, set hdmi-input [4]
Sun 16:41:50 > Device1, [DEBUG] (SSL) ON response 2: {"type":"error","id":2,"error":"500 Application error","payload":{"returnValue":false,"state":"Active","errorCode":"-102","errorText":"The current sub state must be 'screen off'"}}
Sun 16:41:50 > Device1, [DEBUG] (SSL) ON response 3: {"type":"response","id":3,"payload":{"state":"Active","returnValue":true}}
Sun 16:41:50 > Device1, power state is: ON
Sun 16:41:50 > -daemon 1 started
Sun 16:41:50 > [IPC Daemon 1] Started.
Sun 16:41:50 > Device1, repeating WOL broadcast ended
Sun 16:42:03 > The service terminated.

Sun 16:42:03 > LGTV Companion Service started (v 3.1.5) ---------------------------
Sun 16:42:03 > Data path: C:\ProgramData\LGTV Companion\
Sun 16:42:03 > Device1, LG B2 65, with IP 10.0.0.29 initiated (Enabled:yes, NewConn:yes, WOL:3, SubnetMask:255.255.255.0, PairingKey:00f6b023c93f4b6aed536c8e89c1b709, MAC: AC:5A:F0:BD:14:B3 AC:B6:87:45:56:C6 , VerifyHdmiInput:1, SetHdmiInput:4, BlankOnIdle:on(1m))
Sun 16:42:03 > Host IP detected: 10.0.0.116
Sun 16:42:03 > Shutdown timing: default
Sun 16:42:03 > Device1, spawning Thread_SendRequest().
Sun 16:42:03 > ** System requests displays ON.
Sun 16:42:03 > Device1, spawning Thread_DisplayOn().
Sun 16:42:03 > Device1, repeating WOL broadcast started to MAC: AC5AF0BD14B3 using broadcast address: 10.0.0.255
Sun 16:42:03 > Device1, [DEBUG] (SSL) ON response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:42:03 > Device1, [DEBUG] (SSL) ON response 2: {"type":"error","id":2,"error":"500 Application error","payload":{"returnValue":false,"state":"Active","errorCode":"-102","errorText":"The current sub state must be 'screen off'"}}
Sun 16:42:03 > Device1, [DEBUG] (SSL) ON response 3: {"type":"response","id":3,"payload":{"state":"Active","returnValue":true}}
Sun 16:42:03 > Device1, power state is: ON
Sun 16:42:03 > Device1, [DEBUG] (SSL) REQ response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:42:03 > Device1, [DEBUG] (SSL) REQ response 2: {"type":"response","id":1,"payload":{"returnValue":true,"id":"com.webos.app.hdmi4","sessionId":"Y29tLndlYm9zLmFwcC5oZG1pNA=="}}
Sun 16:42:03 > Device1, set hdmi-input [4]
Sun 16:42:03 > -daemon 1 started
Sun 16:42:03 > [IPC Daemon 1] Started.
Sun 16:42:04 > Device1, repeating WOL broadcast ended
Sun 16:43:05 > -daemon 1 useridle
Sun 16:43:05 > [IPC Daemon 1] User is idle.
Sun 16:43:05 > Device1, spawning Thread_DisplayOff().
Sun 16:43:05 > Device1, [DEBUG] (SSL) OFF response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:43:05 > Device1, [DEBUG] (SSL) OFF response 2: {"type":"response","id":5,"payload":{"state":"Active","returnValue":true}}
Sun 16:43:05 > Device1, [DEBUG] (SSL) OFF response 3: {"type":"response","id":6,"payload":{"returnValue":true,"appId":"com.webos.app.hdmi4","processId":"","windowId":""}}
Sun 16:43:05 > Device1, HDMI1 input inactive.
Sun 16:43:05 > Device1, power state is: Unchanged.
Sun 16:43:48 > -daemon 1 userbusy
Sun 16:43:48 > [IPC Daemon 1] User is not idle.
Sun 16:43:48 > Device1, spawning Thread_DisplayOn().
Sun 16:43:48 > Device1, repeating WOL broadcast started to MAC: AC5AF0BD14B3 using broadcast address: 10.0.0.255
Sun 16:43:48 > Device1, [DEBUG] (SSL) ON response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:43:48 > Device1, [DEBUG] (SSL) ON response 2: {"type":"error","id":7,"error":"500 Application error","payload":{"returnValue":false,"state":"Active","errorCode":"-102","errorText":"The current sub state must be 'screen off'"}}
Sun 16:43:48 > Device1, [DEBUG] (SSL) ON response 3: {"type":"response","id":8,"payload":{"state":"Active","returnValue":true}}
Sun 16:43:48 > Device1, power state is: ON
Sun 16:43:49 > Device1, repeating WOL broadcast ended
Sun 16:44:48 > -daemon 1 useridle
Sun 16:44:48 > [IPC Daemon 1] User is idle.
Sun 16:44:48 > Device1, spawning Thread_DisplayOff().
Sun 16:44:48 > Device1, [DEBUG] (SSL) OFF response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:44:48 > Device1, [DEBUG] (SSL) OFF response 2: {"type":"response","id":10,"payload":{"state":"Active","returnValue":true}}
Sun 16:44:48 > Device1, [DEBUG] (SSL) OFF response 3: {"type":"response","id":11,"payload":{"returnValue":true,"appId":"com.webos.app.hdmi4","processId":"","windowId":""}}
Sun 16:44:48 > Device1, HDMI1 input inactive.
Sun 16:44:48 > Device1, power state is: Unchanged.
Sun 16:45:48 > -daemon 1 useridle
Sun 16:45:48 > Device1, spawning Thread_DisplayOff().
Sun 16:45:48 > Device1, [DEBUG] (SSL) OFF response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:45:48 > Device1, [DEBUG] (SSL) OFF response 2: {"type":"response","id":12,"payload":{"state":"Active","returnValue":true}}
Sun 16:45:48 > Device1, [DEBUG] (SSL) OFF response 3: {"type":"response","id":13,"payload":{"returnValue":true,"appId":"com.webos.app.hdmi4","processId":"","windowId":""}}
Sun 16:45:48 > Device1, HDMI1 input inactive.
Sun 16:45:48 > Device1, power state is: Unchanged.
Sun 16:46:48 > -daemon 1 useridle
Sun 16:46:48 > Device1, spawning Thread_DisplayOff().
Sun 16:46:48 > Device1, [DEBUG] (SSL) OFF response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:46:48 > Device1, [DEBUG] (SSL) OFF response 2: {"type":"response","id":14,"payload":{"state":"Active","returnValue":true}}
Sun 16:46:48 > Device1, [DEBUG] (SSL) OFF response 3: {"type":"response","id":15,"payload":{"returnValue":true,"appId":"com.webos.app.hdmi4","processId":"","windowId":""}}
Sun 16:46:48 > Device1, HDMI1 input inactive.
Sun 16:46:48 > Device1, power state is: Unchanged.
Sun 16:46:53 > -daemon 1 userbusy
Sun 16:46:53 > [IPC Daemon 1] User is not idle.
Sun 16:46:53 > Device1, spawning Thread_DisplayOn().
Sun 16:46:53 > Device1, repeating WOL broadcast started to MAC: AC5AF0BD14B3 using broadcast address: 10.0.0.255
Sun 16:46:53 > Device1, [DEBUG] (SSL) ON response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:46:53 > Device1, [DEBUG] (SSL) ON response 2: {"type":"error","id":16,"error":"500 Application error","payload":{"returnValue":false,"state":"Active","errorCode":"-102","errorText":"The current sub state must be 'screen off'"}}
Sun 16:46:53 > Device1, [DEBUG] (SSL) ON response 3: {"type":"response","id":17,"payload":{"state":"Active","returnValue":true}}
Sun 16:46:53 > Device1, power state is: ON
Sun 16:46:54 > Device1, repeating WOL broadcast ended
Sun 16:50:59 > -daemon 1 useridle
Sun 16:50:59 > [IPC Daemon 1] User is idle.
Sun 16:50:59 > Device1, spawning Thread_DisplayOff().
Sun 16:50:59 > Device1, [DEBUG] (SSL) OFF response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:50:59 > Device1, [DEBUG] (SSL) OFF response 2: {"type":"response","id":19,"payload":{"state":"Active","returnValue":true}}
Sun 16:50:59 > Device1, [DEBUG] (SSL) OFF response 3: {"type":"response","id":20,"payload":{"returnValue":true,"appId":"com.webos.app.hdmi4","processId":"","windowId":""}}
Sun 16:50:59 > Device1, HDMI1 input inactive.
Sun 16:50:59 > Device1, power state is: Unchanged.
Sun 16:51:15 > -daemon 1 userbusy
Sun 16:51:15 > [IPC Daemon 1] User is not idle.
Sun 16:51:15 > Device1, spawning Thread_DisplayOn().
Sun 16:51:15 > Device1, repeating WOL broadcast started to MAC: AC5AF0BD14B3 using broadcast address: 10.0.0.255
Sun 16:51:16 > Device1, [DEBUG] (SSL) ON response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:51:16 > Device1, [DEBUG] (SSL) ON response 2: {"type":"error","id":21,"error":"500 Application error","payload":{"returnValue":false,"state":"Active","errorCode":"-102","errorText":"The current sub state must be 'screen off'"}}
Sun 16:51:16 > Device1, [DEBUG] (SSL) ON response 3: {"type":"response","id":22,"payload":{"state":"Active","returnValue":true}}
Sun 16:51:16 > Device1, power state is: ON
Sun 16:51:17 > Device1, repeating WOL broadcast ended
Sun 16:52:23 > -daemon 1 useridle
Sun 16:52:23 > [IPC Daemon 1] User is idle.
Sun 16:52:23 > Device1, spawning Thread_DisplayOff().
Sun 16:52:23 > Device1, [DEBUG] (SSL) OFF response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:52:23 > Device1, [DEBUG] (SSL) OFF response 2: {"type":"response","id":24,"payload":{"state":"Active","returnValue":true}}
Sun 16:52:23 > Device1, [DEBUG] (SSL) OFF response 3: {"type":"response","id":25,"payload":{"returnValue":true,"appId":"com.webos.app.hdmi4","processId":"","windowId":""}}
Sun 16:52:23 > Device1, HDMI1 input inactive.
Sun 16:52:23 > Device1, power state is: Unchanged.
Sun 16:53:23 > -daemon 1 useridle
Sun 16:53:23 > Device1, spawning Thread_DisplayOff().
Sun 16:53:23 > Device1, [DEBUG] (SSL) OFF response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:53:23 > Device1, [DEBUG] (SSL) OFF response 2: {"type":"response","id":26,"payload":{"state":"Active","returnValue":true}}
Sun 16:53:23 > Device1, [DEBUG] (SSL) OFF response 3: {"type":"response","id":27,"payload":{"returnValue":true,"appId":"com.webos.app.hdmi4","processId":"","windowId":""}}
Sun 16:53:23 > Device1, HDMI1 input inactive.
Sun 16:53:23 > Device1, power state is: Unchanged.
Sun 16:53:38 > -daemon 1 userbusy
Sun 16:53:38 > [IPC Daemon 1] User is not idle.
Sun 16:53:38 > Device1, spawning Thread_DisplayOn().
Sun 16:53:38 > Device1, repeating WOL broadcast started to MAC: AC5AF0BD14B3 using broadcast address: 10.0.0.255
Sun 16:53:39 > Device1, [DEBUG] (SSL) ON response 1: {"type":"registered","id":"register_0","payload":{"client-key":"00f6b023c93f4b6aed536c8e89c1b709"}}
Sun 16:53:39 > Device1, [DEBUG] (SSL) ON response 2: {"type":"error","id":28,"error":"500 Application error","payload":{"returnValue":false,"state":"Active","errorCode":"-102","errorText":"The current sub state must be 'screen off'"}}
Sun 16:53:39 > Device1, [DEBUG] (SSL) ON response 3: {"type":"response","id":29,"payload":{"state":"Active","returnValue":true}}
Sun 16:53:39 > Device1, power state is: ON
Sun 16:53:39 > Device1, repeating WOL broadcast ended

**Comment by Chaython** [comment]
If I removed the miscellaneous settings it worked again.
