### ISSUE TITLE
Occasional fail to start TV + wrong program directory?

### ISSUE THREAD

**Issue by therealfreezoid** [JPersson77/LGTVCompanion#165]
Hi. I love this software, and it works great, but occasionally it fails to launch my LG C1. The TV was shut down by the software 10 hours earlier. What I noticed in the log is that it points to a non-existent directory: "D:\a\LGTV...". I don't even have a D: partition. I uninstalled the software and installed it again, but it didn't fix the issue. I also searched windows registry to find anything related to that directory, but with no success. 
Most of the time everything works. This issue occurs mostly after hardware was off for hours. 
I followed the guide here on github to set it all up. I hope this is the right place to post this.

> Wed 04:08:36 > Event subscription callback: system shut down detected.
> Wed 04:08:37 > ** System requests displays OFF.
> Wed 04:08:37 > Device1, spawning Thread_DisplayOff().
> Wed 04:08:37 > Device1, [DEBUG] (SSL) OFF response 1: {"type":"registered","id":"register_0","payload":{"client-key":"ac1870e07d824567074c732b0f270387"}}
> Wed 04:08:37 > Device1, [DEBUG] (SSL) OFF response 2: {"type":"response","id":13,"payload":{"returnValue":true,"state":"Active"}}
> Wed 04:08:37 > Device1, [DEBUG] (SSL) OFF response 4: {"type":"response","id":14,"payload":{"returnValue":true}}
> Wed 04:08:37 > Device1, power state is: OFF.
> Wed 04:08:37 > Event subscription callback: system shut down detected.
> Wed 04:08:38 > ** System is shutting down (low power mode).

> Wed 14:09:00 > ** System resumed from low power state.
> Wed 14:09:00 > ** System requests displays ON.
> Wed 14:09:00 > Device1, spawning Thread_DisplayOn().
> Wed 14:09:00 > Device1, repeating WOL broadcast started to MAC: ************ using IP address: 192.168.1.149
> Wed 14:09:00 > Device1, Best route to IP - interface index 7 LUID 1689399750295552 route protocol 2
> Wed 14:09:05 > ** System resumed from low power state (Automatic).
> Wed 14:09:21 > Device1, WARNING! Thread_DisplayOn(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:632:5 in function 'connect']
> Wed 14:09:29 > -daemon 2 started
> Wed 14:09:29 > [IPC Daemon 2] Started.
> Wed 14:09:41 > Device1, repeating WOL broadcast ended
> Wed 14:09:42 > Device1, WARNING! Thread_DisplayOn(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:632:5 in function 'connect']

**Comment by dechamps** [comment]
> What I noticed in the log is that it points to a non-existent directory: "D:\a\LGTV...". I don't even have a D: partition

This is perfectly normal - the log is referring to the source code located on the machine where LGTVCompanion was originally built (in this case, almost certainly a GitHub Actions worker machine). It is not referring to a file on your computer.

> This issue occurs mostly after hardware was off for hours.

Keep in mind the [following limitation documented on the README](https://github.com/JPersson77/LGTVCompanion#troubleshooting) which might apply to your case, especially if the TV is connected via WiFi:

> If the connection between the TV and the Router and/or access point is lost for any reason (e.g. router reboot, power outage, firmware update, etc.) while the TV is off, the TV might not automatically reconnect and therefore won't react to attempts to turn it on via Wi-Fi or Ethernet. You may therefore need to turn the TV on manually at least once so that it can reconnect to your network.

**Comment by therealfreezoid** [comment]
Thanks for clarifying the log.
I do have it connected through the WiFi so that might indeed be it. I guess I will have to sort out a wired connection. Shame the WiFi connection is not fully reliable.

**Comment by JPersson77** [comment]
Issue closed
