### ISSUE TITLE
TV off stopped working, turn TV on still works

### ISSUE THREAD

**Issue by Kenshokram** [JPersson77/LGTVCompanion#166]
Installed and I'm still using 3.1.5, windows 11 64bits.

I didn't do any chance that I know of to either tv settings nor settings in the application, but the tv automatic turning off when Sleep or Shutdown is selected has stopped working. It still turns on when I turn the PC on.

I have tried changing the setting from default to early, but it didn't make a difference, any idea what I could do?

Thanks for the app!!

**Comment by JonasFi** [comment]
Same here...
Just out of nowhere the app does not seem to work anymore

**Comment by JPersson77** [comment]
Hiya, your issues are indicative of a network change which has made the configuration invalid, specifically the PC does not seem to be able to communicate with the TV properly. The first thing I would  like to verify is that the IP adress of the TV is correctly configured (it may have changed unless a static lease is configured in the router)

**Comment by FabledNinja** [comment]
Mine is set to static, and my TV won't turn off. If I use the "Test" option, it turns off and on just fine. But if I set the Automatic user idle mode management, the TV shows a blank screen saver, but it does not actually turn off. And yes, my windows screen saver is disabled.

**Comment by FabledNinja** [comment]
> Mine is set to static, and my TV won't turn off. If I use the "Test" option, it turns off and on just fine. But if I set the Automatic user idle mode management, the TV shows a blank screen saver, but it does not actually turn off. And yes, my windows screen saver is disabled.

I solved the issue by dong this; control panel -> hardware and sound -> power options -> change powerplan plan setting -> setting the same time for the "Turn off the display" than I have set in the LGTV companion "Automatic user idle mode management."

**Comment by JPersson77** [comment]
Hi @FabledNinja great you figured it out how to workaround

Your issue is however related to user idle mode not triggering so it's a different issue than "the TV not turning off when PC goes to sleep". You can execute c:/program files/lgtvdaemon.exe -show to get a status window with more information about why user idle mode does not trigger

**Comment by JPersson77** [comment]
Hi @JonasFi and @Kenshokram any feedback wrt the suggestion above?

**Comment by JonasFi** [comment]
> Hi @JonasFi and @Kenshokram any feedback wrt the suggestion above?

Well I reinstalled the application, set my TV IP adress to be static and that seemed to fix my problem. :)

**Comment by Kenshokram** [comment]
Sorry I'm in the middle of moving and this went out of my mind, it worked for me just with updating the TV IP, since some ISP changes on my side must've changed them around, and I didn't realize only part of the features failing could still be due to this, thank you!!

**Comment by JPersson77** [comment]
Issue closed
