### ISSUE TITLE
Cannot upgrade to LGTV Companion x64 v3.1.9: "The error code is 2503"

### ISSUE THREAD

**Issue by Cr4z33** [JPersson77/LGTVCompanion#168]
While the upgrade went flawlessly in my Windows 11 Pro partition the same didn't happen in my other Windows 10 Pro partition...

During the installation this error window came up and I couldn't end the setup.

![Cattura](https://github.com/JPersson77/LGTVCompanion/assets/19343851/56f1c635-5482-4c91-af39-753d11f86a89)

**Comment by JPersson77** [comment]
Hi @Cr4z33 google shows me this is likely an issue with writing to the temp directory while installing. Why, I've no idea.

I came across this fix that you may want ro look into:

1 Navigate to the Windows Temp folder located at c:\windows\temp.

2 Make sure you uncheck the read only button.

3 Switch to the Security Tab and choose Administrators and make sure it is highlighted. Make sure that there is a check box next to Full Control for the Administrators and Users group

Let me know if this helps

**Comment by Cr4z33** [comment]
Thank you @JPersson77 for the suggestion, but unfortunately the error window keeps popping up.

As this is not a LGTV Companion issue I will keep investigating further by Google searching.
