### ISSUE TITLE
No resume power on after switching to Windows 11

### ISSUE THREAD

**Issue by Amoeba00** [JPersson77/LGTVCompanion#17]
LG C1
Worked perfectly in Windows 10.
Just did a clean install of Windows 11 and now it appears after the machine sleeps - I have to use the remote to power the TV back on.

I don't know if it's a setting in Windows or what I'm missing.  Any suggestions?

**Comment by JPersson77** [comment]
Hi amoeba00, did you install LGTV companion from scratch as well or did you copy over the old configuration. Can you please enable logging in the global settings, make the PC sleep/resume and then upload the log to pastebin or similar and I can have a look.

**Comment by Amoeba00** [comment]
Clean install on new boot drive. I'll do as you ask and report back.  Thanks.

**Comment by Amoeba00** [comment]
I think I see what's happening here.  It will resume after sleep mode, but after an extended period (I don't know how long) - the TV will not respond and the remote is required.  I'm guessing it's the Advanced power option setting that I have enabled?  What's the guidance for that?

Win 11 Power:  Screen set to off at 3min and Sleep mode begins at 5

Here are my app settings:
![image](https://user-images.githubusercontent.com/39176113/151377235-de7ad221-fcf1-4096-8de0-cca4f80228f0.png)

![image](https://user-images.githubusercontent.com/39176113/151377290-f23770af-0d16-4142-95fa-be690880c475.png)

Here is a copy of the log file after an extended period where the TV would not cycle back on - I unlocked my system without the screen - and still had to power on with the remote.

```
Thu 09:15:24 > ** System requests displays ON.
Thu 09:15:24 > Device1, spawning DisplayPowerOnThread().
Thu 09:15:24 > Device1, repeating WOL broadcast started to MAC: <redacted> using IP address: 192.168.<redacted>
Thu 09:15:24 > Device1, WARNING! DisplayPowerOnThread(): connect: A socket operation was attempted to an unreachable host
Thu 09:15:28 > ** System resumed from low power state.
Thu 09:15:28 > ** System resumed from low power state (Automatic).
Thu 09:15:51 > Device1, WARNING! DisplayPowerOnThread(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Thu 09:16:05 > Device1, repeating WOL broadcast ended
Thu 09:16:12 > Device1, WARNING! DisplayPowerOnThread(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

**Comment by Amoeba00** [comment]
So this time I disabled the Advanced Power Option and here's the log from that (still had to manually power on with remote)

```
Thu 09:29:29 > IPC, Daemon has started.
Thu 09:45:08 > ** System requests displays OFF.
Thu 09:45:08 > Device1, spawning DisplayPowerOffThread().
Thu 09:45:08 > Host IP detected: 192.168.<redacted>
Thu 09:45:08 > Device1, HDMI1 input active.
Thu 09:45:08 > Device1, established contact: Device is OFF.
Thu 09:47:17 > ** System is suspending to a low power state.
Thu 09:54:47 > ** System resumed from low power state.
Thu 09:54:47 > ** System requests displays ON.
Thu 09:54:47 > Device1, spawning DisplayPowerOnThread().
Thu 09:54:47 > Device1, repeating WOL broadcast started to MAC: <redacted> using IP address: 192.168.<redacted>
Thu 09:54:47 > Device1, WARNING! DisplayPowerOnThread(): connect: A socket operation was attempted to an unreachable host
Thu 09:54:51 > ** System resumed from low power state (Automatic).
Thu 09:55:01 > Device1, established contact: Display is ON.  
Thu 09:55:01 > Device1, repeating WOL broadcast ended

```

**Comment by JPersson77** [comment]
Hi without going into the logs, did you try to use option 3 in the network options? Highly suspect that is the issue. Click the "what's this?" link to get some help on determining your subnet mask. Let me know how that goes please.

**Comment by Amoeba00** [comment]
Well - that was it.  Option 3 - definitely made a difference.  Works now. Thanks!

**Comment by JPersson77** [comment]
Lovely! Thanks for your feedback!
