### ISSUE TITLE
Turning on the computer before the TV...

### ISSUE THREAD

**Issue by Chaython** [JPersson77/LGTVCompanion#170]
Turning on the computer before the TV... the TV is started by LG companion, but the TV is loading at 800x600 60hz
This is on a Nvidia RTX 3080 / LG B2.

**Comment by JPersson77** [comment]
For some this happens but it's not related to the app. If you have a newer tv (c2+) then you can try to enable "always ready".

**Comment by JPersson77** [comment]
Hi @Chaython  any feedback wrt the above?

**Comment by JPersson77** [comment]
Closing due to lack of feedback. Feel free to reopen as necessary
