### ISSUE TITLE
Is there a way to keep the monitor from turning off when restarting? 

### ISSUE THREAD

**Issue by netjack7** [JPersson77/LGTVCompanion#173]
Wasn't able to find this in the config options.

**Comment by JPersson77** [comment]
![image](https://github.com/JPersson77/LGTVCompanion/assets/77928210/43bfad0d-4648-4c63-be76-09d9a8a482fd)

Ensure to check all words that refer to the system restarting. if your OS is localised in a language other than english you will have more options here

**Comment by JPersson77** [comment]
hi @netjack7 did the above help?

**Comment by JPersson77** [comment]
Closing due to lack of feedback
