### ISSUE TITLE
"No signal" on shutdown after recent update.

### ISSUE THREAD

**Issue by soma811** [JPersson77/LGTVCompanion#174]
I couldn't find any other information that works. 
After updating to 3.1.9 from 3.1.5 shutting down my PC no longer turns off the TV, the TV remains on displaying "no signal".
I have verified the network information is correct and that the TV has a static IP.

Here is the log after shutting down and booting the PC.
https://zerobin.net/?9316758317b4f7d3#xTaGtkzrQA/1+TNFhEFNvRy8ZlA0wiJ0kX1yF7QcKSo=
Config: 
https://zerobin.net/?eb9262ed51eccf37#txgnjCBhfKU480/FTRCjTPZDMlLefQC9LKvreHlP/0c=

Hopefully I didn't miss something and this isn't a duplicate, please let me know if you'd like any more information.
Thanks :)

**Comment by JPersson77** [comment]
Hi @soma811 there is no change per se between 3.1.5 and 3.1.9 that should cause the issue. 

However, shutting down the TV on system shutdown is a race to communicate with the TV before it's impossible to do so. Changing the method to "early" from "auto" in the shutdown section in general options may hopefully resolve your issue. If this does not help please paste a log here and I will have a look.

**Comment by soma811** [comment]
Hello, I tried setting timing to early to no avail. TV still displays "no signal" on shutdown.

Log:
https://zerobin.net/?c90527465e26853a#MHHr8nohZgXigyTY8FVZEv0dDukE4/fxF69TAdISze0=
Config:
https://zerobin.net/?0f170da9ad1b41ff#j1Gd5PzRq8PB4DetOsEWSxNp/4YSfomNk3Tve8jHVTg=

Thanks! :)

**Comment by JPersson77** [comment]
Hi thanks, I noticed nothing out of the ordinarie in the log but see this in the config:

"LocalEventLogRestartString": [
            "restart",
            "shutdown",
            "power off"
        ],

It seems you may have checked a few checkboxes too many in the "shutdown" configuration. Try unchecking "shutdown" and "power off". Hope that helps

**Comment by soma811** [comment]
Awesome, this worked, thank you so much! Didn't realize that checking all of them could cause it not to work.
