### ISSUE TITLE
webOS 5: TV refuses packet

### ISSUE THREAD

**Issue by davidmatthewcoleman** [JPersson77/LGTVCompanion#175]
My 65UH5500 actively refuses the packet sent by this app.

Tue 12:08:55 > LGTV Companion Service started (v 3.1.9) ---------------------------
Tue 12:08:55 > Data path: C:\ProgramData\LGTV Companion\
Tue 12:08:55 > Device1, 65UH5500, with IP 192.168.1.196 initiated (Enabled:yes, NewConn:yes, WOL:2, SubnetMask:255.255.255.0, PairingKey:n/a, MAC: D4:63:FE:D9:9F:C1 , VerifyHdmiInput:3, SetHdmiInput:3, BlankOnIdle:on(10m))
Tue 12:08:55 > Host IP detected: 192.168.1.192/24
Tue 12:08:55 > Shutdown timing: default
Tue 12:08:55 > Device1, omitted Thread_SendRequest(). No pairing key.
Tue 12:08:55 > ** System requests displays ON.
Tue 12:08:55 > Device1, spawning Thread_DisplayOn().
Tue 12:08:55 > Device1, repeating WOL broadcast started to MAC: D463FED99FC1 using IP address: 192.168.1.196
Tue 12:08:55 > Device1, Best route to IP - interface index 15 LUID 19985273152602112 route protocol 2
Tue 12:08:55 > -daemon 1 started
Tue 12:08:55 > [IPC Daemon 1] Started.
Tue 12:08:57 > Device1, WARNING! Thread_DisplayOn(): connect: No connection could be made because the target machine actively refused it [system:10061 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:632:5 in function 'connect']
Tue 12:08:58 > -poweroff Device1
Tue 12:08:58 > [IPC] Force power OFF: Device1 
Tue 12:08:58 > Device1, omitted Thread_DisplayOff(). No pairing key.
Tue 12:09:00 > -poweron Device1
Tue 12:09:00 > [IPC] Force power ON: Device1 
Tue 12:09:00 > Device1, omitted Thread_DisplayOn().
Tue 12:09:00 > Device1, WARNING! Thread_DisplayOn(): connect: No connection could be made because the target machine actively refused it [system:10061 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:632:5 in function 'connect']
Tue 12:09:02 > Device1, WARNING! Thread_DisplayOn(): connect: No connection could be made because the target machine actively refused it [system:10061 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:632:5 in function 'connect']
Tue 12:09:03 > -daemon 1 topology state Device1 
Tue 12:09:03 > [IPC Daemon 1] Windows monitor topology was changed. Device1:ON 
Tue 12:09:03 > Device1, omitted Thread_DisplayOn().
Tue 12:09:04 > Device1, WARNING! Thread_DisplayOn(): connect: No connection could be made because the target machine actively refused it [system:10061 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:632:5 in function 'connect']
Tue 12:09:07 > Device1, WARNING! Thread_DisplayOn(): connect: No connection could be made because the target machine actively refused it [system:10061 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:632:5 in function 'connect']
Tue 12:09:09 > Device1, WARNING! Thread_DisplayOn(): connect: No connection could be made because the target machine actively refused it [system:10061 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:632:5 in function 'connect']
Tue 12:09:12 > Device1, WARNING! Thread_DisplayOn(): connect: No connection could be made because the target machine actively refused it [system:10061 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:632:5 in function 'connect']
Tue 12:09:14 > Device1, WARNING! Thread_DisplayOn(): connect: No connection could be made because the target machine actively refused it [system:10061 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:632:5 in function 'connect']
Tue 12:09:17 > Device1, WARNING! Thread_DisplayOn(): connect: No connection could be made because the target machine actively refused it [system:10061 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:632:5 in function 'connect']

**Comment by JPersson77** [comment]
Hi @davidmatthewcoleman sorry it could be a number of things. I don't know the TV specifically. Are there any settings in the TV configuration to allow for external communication? Are you sure the TV allows for external connections? Maybe try the legacy connection methods (non-ssl)

**Comment by JPersson77** [comment]
Hi @davidmatthewcoleman any feedback wrt the above?

**Comment by JPersson77** [comment]
Closed due to lack of feedback. Feel free to reopen as necessary
