### ISSUE TITLE
[Bug?] Error 1068: the dependency service or group failed to start

### ISSUE THREAD

**Issue by sebdotffs** [JPersson77/LGTVCompanion#178]
Hello!

I keep running into an issue with the Companion. Everything worked fine for months on my Windows 11 PC until I started fidgeting with NordVPN a few days ago.

The LGTV Companion service cannot start anymore under any circumstance - even after completely uninstalling NordVPN and reinstalling the LGTV Companion app (with restarts in between each action).

I even uninstalled and reinstalled my Ethernet driver, using Device Manager, in case that had anything to do with it. 

Also, before this, the app kept spamming me once in a while with the "Invalidated Monitor Topology Configuration!" error, but for about 2-3 weeks everything worked despite the notification.

![Screenshot 2023-11-02 000220](https://github.com/JPersson77/LGTVCompanion/assets/102325203/18033c8b-29b2-4298-94a3-dfa32ff3353c)

Let me know if you have any suggestions.

**Comment by sebdotffs** [comment]
Found the culprit: NordVPN messed with the network adapters so bad that even uninstalling it did not fix the issue as Network Sharing/Discovery couldn't be turned on.

I modified a registry key after finding the solution on google, Start from HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache from 4 to 1.

This solved it.

**Comment by JPersson77** [comment]
Thanks for the information! I still have it on the todo to offer a choice of what network adapter to use :)
