### ISSUE TITLE
LG C2 not turning off when pc shuts down

### ISSUE THREAD

**Issue by adachoinw** [JPersson77/LGTVCompanion#181]
When I shutdown my pc, the tv stays on.
It works fine when I turn on my pc, the tv turns on automatically.
Both the tv and pc are on the same subnet. And the tv has a static IP.

When I test it using the test button under 'configure', 'turn off' works, and 'turn on' doesn't.
Also pressing enter after clicking 'test' doesn't turn the tv back on.

Things I've tried:
- reinstalling the app and deleting the config.json.
- changed shutdown timing to early
- changed firmware connection to legacy
- tried both static and dynamic IP for tv
[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/13448385/Log.txt)
![2023-11-23 04_55_17-](https://github.com/JPersson77/LGTVCompanion/assets/60563114/72a2cfff-d2e3-4c0a-ac4f-a2d242971e5a)

**Comment by JPersson77** [comment]
Hi, uncheck "shutdown" and "power off" in top left corner. With the current settings a shutdown is treated as a restart, which means the TV will remain powered on. Please click the "whats this?" link to learn more

**Comment by Minecraftman04** [comment]
I have the same issue, haven't touched the software and it suddenly doesn't work, i think lg has done an update to their tv again!

**Comment by JPersson77** [comment]
Hi @Minecraftman04 the issue above is however a configuration issue. Maybe start a new issue if it's not related. Please enable logging and paste the log and I will have a look

**Comment by adachoinw** [comment]
> Hi, uncheck "shutdown" and "power off" in top left corner. With the current settings a shutdown is treated as a restart, which means the TV will remain powered on. Please click the "whats this?" link to learn more

This fixed the issue! Didn't think it was just a settings configuration. Thanks alot!

**Comment by JPersson77** [comment]
resolved
