### ISSUE TITLE
Toggling "Keep topology configuration" not being detected as changed option / Service Failing to Restart after Applying Settings

### ISSUE THREAD

**Issue by snada88** [JPersson77/LGTVCompanion#182]
I had "Support windows multi-monitor topology" enabled on 3.1.9 before updating to 3.2.5.  Toggling on the new "Keep topology configuration also at logon screen after system boot" option did not enable the "OK" button to allow me to save settings.  To attempt to force the button to enable, I unchecked "Support windows multi-monitor topology" and then re-checked both options.  This enables the "OK" button but the application hangs when I then click "Apply" on the main window.

**Comment by snada88** [comment]
It seems the service is stuck at Starting whenever I apply any options on 3.2.5, including the option to enable logging.  Should I make a new issue?

**Comment by JPersson77** [comment]
It's fine! Can you try to reboot your PC meanwhile and I'll review the code change from 3.1.9

**Comment by JPersson77** [comment]
I uploaded v 3.2.9 with a bugfix. for the service crash. Closing this issue since you have resolved it already but feel free to reopen as needed
