### ISSUE TITLE
[Feature Request] Same app but for Samsung TV / Monitors possible?

### ISSUE THREAD

**Issue by D1Vad22** [JPersson77/LGTVCompanion#186]
Hi JPersson77,

Sorry if this isnt the place, but could you amazing work be tweaked to do Samsung TV / Monitors?

I used an LG 42" C2 TV briefly as my PC monitor and your companion app was a life saver.

Reason I ask, i am using the Samsung 34" G8 oled monitor and it has this ridiculous standby bug that crashes the gpu. So basically cant use monitor standby and in 11mths samsung still hasnt solved this.

I know the G8 can be turned on/off via wifi as I just tested using the the popup on my samsung phone. This then got me thinking about your LG companion app.

**Comment by JPersson77** [comment]
Hi there, it looks like there is an Api for TizenOS  which can do similar stuff but I don't have a samsung TV so it's a bit hard to test it. I tried contacting Samsung to see if they would like to lend me me a TV but no :)

Someone might want to contribute with this?

**Comment by D1Vad22** [comment]
Thanks JPersson,

I am happy to have a crack myself, granted i dont think i have the programming skills for this. Unless its just a matter of tweaking some network outputs...

**Comment by JPersson77** [comment]
Yeah give it a go! I have not checked much but I think to wake a samsung you should still use WOL, so that is the same. Then you basically want to rewrite/adapt the Csession and CsessionManager classes in session.cpp as they are reaponsible for all communications with the TVs

**Comment by D1Vad22** [comment]
Not required, samsung finally released update thar fix the Displayport wake/sleep issue on samsung g8 oled monitor
