### ISSUE TITLE
The LG BX tv does not automatically turn off when entering hibernation

### ISSUE THREAD

**Issue by akkuz** [JPersson77/LGTVCompanion#187]
I don't know if the problem is related to my model, but it would be nice if the TV turned off automatically when entering hibernation. With sleep and normal shutdown the companion app works correctly, but not in hibernation state. Anyway, congratulations on the masterful work you did with this app, it's fantastic.

**Comment by JPersson77** [comment]
Hi @akkuz Can you please enable logging and paste a snippet on pastebin or imilar and copy the linkl here and I will have a look.

**Comment by akkuz** [comment]
> Hi @akkuz Can you please enable logging and paste a snippet on pastebin or imilar and copy the linkl here and I will have a look.

Here is the link to see my log file, I tried to activate the hibernation state a couple of times to see if it worked: 

https://pastebin.com/TtUbBy2V

**Comment by JPersson77** [comment]
Is it possible for you to join the discord channel and try a dev build? I can see some evidence in the log that the system does not properly process power off commands. Maybe it's due to a lack of time before windows shut down. Want to try another method for keeping windows alive long enough to send out the proper commands

**Comment by akkuz** [comment]
> Is it possible for you to join the discord channel and try a dev build? I can see some evidence in the log that the system does not properly process power off commands. Maybe it's due to a lack of time before windows shut down. Want to try another method for keeping windows alive long enough to send out the proper commands
> 
> Discord link: https://discord.gg/7KkTPrP3fq

To install the dev version, do I have to uninstall the regular version? If it doesn't work how do I make windows wait longer to shut down

**Comment by akkuz** [comment]
ok I tried to install the dev version after uninstalling the regular version. Now the tv shuts down when entering the hibernating state but it doesn't turn on when the pc wakes up. All other modes work (sleep mode and standard turn off). I don t know if it's the same problem as before.

I paste my new log file here, just in case: https://pastebin.com/pGiM6eDG

**Comment by JPersson77** [comment]
That is an old dev version you just installed. Ping me instead and I will sens you the one ID like for you to try. Interesting the  ehaviour  changed though

**Comment by JPersson77** [comment]
Following from inactivity I'm closing this issue. Feel free to reopen as needed
