### ISSUE TITLE
TV returning 500 Application error

### ISSUE THREAD

**Issue by AckermannM** [JPersson77/LGTVCompanion#189]
I ran into an issue with the latest LGTV Companion v3.3.3

My TV is an LG C3 OLED42C37LA with webOS 8.3.0-13 (number1-nameri).

The TV is answering the power on messages like this: 
```
Mon 15:38:37 > Device1, [DEBUG] (SSL) ON response 1: {"type":"registered","id":"register_0","payload":{"client-key":"b6316536005e8c9893b9ad41cd8bfd58"}}
Mon 15:38:37 > Device1, [DEBUG] (SSL) ON response 2: {"type":"error","id":9,"error":"500 Application error","payload":{"returnValue":false,"state":"Active Standby","errorCode":"-102","errorText":"The current sub state must be 'screen off'"}}
Mon 15:38:37 > Device1, [DEBUG] (SSL) ON response 3: {"type":"response","id":10,"payload":{"state":"Active Standby","returnValue":true}}
```

I have tried:
- both WiFi and LAN
- Enabling and disabling "Always Ready"
- Enabling and disabling SDDP
- Enabling and disabling IP control

Further settings: 
- WOL is on
- Wake from wifi is on

Whole log is attached. 
[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/13940306/Log.txt)

EDIT:

My actual problem that the app successfully turns my TV off, but won’t turn it on again.

**Comment by JPersson77** [comment]
Hi @AckermannM while I understand that this may seem like a problem, the error message is actually to be expected. The error message (from the TV) is a result of LGTV companion asking the tv to unblank. So you can saely ignore tht error message.

Not sure from your description if there is something wrong with the operations, so please feedback on that. Cheers

**Comment by AckermannM** [comment]
Ah I forgot to mention, the app successfully turns my TV off, but won’t turn it on again. Sorry

**Comment by JPersson77** [comment]
Sorry for a late reply. It is hard to tell conclusively from the log. When the TV is not awoken properly probably the issue is with the Wake-on-lan. For example - the  the PC may be sending the magic packet on the wrong network adapter (notice you have a few), or the LAN is configured to not allow WOL, or the TV is not properly configured (but you say it is).

Can you perform a test and see if another WOL tool can wake the TV? For example this one: https://wol.aquilatech.com/

**Comment by AckermannM** [comment]
I did a complete reset of the TV, and re-setup of the companion app again. Now it works again. Unfortunately I have no more info. Thanks for the suggestions anyways!
