### ISSUE TITLE
TV sometimes does not turn on (WiFi broadcast issue?)

### ISSUE THREAD

**Issue by dechamps** [JPersson77/LGTVCompanion#19]
I've noticed that, when using LGTVCompanion (any version, including latest `master`) with my LG G1 over WiFi, the TV would sometimes (not always!) fail to react when asked to turn on (automatically or manually from the LGTVCompanion UI).

This happens once every 2-3 days or so. I am not able to reproduce it on demand. It seems to only happen after the TV has been off for a long time (e.g. a few hours or more). I don't think this is related to "pixel cleaning" since it often happens after the TV has been off for 12+ hours, long after any pixel cleaning routine should have completed.

Every time this happens I try to gather more information by examining network traffic and doing a few Wake-On-LAN experiments. I'm still not 100% convinced I have the full picture but here's what I got so far:

**Usually the TV wakes up in response to a broadcast-directed (i.e. destination MAC `FF:FF:FF:FF:FF:FF`) WoL packet, but when the problem occurs it does not. However it _does_ wake up if I send it a _unicast_ WoL packet.** This can be confirmed independently using tools other than LGTVCompanion. For example I managed to demonstrate this using `etherwake` from a nearby Linux machine - if the broadcast flag (`-b`) is used the TV will not wake up, but if the flag is omitted it will. To be honest I find it a bit baffling that broadcasts sometimes work and sometimes don't. It's also not clear to me if the TV is truly ignoring WoL packets or if it's my WiFi AP (Ubiquiti Unifi UAP-AC-Pro firmware 6.0.14) that's not transmitting them. I wouldn't be surprised if there was some kind of 802.11 power saving feature that stops broadcasts from being delivered under certain conditions, but honestly I have no idea.

**Unicast WoL packets do work, from what I can tell… but the Unicast mode of LGTVCompanion seems to have a different problem that results in similar symptoms, further confusing the issue.** I noticed that `etherwake` in unicast mode always seems to work every single time, but LGTVCompanion in Unicast mode doesn't always work. I strongly suspect this is because the Unicast mode of LGTVCompanion is attempting to send the Unicast packet the "normal way", using the standard UDP/IP mechanism (i.e. `socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP)`, `sendto()`). The problem is, that mechanism assumes that the target device is in the [ARP](https://en.wikipedia.org/wiki/Address_Resolution_Protocol) cache (unlikely if the TV has been off for some time), or that it will respond to ARP requests. There again it looks like sometimes the TV will respond to ARP requests while off, and sometimes it won't, similar to how it sometimes ignores broadcast WoL packets. (In fact it might be the exact same root cause, since ARP requests *are* broadcast packets!) If ARP doesn't work, then attempting to send a UDP packet to the TV the normal way will simply not work. This can be verified using a sniffer like Wireshark, which won't show any WoL packets going out, showing unanswered ARP requests instead. This is precisely what one would expect. `etherwake` is immune to this problem because it uses raw sockets and puts the WoL payload directly inside an Ethernet frame - it doesn't use IP at all, and is therefore not reliant on ARP.

Assuming that my hypothesis is correct and that the issue truly lies with broadcast packets (either ARP packets or the WoL packets themselves) not being delivered to the TV over WiFi, then it looks like there are two possible fixes:

- Use LGTVCompanion in Unicast mode but have the user add a permanent static entry to the Windows ARP table so that the packet will go out even if the device is not responding to ARP requests.
   - I tried using `netsh` to do this but was unsuccessful. However I just discovered the existence of [`New-NetNeighbor`](https://docs.microsoft.com/en-us/powershell/module/nettcpip/new-netneighbor) and it looks like I was able to add a proper ARP override using that command. Now that I have the ARP static entry I've switched LGTVCompanion to Unicast mode and will report back after a few days…
- Improve LGTVCompanion so that it can send Unicast WoL packets without depending on ARP. Most likely that would mean changing the code to use raw sockets and craft the Ethernet payload directly like `etherwake` does, perhaps as a fourth "mode" of operation. This seems like a better long-term solution since it doesn't require the user to do anything, beyond selecting this new mode in the LGTVCompanion options.

**Comment by WilliamLeGod** [comment]
I have the same issue!

**Comment by dechamps** [comment]
@WilliamLeGod If you'd like to experiment, try the following potential workaround in a Powershell command prompt running as Administrator:

- Use the ` Get-NetIPConfiguration` command to figure out the `InterfaceIndex` of your network interface.
- Run: `New-NetNeighbor -InterfaceIndex <your interface index> -IPAddress <your TV IP address> -LinkLayerAddress <your TV MAC address using hyphens as separators>`.
  - For example: `New-NetNeighbor -InterfaceIndex 42 -IPAddress 192.168.0.24 -LinkLayerAddress 12-34-56-78-9A-BC`
- Switch to "Device IP-address" mode in the LGTVCompanion network options if you haven't already.
- Use the test function afterwards to make sure it still works.

If my theory is correct, after you've done this you should not experience the issue anymore. I'd be interested to know if it works for you.

The `NetNeighbor` entry will persist across reboots. To get rid of it and go back to the way things were, use `Remove-NetNeighbor -InterfaceIndex … -IPAddress …`.

**Comment by WilliamLeGod** [comment]
@dechamps Thank you for your help. I will test it soon and let you know. Meantime, I actually done some researches in regards to TV wi-fi/wake on Lan and found out that the wifi module inside the TV just can't function after an hour or more (from a LG representative) so this is more like a Hardware issue though

**Comment by JPersson77** [comment]
Hi Etienne, this is interesting! You're right regarding the unicast implementation, so if your theory is correct your workaround noted above (adding a static arp entry) should potentially work. I don't have much free time, at the moment, so if you can in the meantime please let me know how your experimentation with the ARP cache goes that wouold be great and I will start already thinking about a fourth mode of operations for the WOL, or maybe as a modified unicast. 

I'm, too, a little baffled as to why the broadcast would be dropped sometimes, but since your experimentation with etherwake indicate that the network interface of the TV in some aspects remains "engaged" even after many hours in off mode I think it might well be possible to fix this little quirk.

I also suspect you can verify that this issue only happen when using the wireless network? At least for me this issue never occur but I'm running cables currently (CX < -> unmanaged switch <->  ubiquit switch <-> ubiquiti edgerouter 4) .

Thanks for feedback and for the detailed troubleshooting!

**Comment by dechamps** [comment]
> the wifi module inside the TV just can't function after an hour or more (from a LG representative) so this is more like a Hardware issue though

I don't think so - at least not on the C1/G1 series. First of all, I woke the TV plenty of times 16+ hours after being turned off. Second, if that was true, then I wouldn't be able to work around the problem using unicast WoL. Third, according to the dashboard of my WiFi AP, the TV does stay connected to the WiFi pretty much indefinitely after being turned off.

**Comment by WilliamLeGod** [comment]
> > the wifi module inside the TV just can't function after an hour or more (from a LG representative) so this is more like a Hardware issue though
> 
> I don't think so - at least not on the C1/G1 series. First of all, I woke the TV plenty of times 16+ hours after being turned off. Second, if that was true, then I wouldn't be able to work around the problem using unicast WoL. Third, according to the dashboard of my WiFi AP, the TV does stay connected to the WiFi pretty much indefinitely after being turned off.

I guess my C9 uses the worse wifi module :(

**Comment by dechamps** [comment]
I think what I'm doing is working - I went 10 days in a row without the TV failing to turn on a single time. So I'm going to assume my theory is correct.

So now the question is how to adjust the behaviour of LGTVCompanion to work around the issue, i.e. ensure it never relies on Ethernet broadcasts - that means no IP broadcasts, and no broadcast ARP requests either.

I thought this would be easy, but after looking into it a bit it turns out it's really not. There are several options and none of them are great:

1. Send Ethernet frames directly, similar to what `etherwake` does.
   - Unfortunately there is no easy way to do that on Windows. Winsock raw sockets are severely constrained and cannot be used to send raw Ethernet frames.
   - [Npcap](https://npcap.com/) (formerly WinPcap) can [do it](https://npcap.com/guide/wpcap/pcap_inject.html), but the idea of having to bundle and install Npcap with LGTVCompanion seems… ugh.
2. Somehow tell Winsock the destination MAC address to use with `sendto()`.
   - As far as I can tell this is not possible.
3. Use [`CreateIpNetEntry2`](https://docs.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-createipnetentry2) (or equivalent) to manipulate the system-wide Windows ARP table and add a *temporary* (dynamic) entry for the TV, just before we send a unicast WoL packet.
   - This is not great because it makes LGTVCompanion alter system-wide networking configuration, but at least the change won't persist for more than a few seconds (due to ARP entry expiry).
   - I'm not 100% sure it's actually possible to add temporary/dynamic entries that way. Will have to check. The Microsoft documentation on this stuff is… rather sparse, to say the least.
4. When configuring a device for unicast in LGTVCompanion, prompt the user if they want to add a system-wide ARP entry for it, and if they agree, use  [`CreateIpNetEntry2`](https://docs.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-createipnetentry2) (or equivalent) to create a permanent entry.
   - Alternatively, just document the `New-NetNeighbor` workaround in the LGTVCompanion README. (That's less discoverable though.)
   - I'm not a fond of making that kind of system-wide change because we could end up causing permanent network breakage. For example, if the TV loses its IP address and the address ends up being reused by another device, that other device will not be reachable from the PC (because its ARP entry will have the wrong MAC address), and it will be extremely difficult for the user to understand what's going on, especially if they added the entry long ago and do not remember it.

**Comment by dechamps** [comment]
> I'm not 100% sure it's actually possible to add temporary/dynamic entries that way.

Well that's what I was afraid of: I tried it, and it didn't work. Specifically, `CreateIpNetEntry2` always adds `Permanent` entries even if I call it with `State = NlnsReachable`. Looks like it's not possible to add non-permanent ARP entries from user space - the various Powershell commands can't do it either.

However, it *is* possible to add entries that don't survive across reboots (i.e. add permanent entries to the `ActiveStore` but not the `PersistentStore`). (In fact it looks like `CreateIpNetEntry2` can only create non-persistent entries.)

It looks like perhaps the best approach would be for LGTVCompanion to do the following:

1. Immediately before sending the WoL packet, try to create a permanent ARP entry using `CreateIpNetEntry2()`.
2. Send the WoL packet.
3. Immediately after the packet is sent, call `DeleteIpNetEntry2()` to delete the ARP entry, but only if we actually did create the entry (i.e. `CreateIpNetEntry2()` did not return an error such as `ERROR_OBJECT_ALREADY_EXISTS`) to make sure we don't accidentally delete something that we didn't create.

This means that the ARP entry will only be present for a fraction of a second, hopefully minimizing any harmful side effects. Worst case scenario, if something terrible happens and the service crashes at exactly the wrong time, then the worst that can happen is that the user might have to reboot to get the ARP table back to its original state.

**Comment by dechamps** [comment]
I implemented the proposed fix in PR #22.

**Comment by dechamps** [comment]
By the way if anyone wants to try the fix, you can download the [installer](https://github.com/JPersson77/LGTVCompanion/suites/5727850673/artifacts/189538937) that [GitHub actions automatically built](https://github.com/JPersson77/LGTVCompanion/actions/runs/2011908436).
