### ISSUE TITLE
Is it possible to use "turn screen off" instead of shutting down tv on "disable screen" events?

### ISSUE THREAD

**Issue by Sugaroverdose** [JPersson77/LGTVCompanion#190]
Shutting down tv(and turning it on) is a pretty slow process, while turn screen off is almost instant and does not leads to unnecessary power cycles(since relay has click sound it seems like that it's electromechanical which means that it's resource isn't infinite)

**Comment by JPersson77** [comment]
Yes, it is possible to implement, but may I suggest you look into the user idle mode instead which operates like this. 

Configure user idle mode with a 5 minute trigger for example and in windows set "turn off screen after x minutes" to something like 120 minutes and you should be ok. 

Or am I not understanding your scenario?

**Comment by JPersson77** [comment]
Great, let me know how it works out for you.

Your suggestion is possible, but It adds complexity under the hood. For example, it is the same windows message which triggers the screen to go off when the user is idle and when the system goes to low power mode. 

I assume you still would like the screen to turn off when  the system  goes to sleep/hibernate.

So this iwhy user idle mode was implemented basically. That, and the fact that some applications tend to override windows behaviour and effectively disable the "turn off screen after x minutes". Cubase for me. And also games etc.

**Comment by Sugaroverdose** [comment]
> Great, let me know how it works out for you.

I've already swapped to it and it seems that it fits my use case pretty much perfectly

> Your suggestion is possible, but It adds complexity under the hood. For example, it is the same windows message which triggers the screen to go off when the user is idle and when the system goes to low power mode.
> 
> I assume you still would like the screen to power off when the system goes to sleep/hibernate.

I didn't know that hibernation is exactly the same type of event honestly, it's basically how i end usage sessions, so yeah, i've expected that it would turn off tv when triggered

>So this iwhy user idle mode was implemented basically. That, and the fact that some applications tend to override windows behaviour and effectively disable the "turn off screen after x minutes". Cubase for me. And also games etc.

Got it, thank you again help and explanation. 
I guess this feature needs this kind of text inside app itself, because currently it basically says that it's more aggressive way of detecting idle, but doesn't clarifies that it's utilises different way of preserving panel or that it's not possible to have screen turn off and shutdown tv at the same time for disable screen and sleep mode

I have another suggestion thou, since it's already distinct full screen apps it would be a nice addition to have different timeout for them

**Comment by dechamps** [comment]
Worth noting that using the "user idle" feature of LGTVCompanion is not the only way to achieve this result: you can also configure a blank Windows screensaver, which basically amounts to the same thing except LGTVCompanion uses a more aggressive definition of "idle". Basically, if you're using LGTVCompanion user idle and find that it turns off the screen at inappropriate times, you can try the screensaver approach which is less aggressive.

Another point to remember is that the TV will use a lot more power in "screen off" (or blank) mode than if it's fully off. My G1 uses 3.5 W when fully off, and 56 W on just "screen off" (or when displaying full screen black, which amounts to the same thing).

**Comment by Sugaroverdose** [comment]
> Another point to remember is that the TV will use a lot more power in "screen off" (or blank) mode than if it's fully off. My G1 uses 3.5 W when fully off, and 56 W on just "screen off" (or when displaying full screen black, which amounts to the same thing).

Well, for me it's exceptionally insignificant difference, it doesn't even worth spend time to calculate how big economy could be, the fact that there's no difference in displaying blank screensaver and screen off is the interesting part thou

**Comment by dechamps** [comment]
Well it's not just about the economy, it's also about releasing slightly more heat into the room, and also about the TV electronics being kept powered on which potentially reduces their lifespan, compared to if they were completely off and cold. I do agree that it's unlikely to matter in practice though.

**Comment by Sugaroverdose** [comment]
> Well it's not just about the economy, it's also about releasing slightly more heat into the room, and also about the TV electronics being kept powered on which potentially reduces their lifespan, compared to if they were completely off and cold. I do agree that it's unlikely to matter in practice though. (Also, one could argue that switching the TV completely off reduces the lifespan of that electromechanical relay that "clicks" on power transitions.)

In my experience it is exactly power cycles what reduces lifespan of electronics, even if board does not have any mechanical parts, board itself is a mechanical part if you change it's temperature significantly(due to thermal expansion) and it will lead to accumulative destruction of soldered joints(the only a question of how much cycles it will survive). Also, there is inrush current which is typically significantly higher than normal operation one, which might(or will) increase wear pace of some parts, like electrolytic capacitors(who ironically are responsible for it's appearance in the first place)

if something "clicks" - it wears and since use case requires a lot of "clicks", a lot more than vendor expected at least - it's better to reduce this difference to reasonable values

**Comment by Sugaroverdose** [comment]
After all i've added empty screensaver after 5 minutes to equation and aggressive "user idle mode"(including Fullscreen) after 10 minutes. Thank you @JPersson77 and @dechamps for your help :)
