### ISSUE TITLE
trying to connect 2 lg tvs only one shows up

### ISSUE THREAD

**Issue by costispavlou** [JPersson77/LGTVCompanion#197]
I successfully set up my C3 and today I got a second LG added to my setup. 
I tried scanning for devices it found the second monitor but now only the first one shows up to be configured.
Multimonitor shows only one device as well. 
What am I doing wrong ? Can you help me ? 

Screenshots are below:

<img width="503" alt="image" src="https://github.com/JPersson77/LGTVCompanion/assets/57916603/54f4d0c7-a0bf-401b-b348-568e28d5f27e">

<img width="524" alt="image" src="https://github.com/JPersson77/LGTVCompanion/assets/57916603/94f22adf-a0e7-4f5e-9f6c-f5229259989b">

**Comment by JPersson77** [comment]
Hi @costispavlou it is hard to say exactly what happened from the screenshots. Looks like maybe the same device was detected twice(?)

You should add the devices manually (or edit the existing entries) to ensure the IP and mac-address are correct, respectively. And name them so you know which is which. You can manually add devices by clicking the down-arrow and select "add manually"

**Comment by costispavlou** [comment]
yeah all good, sorry for the panic post. 
Question: is there a way for the device to enter in ready mode ?

**Comment by costispavlou** [comment]
that's the problem, the feature is enabled but shutting down my computer just shuts off the tv.

**Comment by JPersson77** [comment]
Oh yeah you are right! Never noticed that. I'd almost consider it a feature :)

But I can have a look and see if there is another way to invoke power off without bypassing the art screensaver

**Comment by costispavlou** [comment]
Yeah, that'd be awesome really. At least to have it as a choice. In any case you did a great app mate. Kudos to you. 
Want me to change the title of the thread or anything or you got it?

**Comment by JPersson77** [comment]
All good mate. Thanks!
