### ISSUE TITLE
LG tv turns off but not on 

### ISSUE THREAD

**Issue by tomotomo123123** [JPersson77/LGTVCompanion#198]
Hello, I have an LG OLED48A2PUA.  I installed the LG TV companion for use with my computer and the tv did shut off by itself.  However, the tv does not power on when I power the computer on.  I have to manually turn the tv on.  I have tried all options on the tv companion.  I have updates on it's version 3.4.0.  Thank you for any guidance in advance.

https://www.bestbuy.com/site/lg-48-class-a2-series-oled-4k-uhd-smart-webos-tv/6501902.p?skuId=6501902

Logs:

Tue 10:38:41 > Event subscription callback: System restart detected.
Tue 10:38:45 > ** System requests displays OFF.
Tue 10:38:45 > Device1, spawning Thread_DisplayOff().
Tue 10:38:45 > Device1, [DEBUG] (SSL) OFF response 1: {"type":"registered","id":"register_0","payload":{"client-key":"ba6186e4b4f2c875478421e82fff1309"}}
Tue 10:38:45 > Device1, [DEBUG] (SSL) OFF response 2: {"type":"response","id":27,"payload":{"state":"Active","returnValue":true}}
Tue 10:38:45 > Device1, [DEBUG] (SSL) OFF response 3: {"type":"response","id":28,"payload":{"returnValue":true,"appId":"com.webos.app.hdmi1","processId":"","windowId":""}}
Tue 10:38:45 > Device1, HDMI1 input active.
Tue 10:38:46 > Device1, [DEBUG] (SSL) OFF response 4: {"type":"response","id":29,"payload":{"returnValue":true}}
Tue 10:38:46 > Device1, power state is: OFF.
Tue 10:38:46 > ** System is restarting.
Tue 10:39:54 > ** System resumed from low power state.
Tue 10:39:55 > ** System requests displays ON.
Tue 10:39:55 > Device1, spawning Thread_DisplayOn().
Tue 10:39:55 > Device1, repeating WOL broadcast started to MAC: 88EF1679A091 using IP address: 192.168.1.210
Tue 10:39:55 > Device1, Best route to IP - interface index 18 LUID 1689399683186688 route protocol 2
Tue 10:39:55 > ** System resumed from low power state (Automatic).
Tue 10:39:55 > Device1, spawning Thread_SendRequest().
Tue 10:40:16 > Device1, WARNING! Thread_DisplayOn(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Tue 10:40:16 > Device1, WARNING! Thread_SendRequest(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Tue 10:40:31 > -daemon 4 started
Tue 10:40:31 > [IPC Daemon 4] Started.
Tue 10:40:37 > Device1, WARNING! Thread_DisplayOn(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Tue 10:40:37 > Device1, WARNING! Thread_SendRequest(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Tue 10:40:39 > -daemon 4 topology state Device1 
Tue 10:40:39 > [IPC Daemon 4] Windows monitor topology was changed. Device1:ON 
Tue 10:40:39 > Device1, omitted Thread_DisplayOn().
Tue 10:40:58 > Device1, WARNING! Thread_DisplayOn(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Tue 10:40:58 > Device1, WARNING! Thread_SendRequest(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Tue 10:41:06 > Device1, repeating WOL broadcast ended
Tue 10:41:19 > Device1, WARNING! Thread_DisplayOn(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Tue 10:41:19 > Device1, WARNING! Thread_SendRequest(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']

**Comment by JPersson77** [comment]
Hi @tomotomo123123 , it sounds like either of the following might help: 

1) Confirm that you have enabled wake on lan for the TV. See point 1 here:

https://github.com/JPersson77/LGTVCompanion?tab=readme-ov-file#installation-and-usage

2) or alternatively confirm that the MAC address of the TV is correctly entered in the device configuration in the app. You do this by reviewing the MAC address for the wired or wireless (depending on which you use) network adapter in the network settings of the TV

**Comment by tomotomo123123** [comment]
Ok, I think I foolish put my pc MAC address instead of the tv.   After doing this, I kept getting the "no signal" input from the tv, after shutoff but I just tried some different options on the app and everything is resolved, thank you.  

Did you make this app?  It's really helpful.

**Comment by JPersson77** [comment]
Good to hear! It should work :) 

Yes I have coded the app :D

**Comment by tomotomo123123** [comment]
Wow!  Amazing!  

I am wondering if anyone at LG knows it exists, maybe they could pay you a royalty or something.  The tv as a monitor is much more valuable with the app.

**Comment by JPersson77** [comment]
I wish :D Thanks mate :)

**Comment by tomotomo123123** [comment]
Hi, so sorry to bother you.  I can deal with this issue, but if it can be solved that would be great also.  So, the tv turns off and on ok with the pc during the day fine.  However, when I turn it off at night, it turns off fine, but the next morning, I have to manually power on the tv.  I have copy and pasted the log.

Tue 23:13:05 > ** System is suspending to a low power state.(or event callback is missing)
Wed 08:12:12 > ** System resumed from low power state.
Wed 08:12:13 > ** System requests displays ON.
Wed 08:12:13 > Device1, spawning Thread_DisplayOn().
Wed 08:12:13 > Device1, repeating WOL broadcast started to MAC: D8E35E536A16 using IP address: 192.168.1.210
Wed 08:12:13 > Device1, Best route to IP - interface index 18 LUID 1689399683186688 route protocol 2
Wed 08:12:13 > ** System resumed from low power state (Automatic).
Wed 08:12:13 > Device1, spawning Thread_SendRequest().
Wed 08:12:34 > Device1, WARNING! Thread_DisplayOn(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Wed 08:12:34 > Device1, WARNING! Thread_SendRequest(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Wed 08:12:49 > -daemon 4 started
Wed 08:12:49 > [IPC Daemon 4] Started.
Wed 08:12:55 > Device1, WARNING! Thread_DisplayOn(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Wed 08:12:55 > Device1, WARNING! Thread_SendRequest(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Wed 08:12:57 > -daemon 4 topology state Device1 
Wed 08:12:57 > [IPC Daemon 4] Windows monitor topology was changed. Device1:ON 
Wed 08:12:57 > Device1, omitted Thread_DisplayOn().
Wed 08:13:16 > Device1, WARNING! Thread_DisplayOn(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Wed 08:13:16 > Device1, WARNING! Thread_SendRequest(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Wed 08:13:24 > Device1, repeating WOL broadcast ended
Wed 08:13:37 > Device1, WARNING! Thread_DisplayOn(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Wed 08:13:37 > Device1, WARNING! Thread_SendRequest(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Wed 08:15:26 > -daemon 4 topology state Device1 
Wed 08:15:26 > [IPC Daemon 4] Windows monitor topology was changed. Device1:ON 
Wed 08:15:26 > Device1, spawning Thread_DisplayOn().
Wed 08:15:26 > Device1, repeating WOL broadcast started to MAC: D8E35E536A16 using IP address: 192.168.1.210
Wed 08:15:26 > Device1, Best route to IP - interface index 18 LUID 1689399683186688 route protocol 2
Wed 08:15:48 > Device1, WARNING! Thread_DisplayOn(): handshake: An existing connection was forcibly closed by the remote host [system:10054]
Wed 08:15:55 > Device1, [DEBUG] (SSL) ON response 1: {"type":"registered","id":"register_0","payload":{"client-key":"ba6186e4b4f2c875478421e82fff1309"}}
Wed 08:15:56 > Device1, [DEBUG] (SSL) ON response 2: {"type":"error","id":29,"error":"500 Application error","payload":{"returnValue":false,"state":"Active","errorCode":"-102","errorText":"The current sub state must be 'screen off'"}}
Wed 08:15:56 > Device1, [DEBUG] (SSL) ON response 3: {"type":"response","id":30,"payload":{"state":"Active","returnValue":true}}
Wed 08:15:56 > Device1, power state is: ON
Wed 08:15:57 > Device1, repeating WOL broadcast ended

**Comment by JPersson77** [comment]
Ho @tomotomo123123 no worries. My guess is the TV is connected via wifi, so then the recommendation is to use a network cable instead (if possible).

I t seems the wifi nic of the TV has trouble reconneting when/if the connection is lost.

I dont think your model TV has the "always ready" which I'd otherwise also recommend trying out to see if it makes a difference

**Comment by aboutvin** [comment]
@JPersson77 I have no issues with turning the PC on however, when I shutdown my PC. I kept getting the "no signal" input from the TV. I will appreciate any help here thank you!

**Comment by JPersson77** [comment]
hi @aboutvin maybe start a new issue as it seems to be another issue

**Comment by JPersson77** [comment]
Hi @tomotomo123123 any more feedback wrt the above or should we close the issue?

**Comment by JPersson77** [comment]
Closing due to missing feedback, please feel free to reopen as needed.
