### ISSUE TITLE
Playstation input issue (Enhancement) 

### ISSUE THREAD

**Issue by WilliamLeGod** [JPersson77/LGTVCompanion#20]
Example: PS5 on HDMI 1, PC on HDMI 2

Scenario 1: LG companion using the option to turn to PC (HDMI 2) when TV is off at HDMI 1 (PS5) last time - Result when turn on PC: PS5 (HDMI 1) shows up for a second or two and force PS5 to turn on (If using CEC option in PS5)

Scenario 2: Using Hotel mode to force HDMI 2 as default input source - Result when turn on PC: Ps5 (HDMI 1) input source doesn't show up which will then not trigger turning on the PS5

Is there a way to configure this new feature in LG companion to be exactly like in Hotel mode since Hotel mode disable Wake on Lan and some other TV features like Airplay, Lite pixel refresher

Thanks!

**Comment by JPersson77** [comment]
Hi, will investigate for a potential fix.

**Comment by WilliamLeGod** [comment]
> Hi, will investigate for a potential fix.

Thank you!.

Also, I've tested the seconds between turning on Xbox seri X, Ps5 and PC  And TV on and they are different, could you explain this by any chance?
 - Xbox seri X (From OFF instead of standby/sleep): Press xbox button on controller, Xbox turns on Immediately (not xbox OS but the hardware) and also TV turns on IMMEDIATELY!
 - PS5 (From OFF instead of Rest mode): Press PS button on controller and hearing the beep voice, Ps5 turns on Immediately (not PS OS but the hardware) and also TV turns on after around 9 seconds! (I tried several times already)
 - PC: Press Power button, PC hardware turns on:
 + From Sleep, TV turns on after 13 seconds
 + From Off, TV turns on after 19 seconds 

So the way I'm seeing this is, It should  be possible to lower the delay of TV turns on when turning on the PC right?

**Comment by JPersson77** [comment]
Hi @WilliamLeGod 

the XBOX and PS5 are using different means for controlling the TV (CEC) and PC graphics cards do not have that functionality thus this app use other mechanisms for controlling the display, which require at least the OS to be at a state where services are loaded, which explains this delay. 

And, no good fix devised for the first issue I'm afraid. Not having a PS5 to replicate doesn't help
