### ISSUE TITLE
LG C2 turns off when in use

### ISSUE THREAD

**Issue by douglasparker** [JPersson77/LGTVCompanion#200]
The LG TV Companion app used to work great, but after reinstalling Windows I started having major issues with it. This started months ago and I stopped using it for a while and then tried again today and the issue persists.

so basically, after first setting it up my TV has a pop up about a mobile device wanting to connect or whatever- This is the LG TV Companion app.

After allowing the connection, things work normal but soon after I get that same pop up and clicking decline or no just results it popping up over and over again.

At this point, I click allow or yes to make it go away and the entire app stops working as expected. I can be doing anything and it seems to shut off the TV after 10 or 15 minutes; which is the same amount of time I have set for idle detection.

I’ve had to reset my TV many times and have reinstalled the LG TV Companion app and the issue still persists.

Edit: If you can provide the default log directory I can upload the logs.

**Comment by JPersson77** [comment]
Hi,

c:/programdata/lgtv companion/

Please upload both log.txt and config.json.

After allowing the popup once on initial install you should never see it again. Do you currently have other software installed which may conflict?

**Comment by douglasparker** [comment]
> Hi,
> 
> c:/programdata/lgtv companion/
> 
> Please upload both log.txt and config.json.

These logs are after the TV went dark (but was still technically on, the display just appeared to be off or in a sleep state).

It hasn't turned off all the way just yet.

[config.json](https://github.com/JPersson77/LGTVCompanion/files/14472363/config.json)
[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/14472364/Log.txt)

> After allowing the popup once on initial install you should never see it again. Do you currently have other software installed which may conflict?

I do not believe I am running any other software that would conflict.

The screen originally went black and hitting a button on the remote made it turn on again (the TV wasn't actually off at this point), but a shortly after the LG logo appeared and then it actually turned off.

If I reset the TV, this doesn't happen again until I allow the mobile device connection (LG TV Companion). The initial allow is fine, it's after it's been on for a bit it will eventually spam that allow prompt until I finally give in and hit allow again. That's when the issues seem to start.

Ah, as I was writing this the screen went black again! The TV was still on, but it was completely black. I waited to see if it would turn off and it didn't. So I just hit any button on the remote and the picture wakes up.

At some point, the TV gets turned off all the way.

**Comment by douglasparker** [comment]
It went black again, but nothing new was added to the logs. Mouse and keyboard doesn't wake the screen. Only hitting any button on the remote. The TV isn't actually off at this point.

If I disconnect the TV from WiFi, this stops happening. This makes me believe it is LG TV Companion.

**Comment by JPersson77** [comment]
Thanks can you upload the full log please?

**Comment by douglasparker** [comment]
> Thanks the log seem to be a snippet, can you upload the full log please?

[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/14472394/Log.txt)

Here is the log again. I did run a second test.

**Comment by douglasparker** [comment]
[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/14472399/Log.txt)
Uploaded again because it just went black again.

**Comment by JPersson77** [comment]
still does not seem to be a full log. It should at minimum start with this line: 

Sun 10:39:36 > LGTV Companion Service started (v 3.4.1) ---------------------------

can you try restarting the pc and then send me the log again.

How many users are currently logged onto your PC? Can you confirm how many lgtvdaemon.exe and lgtvsvc.exe you see in task manager

**Comment by douglasparker** [comment]
> still does not seem to be a full log. It should at minimum start with this line:
> 
> Sun 10:39:36 > LGTV Companion Service started (v 3.4.1) ---------------------------
> 
> can you try restarting the pc and then send me the log again.
> 
> How many users are currently logged onto your PC? Can you confirm how many lgtvdaemon.exe and lgtvsvc.exe you see in task manager

It's not a full log because logging wasn't enabled until I replied to your message. I waited for the event to happen again before I sent the first log over.

I am the only user on this PC, and there is only one instance of the daemon running.

**Comment by JPersson77** [comment]
Thanks, but it does not look complete regardless so let's figure out why. 

When you click apply in the main ui after having changed the global option to enable logging the service should restart. When the service restart it will start by writing the line I mentioned. I need to review the start of the log to be able to help really. Your log does not indicate anything wromng, in fact it does not indicate that LGTV companion is blanking the screen even. So this is where we are now.

if you restart your PC, I'd be interested in having a look at the log after that

**Comment by douglasparker** [comment]
> if you restart your PC, I'd be interested in having a look at the log after that

Okay, I restarted and waited for the black screen again.

[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/14472482/Log.txt)

> It still sounds a little like there is some other software conflicting because of the multiple popups on the tv, or possibly lgtv companion is running in two instances somehow.

Yeah, the strange thing is it worked fine until the pop-up spam. Clicking decline was not an option, it just came back over and over. There is no other software installed that interfaces with the LG TV.

In fact, I have another device on the network in another room that doesn't get any pop ups like that. I was thinking maybe it's a neighbor (I live in an apartment complex), but they'd have to be on the same WiFi network right?

My WiFi network is locked down. I use Ubiquiti network equipment if that helps... There are no unknown devices on the network either. It's pretty much my network equipment, a few PCs, some phones, and Apple TV.

**Comment by JPersson77** [comment]
Thanks, so the log shows nothing out of the ordinary. Please send it again after the screen blanks involontarily next time. Because I can see no trace in the log of the app blanking the screen and I want to verify that after the rrestart of the system.

I notice you are using IP range 10.x.x.x, do you run your own dhcp server or are you on the apartment complex's IP range?

**Comment by douglasparker** [comment]
> Thanks, so the log shows nothing out of the ordinary. Please send it again after the screen blanks involontarily next time. Because I can see no trace in the log of the app blanking the screen and I want to verify that is the case also after you now have restarted the system.

It has since happened again. Here is a new log:
[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/14472560/Log.txt)


> I notice you are using IP range 10.x.x.x, do you run your own dhcp server/router or are you on the apartment complex's IP range? The wifi is through a protected access point but it may be a possibility that a neighbour can access your devices, depending on how things are set up and how your internet is delivered

I have my own private network with my own enterprise grade network equipment. There are no foreign devices on the network.

**Comment by JPersson77** [comment]
Thanks, then I think we can probably conclude that THIS instance of the app does not send the command to the TV to blank the screen. There is just nothing in the log to indicate that the daemon has signalled that the user is idle or that the service has communicated with the TV to blank the screen.

So then what? If you know that there can be no foreigna traffic on your network then either it must be something else on your network which blanks the screen.

Another install of lgtv companion on another PC? Or an old install of the app on your PC which somehow interferes? You confirmed that only one LGTV daemon was running, but how about LGTVsvc.exe? Are you using ColorControl?

**Comment by douglasparker** [comment]
> Thanks, then I think we can probably conclude that THIS instance of the app does not send the command to the TV to blank the screen. There is just nothing in the log to indicate that the daemon has signalled that the user is idle or that the service has communicated with the TV to blank the screen.
> 
> So then what? If you know that there can be no foreign traffic on your network then it must be something else on your local network or current PC which blanks the screen.

My gut feeling is that the initial prompt to allow control of the TV was from LG TV Companion.

The follow up prompts must be from something else on the network- because it initially worked fine and whatever was causing the prompts (they actually appeared the second day after I got LG TV Companion installed) would not take decline. It was like something was spamming the device for access.

I think what I am going to do is reset the TV and then create a firewall rule to only allow incoming traffic to the TV from the computer running LG TV Companion. Then set it up again.

This is extremely weird behavior, and after seeing the logs I agree that something on my network is doing something weird.

There are no foreign devices, so it must be something else sending some kind of signal or packet over the network. Maybe some kind of broadcast? Regardless, the firewall rule should resolve this issue.

I will report back on this.

> Another install of lgtv companion on another PC? Or an old install of the app on your PC which somehow interferes? You confirmed that only one LGTV daemon was running, but how about LGTVsvc.exe? Are you using ColorControl?

I do not believe it is an app on my PC. There is only one instance of LGTVsvc.exe running as well. And I only have the LG TV companion app on one machine.

I will report back my findings when I am done.

**Comment by JPersson77** [comment]
It is a bit weird indeed. Keep me posted please! 

Wireshark is a great tool for caputing all packets going to a certain device

**Comment by dechamps** [comment]
I second the use of Wireshark/tcpdump/port mirroring/your sniffer of choice. Look for connections going to the TV on TCP port 3001 (or TCP port 3000 if your TV is running old firmware). If the originating device is a Windows PC, you can use [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) (filter by Event Class: Network) to watch for network connections and determine which specific process is connecting to the TV.

**Comment by douglasparker** [comment]
> It is a bit weird indeed. Keep me posted please!
> 
> Wireshark is a great tool for caputing all packets going to a certain device

I reset the TV and allowed the connection from LG TV Companion and things are working again.

However, I am getting that mobile device connection spam.

My other LG TV doesn't get this spam, but maybe that's because TV On With Mobile is disabled?

Here are the wireshark logs after the mobile device connection spam has started.

It seems like the LG TV is the source of all communication when the mobile device connection spam is occurring and I don't see any new things being sent over the network when the event starts either...

```
34	0.213515	10.0.0.20	10.0.0.21	ICMP	74	Echo (ping) request  id=0x0001, seq=11878/26158, ttl=128 (reply in 35)
35	0.216411	10.0.0.21	10.0.0.20	ICMP	74	Echo (ping) reply    id=0x0001, seq=11878/26158, ttl=64 (request in 34)
140	1.229084	10.0.0.20	10.0.0.21	ICMP	74	Echo (ping) request  id=0x0001, seq=11879/26414, ttl=128 (reply in 141)
141	1.232644	10.0.0.21	10.0.0.20	ICMP	74	Echo (ping) reply    id=0x0001, seq=11879/26414, ttl=64 (request in 140)
214	2.246076	10.0.0.20	10.0.0.21	ICMP	74	Echo (ping) request  id=0x0001, seq=11880/26670, ttl=128 (reply in 215)
215	2.250670	10.0.0.21	10.0.0.20	ICMP	74	Echo (ping) reply    id=0x0001, seq=11880/26670, ttl=64 (request in 214)
383	3.248872	10.0.0.20	10.0.0.21	ICMP	74	Echo (ping) request  id=0x0001, seq=11881/26926, ttl=128 (reply in 385)
385	3.252841	10.0.0.21	10.0.0.20	ICMP	74	Echo (ping) reply    id=0x0001, seq=11881/26926, ttl=64 (request in 383)
507	4.254425	10.0.0.20	10.0.0.21	ICMP	74	Echo (ping) request  id=0x0001, seq=11882/27182, ttl=128 (reply in 510)
510	4.257292	10.0.0.21	10.0.0.20	ICMP	74	Echo (ping) reply    id=0x0001, seq=11882/27182, ttl=64 (request in 507)
591	4.967470	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
3324	29.967950	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
4390	39.828883	10.0.0.21	255.255.255.255	UDP	78	56700 → 56700 Len=36
6046	54.969590	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
8751	79.971676	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
9493	85.806889	10.0.0.21	10.0.0.20	UDP	384	37777 → 53563 Len=342
9494	85.806946	10.0.0.21	10.0.0.20	UDP	384	37777 → 53563 Len=342
9499	86.009230	10.0.0.21	10.0.0.20	UDP	384	37777 → 53563 Len=342
9500	86.009291	10.0.0.21	10.0.0.20	UDP	384	37777 → 53563 Len=342
9670	86.728775	10.0.0.21	10.0.0.20	UDP	384	60405 → 53563 Len=342
9671	86.728866	10.0.0.21	10.0.0.20	UDP	384	60405 → 53563 Len=342
9677	86.930654	10.0.0.21	10.0.0.20	UDP	384	60405 → 53563 Len=342
9678	86.930719	10.0.0.21	10.0.0.20	UDP	384	60405 → 53563 Len=342
9741	87.650915	10.0.0.21	10.0.0.20	UDP	384	45536 → 53563 Len=342
9742	87.650953	10.0.0.21	10.0.0.20	UDP	384	45536 → 53563 Len=342
9757	87.867897	10.0.0.21	10.0.0.20	UDP	384	45536 → 53563 Len=342
9758	87.867964	10.0.0.21	10.0.0.20	UDP	384	45536 → 53563 Len=342
9872	88.879509	10.0.0.21	10.0.0.20	UDP	384	36692 → 53563 Len=342
9873	88.879545	10.0.0.21	10.0.0.20	UDP	384	36692 → 53563 Len=342
9891	89.080923	10.0.0.21	10.0.0.20	UDP	384	36692 → 53563 Len=342
9892	89.080973	10.0.0.21	10.0.0.20	UDP	384	36692 → 53563 Len=342
11085	99.831556	10.0.0.21	255.255.255.255	UDP	78	56700 → 56700 Len=36
12991	104.973276	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
13286	107.590249	10.0.0.21	239.255.255.250	SSDP	287	NOTIFY * HTTP/1.1 
13288	107.640237	10.0.0.21	239.255.255.250	SSDP	296	NOTIFY * HTTP/1.1 
13289	107.690536	10.0.0.21	239.255.255.250	SSDP	295	NOTIFY * HTTP/1.1 
13290	107.741487	10.0.0.21	239.255.255.250	SSDP	313	NOTIFY * HTTP/1.1 
13375	107.991594	10.0.0.21	239.255.255.250	SSDP	287	NOTIFY * HTTP/1.1 
13377	108.042213	10.0.0.21	239.255.255.250	SSDP	296	NOTIFY * HTTP/1.1 
13379	108.092831	10.0.0.21	239.255.255.250	SSDP	295	NOTIFY * HTTP/1.1 
13399	108.142773	10.0.0.21	239.255.255.250	SSDP	313	NOTIFY * HTTP/1.1 
13787	111.802598	10.0.0.21	239.255.255.250	SSDP	287	NOTIFY * HTTP/1.1 
13795	111.852676	10.0.0.21	239.255.255.250	SSDP	296	NOTIFY * HTTP/1.1 
13796	111.902799	10.0.0.21	239.255.255.250	SSDP	327	NOTIFY * HTTP/1.1 
13798	111.953487	10.0.0.21	239.255.255.250	SSDP	339	NOTIFY * HTTP/1.1 
13825	112.203832	10.0.0.21	239.255.255.250	SSDP	287	NOTIFY * HTTP/1.1 
13826	112.254554	10.0.0.21	239.255.255.250	SSDP	296	NOTIFY * HTTP/1.1 
13827	112.305025	10.0.0.21	239.255.255.250	SSDP	327	NOTIFY * HTTP/1.1 
13828	112.355252	10.0.0.21	239.255.255.250	SSDP	339	NOTIFY * HTTP/1.1 
14220	116.078527	10.0.0.21	224.0.0.251	MDNS	81	Standard query 0x0000 PTR lb._dns-sd._udp.local, "QM" question
15062	123.592475	10.0.0.21	239.255.255.250	SSDP	385	NOTIFY * HTTP/1.1 
15065	123.642517	10.0.0.21	239.255.255.250	SSDP	394	NOTIFY * HTTP/1.1 
15070	123.694154	10.0.0.21	239.255.255.250	SSDP	441	NOTIFY * HTTP/1.1 
15108	123.743168	10.0.0.21	239.255.255.250	SSDP	439	NOTIFY * HTTP/1.1 
15110	123.794532	10.0.0.21	239.255.255.250	SSDP	451	NOTIFY * HTTP/1.1 
15133	123.844018	10.0.0.21	239.255.255.250	SSDP	449	NOTIFY * HTTP/1.1 
15168	124.094747	10.0.0.21	239.255.255.250	SSDP	385	NOTIFY * HTTP/1.1 
15171	124.144903	10.0.0.21	239.255.255.250	SSDP	394	NOTIFY * HTTP/1.1 
15179	124.195287	10.0.0.21	239.255.255.250	SSDP	441	NOTIFY * HTTP/1.1 
15191	124.245878	10.0.0.21	239.255.255.250	SSDP	439	NOTIFY * HTTP/1.1 
15192	124.296128	10.0.0.21	239.255.255.250	SSDP	451	NOTIFY * HTTP/1.1 
15193	124.346441	10.0.0.21	239.255.255.250	SSDP	449	NOTIFY * HTTP/1.1 
15733	129.975034	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
18432	154.976652	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
18931	159.834209	10.0.0.21	255.255.255.255	UDP	78	56700 → 56700 Len=36
21168	179.978572	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
23837	204.980823	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
23881	205.619651	10.0.0.21	10.0.0.20	UDP	384	46116 → 54475 Len=342
23882	205.619689	10.0.0.21	10.0.0.20	UDP	384	46116 → 54475 Len=342
23913	205.820948	10.0.0.21	10.0.0.20	UDP	384	46116 → 54475 Len=342
23914	205.820991	10.0.0.21	10.0.0.20	UDP	384	46116 → 54475 Len=342
24041	206.847931	10.0.0.21	10.0.0.20	UDP	384	55351 → 54475 Len=342
24042	206.848386	10.0.0.21	10.0.0.20	UDP	384	55351 → 54475 Len=342
24058	207.049930	10.0.0.21	10.0.0.20	UDP	384	55351 → 54475 Len=342
24059	207.049966	10.0.0.21	10.0.0.20	UDP	384	55351 → 54475 Len=342
24160	207.770034	10.0.0.21	10.0.0.20	UDP	384	55779 → 54475 Len=342
24161	207.770136	10.0.0.21	10.0.0.20	UDP	384	55779 → 54475 Len=342
24163	207.971657	10.0.0.21	10.0.0.20	UDP	384	55779 → 54475 Len=342
24164	207.971706	10.0.0.21	10.0.0.20	UDP	384	55779 → 54475 Len=342
24278	208.690968	10.0.0.21	10.0.0.20	UDP	384	49036 → 54475 Len=342
24279	208.691473	10.0.0.21	10.0.0.20	UDP	384	49036 → 54475 Len=342
24298	208.893321	10.0.0.21	10.0.0.20	UDP	384	49036 → 54475 Len=342
24299	208.893366	10.0.0.21	10.0.0.20	UDP	384	49036 → 54475 Len=342
25538	219.836807	10.0.0.21	255.255.255.255	UDP	78	56700 → 56700 Len=36
26883	229.982767	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
29611	255.150413	10.0.0.21	239.255.255.250	SSDP	158	M-SEARCH * HTTP/1.1 
29612	255.250913	10.0.0.21	239.255.255.250	SSDP	158	M-SEARCH * HTTP/1.1 
29616	255.351571	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
33085	274.418990	10.0.0.21	239.255.255.250	SSDP	297	NOTIFY * HTTP/1.1 
33102	274.469204	10.0.0.21	239.255.255.250	SSDP	306	NOTIFY * HTTP/1.1 
33104	274.519256	10.0.0.21	239.255.255.250	SSDP	345	NOTIFY * HTTP/1.1 
33110	274.569753	10.0.0.21	239.255.255.250	SSDP	345	NOTIFY * HTTP/1.1 
33387	274.820417	10.0.0.21	239.255.255.250	SSDP	297	NOTIFY * HTTP/1.1 
33451	274.870616	10.0.0.21	239.255.255.250	SSDP	306	NOTIFY * HTTP/1.1 
33673	274.921212	10.0.0.21	239.255.255.250	SSDP	345	NOTIFY * HTTP/1.1 
33891	274.970794	10.0.0.21	239.255.255.250	SSDP	345	NOTIFY * HTTP/1.1 
34648	279.839729	10.0.0.21	255.255.255.255	UDP	78	56700 → 56700 Len=36
34709	280.353903	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
37939	305.357582	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
42407	325.738739	10.0.0.21	10.0.0.20	UDP	384	53198 → 63954 Len=342
42408	325.738838	10.0.0.21	10.0.0.20	UDP	384	53198 → 63954 Len=342
42461	325.940350	10.0.0.21	10.0.0.20	UDP	384	53198 → 63954 Len=342
42462	325.940395	10.0.0.21	10.0.0.20	UDP	384	53198 → 63954 Len=342
42565	326.662458	10.0.0.21	10.0.0.20	UDP	384	48832 → 63954 Len=342
42566	326.662503	10.0.0.21	10.0.0.20	UDP	384	48832 → 63954 Len=342
42572	326.861983	10.0.0.21	10.0.0.20	UDP	384	48832 → 63954 Len=342
42573	326.862032	10.0.0.21	10.0.0.20	UDP	384	48832 → 63954 Len=342
42750	327.888788	10.0.0.21	10.0.0.20	UDP	384	48706 → 63954 Len=342
42751	327.888826	10.0.0.21	10.0.0.20	UDP	384	48706 → 63954 Len=342
42771	328.091625	10.0.0.21	10.0.0.20	UDP	384	48706 → 63954 Len=342
42772	328.091682	10.0.0.21	10.0.0.20	UDP	384	48706 → 63954 Len=342
42875	328.811010	10.0.0.21	10.0.0.20	UDP	384	44705 → 63954 Len=342
42876	328.811070	10.0.0.21	10.0.0.20	UDP	384	44705 → 63954 Len=342
42882	329.012757	10.0.0.21	10.0.0.20	UDP	384	44705 → 63954 Len=342
42883	329.012801	10.0.0.21	10.0.0.20	UDP	384	44705 → 63954 Len=342
43027	330.357476	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
44451	339.842297	10.0.0.21	255.255.255.255	UDP	78	56700 → 56700 Len=36
46415	355.359597	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
49029	380.361208	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
49695	387.038529	10.0.0.21	239.255.255.250	SSDP	267	NOTIFY * HTTP/1.1 
49697	387.088710	10.0.0.21	239.255.255.250	SSDP	276	NOTIFY * HTTP/1.1 
49699	387.141792	10.0.0.21	239.255.255.250	SSDP	303	NOTIFY * HTTP/1.1 
49702	387.191862	10.0.0.21	239.255.255.250	SSDP	305	NOTIFY * HTTP/1.1 
49722	387.442816	10.0.0.21	239.255.255.250	SSDP	267	NOTIFY * HTTP/1.1 
49729	387.492844	10.0.0.21	239.255.255.250	SSDP	276	NOTIFY * HTTP/1.1 
49731	387.543180	10.0.0.21	239.255.255.250	SSDP	303	NOTIFY * HTTP/1.1 
49743	387.593965	10.0.0.21	239.255.255.250	SSDP	305	NOTIFY * HTTP/1.1 
50964	399.844681	10.0.0.21	255.255.255.255	UDP	78	56700 → 56700 Len=36
52823	405.363126	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
55104	430.365475	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
55975	445.857384	10.0.0.21	10.0.0.20	UDP	384	55055 → 53862 Len=342
55976	445.857432	10.0.0.21	10.0.0.20	UDP	384	55055 → 53862 Len=342
56034	446.059783	10.0.0.21	10.0.0.20	UDP	384	55055 → 53862 Len=342
56035	446.059835	10.0.0.21	10.0.0.20	UDP	384	55055 → 53862 Len=342
56079	446.779857	10.0.0.21	10.0.0.20	UDP	384	59674 → 53862 Len=342
56080	446.779906	10.0.0.21	10.0.0.20	UDP	384	59674 → 53862 Len=342
56084	446.981350	10.0.0.21	10.0.0.20	UDP	384	59674 → 53862 Len=342
56085	446.981412	10.0.0.21	10.0.0.20	UDP	384	59674 → 53862 Len=342
56146	447.700549	10.0.0.21	10.0.0.20	UDP	384	52281 → 53862 Len=342
56147	447.700986	10.0.0.21	10.0.0.20	UDP	384	52281 → 53862 Len=342
56154	447.903084	10.0.0.21	10.0.0.20	UDP	384	52281 → 53862 Len=342
56155	447.903168	10.0.0.21	10.0.0.20	UDP	384	52281 → 53862 Len=342
56193	448.622374	10.0.0.21	10.0.0.20	UDP	384	40421 → 53862 Len=342
56194	448.622492	10.0.0.21	10.0.0.20	UDP	384	40421 → 53862 Len=342
56201	448.824865	10.0.0.21	10.0.0.20	UDP	384	40421 → 53862 Len=342
56202	448.824893	10.0.0.21	10.0.0.20	UDP	384	40421 → 53862 Len=342
56548	455.367074	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
56966	459.847958	10.0.0.21	255.255.255.255	UDP	78	56700 → 56700 Len=36
58835	480.368637	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
60999	505.370404	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
62423	519.849923	10.0.0.21	255.255.255.255	UDP	78	56700 → 56700 Len=36
63376	530.372407	10.0.0.21	255.255.255.255	TPLINK-SMARTHOME/JSON	100	UDP Cmd: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
```

**Comment by JPersson77** [comment]
Hi again,

Can't say what is wrong from the log. I assume the columns are sorted in the standard order and sorted to only include packets from PC and TV. Try sorting it so that you see packets going to 10.0.0.21 from any IP.

**Comment by douglasparker** [comment]
> Hi again,
> 
> Can't say what is wrong from the log. I assume the columns are sorted in the standard order and filtered to include packets originating (source) from PC and TV. Try filtering it so that you see packets going to (destination) 10.0.0.21 (TV) from any IP.

I filtered for source OR destination with the IP being 10.0.0.21.

**Comment by JPersson77** [comment]
Then, assuming this is the full and relevant log, it looks like there are no packets to destination 10.0.0.21, port 3001 (on this network adapter) at the time of your issues.  The conclusion from this seem to be that the issues you are experiencing do not originate from some program (lgtv companion, home assistant, remote control app etc etc) on this PC (10.0.0.20) trying to establish communication with the WebOS API.

But it is still a possibility that wireshark did not capture relevant packets from other PCs/devices because of network equipment. For example with a simple unmanaged switch it may well not be possible to tap into the correct data on your main PC. 

So if you have managed switches maybe consider configuring port monitoring/mirroring for troubleshooting (i e mirror traffic from the port the TV is on to the port your PC is connected to). 

Another thing to try if you don't want to go that route- go into your ubiquity router configuration or the cloudkey/equivalent and check what devices are currently connected to your network. Try disconnecting them one by one and see how that affects the issue.

**Comment by JPersson77** [comment]
Hey, did you progress with this?

**Comment by douglasparker** [comment]
> Hey, did you progress with this?

I have not been able to figure this one out.

It will sometimes happen several times a day where I have to hit decline 10 or more times before it’ll go away.

Sometimes it doesn’t happen for a day or two and will then start popping up again.

I haven’t been having success blocking traffic from the firewall for some reason either.

Im personally on the verge of buying an actual monitor because the issues I am facing are incredibly disruptive.

**Comment by JPersson77** [comment]
Curious if you had any more luck with your issue? Guess we should close the github issue

**Comment by douglasparker** [comment]
The problem actually went away at some point.

The issue was just so extremely weird. The only thing I can think of is something on my home network was broadcasting something that was triggering the connection prompt on my TV. I have no idea what was doing it or why-

We can close this issue now. If anyone else has this problem or of it comes back we can always revisit and continue where we left off.

Thank you for your help and patience!
