### ISSUE TITLE
TV not turning on from sleep

### ISSUE THREAD

**Issue by gotoman00** [JPersson77/LGTVCompanion#202]
TV turns off when going into sleep mode but will not turn on when the PC resumes from standby.

The TV WILL turn off just fine from the Configure dropdown menu.

TV is a BX OLED, everything was working fine previously (before maybe a week or two ago).

Here is my log:

Thu 12:31:24 > LGTV Companion Service started (v 3.4.0) ---------------------------
Thu 12:31:24 > Data path: C:\ProgramData\LGTV Companion\
Thu 12:31:24 > Device1, [LG] webOS TV OLED55BXPUA, with IP 192.168.3.53 initiated (Enabled:yes, NewConn:yes, WOL:2, SubnetMask:255.255.255.0, PairingKey:ae21d0a080ae6d9bd82c2039d6ab9625, MAC: B4:B2:91:6C:4B:E9 , VerifyHdmiInput:off, SetHdmiInput:4, BlankOnIdle:on(10m))
Thu 12:31:24 > Restoring topology configuration: Device1:OFF 
Thu 12:31:24 > Host IP detected: 192.168.3.231/24
Thu 12:31:24 > Shutdown timing: default
Thu 12:31:24 > ** System requests displays ON.
Thu 12:31:24 > -daemon 1 started
Thu 12:31:24 > [IPC Daemon 1] Started.
Thu 12:31:32 > -daemon 1 topology invalid
Thu 12:31:32 > [IPC Daemon 1] A recent change to the system has invalidated the monitor topology configuration. Please run the configuration guide in the global options again to ensure correct operation.
Thu 12:39:08 > ** System requests displays OFF.
Thu 12:39:08 > Device1, spawning Thread_DisplayOff().
Thu 12:39:08 > Device1, [DEBUG] (SSL) OFF response 1: {"type":"registered","id":"register_0","payload":{"client-key":"ae21d0a080ae6d9bd82c2039d6ab9625"}}
Thu 12:39:08 > Device1, [DEBUG] (SSL) OFF response 2: {"type":"response","id":1,"payload":{"returnValue":true,"state":"Active"}}
Thu 12:39:08 > Device1, [DEBUG] (SSL) OFF response 4: {"type":"response","id":2,"payload":{"returnValue":true}}
Thu 12:39:08 > Device1, power state is: OFF.
Thu 12:39:09 > ** System is suspending to a low power state.(or event callback is missing)
Thu 14:34:07 > ** System resumed from low power state (Automatic).
Thu 14:34:07 > ** System resumed from low power state.
Thu 14:34:08 > ** System requests displays ON.
Thu 14:46:24 > -poweroff Device1
Thu 14:46:24 > [IPC] Force power OFF: Device1 
Thu 14:46:24 > Device1, spawning Thread_DisplayOff().
Thu 14:46:24 > Device1, [DEBUG] (SSL) OFF response 1: {"type":"registered","id":"register_0","payload":{"client-key":"ae21d0a080ae6d9bd82c2039d6ab9625"}}
Thu 14:46:24 > Device1, [DEBUG] (SSL) OFF response 2: {"type":"response","id":3,"payload":{"returnValue":true,"state":"Active"}}
Thu 14:46:24 > Device1, [DEBUG] (SSL) OFF response 4: {"type":"response","id":4,"payload":{"returnValue":true}}
Thu 14:46:24 > Device1, power state is: OFF.
Thu 14:46:29 > -poweron Device1
Thu 14:46:29 > [IPC] Force power ON: Device1 
Thu 14:46:29 > Device1, spawning Thread_DisplayOn().
Thu 14:46:29 > Device1, repeating WOL broadcast started to MAC: B4B2916C4BE9 using IP address: 192.168.3.53
Thu 14:46:29 > Device1, Best route to IP - interface index 13 LUID 1689399800627200 route protocol 2
Thu 14:46:30 > Device1, [DEBUG] (SSL) ON response 1: {"type":"registered","id":"register_0","payload":{"client-key":"ae21d0a080ae6d9bd82c2039d6ab9625"}}
Thu 14:46:30 > Device1, [DEBUG] (SSL) ON response 2: {"type":"error","id":5,"error":"500 Application error","payload":{"returnValue":false,"state":"Active","errorCode":"-102","errorText":"The current state must be 'Screen Off'"}}
Thu 14:46:30 > Device1, [DEBUG] (SSL) ON response 3: {"type":"response","id":6,"payload":{"returnValue":true,"state":"Active"}}
Thu 14:46:30 > Device1, power state is: ON
Thu 14:46:30 > Device1, repeating WOL broadcast ended
Thu 16:10:08 > SERVICE_CONTROL_INTERROGATE
Thu 17:16:42 > -daemon 1 useridle
Thu 17:16:42 > [IPC Daemon 1] User is idle.
Thu 17:26:42 > -daemon 1 useridle
Thu 17:36:42 > -daemon 1 useridle
Thu 17:46:42 > -daemon 1 useridle
Thu 17:56:42 > -daemon 1 useridle
Thu 18:06:42 > -daemon 1 useridle
Thu 18:10:08 > SERVICE_CONTROL_INTERROGATE
Thu 18:16:42 > -daemon 1 useridle
Thu 18:26:42 > -daemon 1 useridle
Thu 18:36:42 > -daemon 1 useridle
Thu 18:46:42 > -daemon 1 useridle
Thu 18:56:42 > -daemon 1 useridle
Thu 19:06:42 > -daemon 1 useridle
Thu 19:14:07 > -daemon 1 userbusy
Thu 19:14:07 > [IPC Daemon 1] User is not idle.
Thu 20:10:08 > SERVICE_CONTROL_INTERROGATE
Thu 20:53:28 > ** System requests displays OFF.
Thu 20:53:28 > Device1, spawning Thread_DisplayOff().
Thu 20:53:30 > ** System is suspending to a low power state.(or event callback is missing)
Thu 20:53:59 > ** System resumed from low power state.
Thu 20:53:59 > ** System resumed from low power state (Automatic).
Thu 20:54:00 > ** System requests displays ON.
Thu 20:54:13 > Device1, WARNING! Thread_DisplayOff(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Thu 20:55:12 > ** System requests displays OFF.
Thu 20:55:12 > Device1, spawning Thread_DisplayOff().
Thu 20:55:34 > Device1, WARNING! Thread_DisplayOff(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Thu 21:04:00 > -daemon 1 useridle
Thu 21:04:00 > [IPC Daemon 1] User is idle.
Thu 21:14:00 > -daemon 1 useridle
Thu 21:24:00 > -daemon 1 useridle
Thu 21:27:55 > ** System requests displays ON.
Thu 21:28:09 > ** System requests displays OFF.
Thu 21:28:09 > Device1, spawning Thread_DisplayOff().
Thu 21:28:09 > ** System is suspending to a low power state.(or event callback is missing)
Fri 07:29:46 > ** System resumed from low power state (Automatic).
Fri 07:29:46 > ** System resumed from low power state.
Fri 07:29:47 > ** System requests displays ON.
Fri 07:30:01 > Device1, WARNING! Thread_DisplayOff(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Fri 07:30:57 > ** System requests displays OFF.
Fri 07:30:57 > Device1, spawning Thread_DisplayOff().
Fri 07:31:18 > Device1, WARNING! Thread_DisplayOff(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Fri 07:39:47 > -daemon 1 useridle
Fri 07:49:47 > -daemon 1 useridle
Fri 07:59:47 > -daemon 1 useridle
Fri 08:09:47 > -daemon 1 useridle
Fri 08:12:05 > SERVICE_CONTROL_INTERROGATE
Fri 08:17:02 > ** System requests displays ON.
Fri 08:44:53 > Event subscription callback: System restart detected.
Fri 08:45:41 > ** System is restarting.
Fri 08:45:43 > The service terminated.

Fri 08:46:16 > LGTV Companion Service started (v 3.4.0) ---------------------------
Fri 08:46:16 > Data path: C:\ProgramData\LGTV Companion\
Fri 08:46:16 > Device1, [LG] webOS TV OLED55BXPUA, with IP 192.168.3.53 initiated (Enabled:yes, NewConn:yes, WOL:2, SubnetMask:255.255.255.0, PairingKey:ae21d0a080ae6d9bd82c2039d6ab9625, MAC: B4:B2:91:6C:4B:E9 , VerifyHdmiInput:off, SetHdmiInput:4, BlankOnIdle:on(10m))
Fri 08:46:16 > Restoring topology configuration: Device1:OFF 
Fri 08:46:16 > Host IP detected: 192.168.3.231/24
Fri 08:46:16 > Shutdown timing: default
Fri 08:46:16 > ** System requests displays ON.
Fri 08:47:22 > SERVICE_CONTROL_INTERROGATE
Fri 08:47:31 > -daemon 1 started
Fri 08:47:31 > [IPC Daemon 1] Started.
Fri 08:47:39 > -daemon 1 topology invalid
Fri 08:47:39 > [IPC Daemon 1] A recent change to the system has invalidated the monitor topology configuration. Please run the configuration guide in the global options again to ensure correct operation.
Fri 08:52:22 > SERVICE_CONTROL_INTERROGATE
Fri 09:37:52 > -daemon 1 useridle
Fri 09:37:52 > [IPC Daemon 1] User is idle.
Fri 09:40:34 > -daemon 1 userbusy
Fri 09:40:34 > [IPC Daemon 1] User is not idle.
Fri 10:28:09 > -daemon 1 useridle
Fri 10:28:09 > [IPC Daemon 1] User is idle.
Fri 10:38:09 > -daemon 1 useridle
Fri 10:48:09 > -daemon 1 useridle
Fri 10:51:53 > -daemon 1 userbusy
Fri 10:51:53 > [IPC Daemon 1] User is not idle.
Fri 10:52:22 > SERVICE_CONTROL_INTERROGATE
Fri 11:18:56 > ** System requests displays OFF.
Fri 11:18:56 > Device1, spawning Thread_DisplayOff().
Fri 11:18:56 > Device1, [DEBUG] (SSL) OFF response 1: {"type":"registered","id":"register_0","payload":{"client-key":"ae21d0a080ae6d9bd82c2039d6ab9625"}}
Fri 11:18:56 > Device1, [DEBUG] (SSL) OFF response 2: {"type":"response","id":1,"payload":{"returnValue":true,"state":"Active"}}
Fri 11:18:56 > Device1, [DEBUG] (SSL) OFF response 4: {"type":"response","id":2,"payload":{"returnValue":true}}
Fri 11:18:56 > Device1, power state is: OFF.
Fri 11:18:57 > ** System is suspending to a low power state.(or event callback is missing)
Fri 12:39:46 > ** System resumed from low power state (Automatic).
Fri 12:39:46 > ** System resumed from low power state.
Fri 12:39:47 > ** System requests displays ON.
Fri 14:13:07 > SERVICE_CONTROL_INTERROGATE
Fri 15:41:12 > -daemon 1 useridle
Fri 15:41:12 > [IPC Daemon 1] User is idle.
Fri 15:51:12 > -daemon 1 useridle
Fri 15:55:16 > -daemon 1 userbusy
Fri 15:55:16 > [IPC Daemon 1] User is not idle.
Fri 16:13:07 > SERVICE_CONTROL_INTERROGATE
Fri 17:25:25 > -daemon 1 useridle
Fri 17:25:25 > [IPC Daemon 1] User is idle.
Fri 17:35:25 > -daemon 1 useridle
Fri 17:41:02 > -daemon 1 userbusy
Fri 17:41:02 > [IPC Daemon 1] User is not idle.
Fri 18:13:07 > SERVICE_CONTROL_INTERROGATE
Fri 19:07:18 > ** System requests displays OFF.
Fri 19:07:18 > Device1, spawning Thread_DisplayOff().
Fri 19:07:18 > Device1, [DEBUG] (SSL) OFF response 1: {"type":"registered","id":"register_0","payload":{"client-key":"ae21d0a080ae6d9bd82c2039d6ab9625"}}
Fri 19:07:18 > Device1, [DEBUG] (SSL) OFF response 2: {"type":"response","id":3,"payload":{"returnValue":true,"state":"Active"}}
Fri 19:07:18 > Device1, [DEBUG] (SSL) OFF response 4: {"type":"response","id":4,"payload":{"returnValue":true}}
Fri 19:07:18 > Device1, power state is: OFF.
Fri 19:07:19 > ** System is suspending to a low power state.(or event callback is missing)
Fri 21:16:26 > ** System resumed from low power state (Automatic).
Fri 21:16:26 > ** System resumed from low power state.
Fri 21:16:27 > ** System requests displays ON.

**Comment by JPersson77** [comment]
Hi @gotoman00 I notice some weirdness (bug?) related to the monitor topology.I. e. this:

Fri 08:46:16 > Restoring topology configuration: Device1:OFF
...
Fri 08:47:39 > [IPC Daemon 1] A recent change to the system has invalidated the monitor topology configuration. Please run the configuration guide in the global options again to ensure correct operation.

Restoring the topology at boot (service start) like this will prevent the TV from turning on obviously. But then there is the warning message about invalidated monitor topology.

It does not seem to me that topology configuration should be restored if the configuration has been invalidated so I will have a look at that.

To resolve your issues you should probably reconfigure the topology configuration, i.e. run through the configuration guide again.

**Comment by gotoman00** [comment]
running the configuration again fixed it for me thanks

**Comment by JPersson77** [comment]
.. and I have patched a bug. Thanks for bringing it to attention!
