### ISSUE TITLE
Able to turn on monitor when pc starts up but when pc shutdowns, it goes to no signal screen.

### ISSUE THREAD

**Issue by aboutvin** [JPersson77/LGTVCompanion#203]
I have no issues with turning the PC on however, when I shutdown my PC. I kept getting the "no signal" input from the TV. I will appreciate any help here thank you!

**Comment by JPersson77** [comment]
Hi @aboutvin can you enable logging and paste the log and config.json here please. Both are in c:/programdata/lgtv companion/

**Comment by JPersson77** [comment]
in this particular log snippet a system restart was detected. For system restarts the TV should not power off.

If this wasn't a system restart the most likely error is misconfiguration. Can you please also paste your config.json ?

**Comment by JPersson77** [comment]
You need to uncheck "power off" and "shutdown" in the localised restart strings in global options to fix your issue.

Or install the latest version of the app which improves the implementation of this and will also resolve your iossue

**Comment by aboutvin** [comment]
The new version solved it! Thanks

**Comment by JPersson77** [comment]
Happy to hear it! :)
