### ISSUE TITLE
[FEATURE] Turn on TV after automatic TV shutdown

### ISSUE THREAD

**Issue by sjmikler** [JPersson77/LGTVCompanion#205]
Thanks for the program, it works well!

I have a feature request.

* I often have my PC running 24/7 doing some calculations
* I have energy saving settings set to TV turning off after 4 hours of inactivity to save some energy
* I am using "user idle mode" configured to trigger after 1 minute

My problem is: when I approach my PC after the night, the TV is always off because it automatically turned off to save energy. I need to use the remote to turn it on. My suggestion to solve this is to add a setting to send the wake-up signal when moving the mouse after PC spent a predefined amount of time in "user idle mode". I would set it to send a wake up signal if my PC spent at least 1 hour in "user idle mode". This way LGTVCompanion would turn on my TV after the night.

**Comment by JPersson77** [comment]
Hi there, thanks too. It already works this way. 

The likely culprit is that the TV lose network connectivity during the night. So maybe consider enable "always ready" if you have a C2 or newer, using a cable instead of wireless (if applicable). 

Please paste a log as well and I will have a look

**Comment by sjmikler** [comment]
[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/14741470/Log.txt)

What you said seems likely to me. Looks like LGCompanion tried to connect to TV last night but TV was not answering.

I have older A1 so I guess there's no way around it?

**Comment by JPersson77** [comment]
Running a cable usually helps really well if that is an option? Unless you already have.

Seems the built in wireless nic does not reconnect when the connection has been lost

**Comment by sjmikler** [comment]
I am not running the cable and that's not really an option for me.

If the problem is on the hardware side, I can deal with it I guess. Thanks, feel free to close the issue.
