### ISSUE TITLE
[FEATURE] Turn off the TV after set amount of time in idle mode

### ISSUE THREAD

**Issue by sjmikler** [JPersson77/LGTVCompanion#206]
Sorry if this was mentioned before / is already implemented, but I could not find it! 

I read somewhere that with the pixels off, LG TV can still draw ~40W of power or so. My TV usually stays long time with "user idle mode" active and automatic power off only triggers after 4 hours. I cannot shorten this time, because then it would be turning off when I am using it.

The solution would be to add an option for LGTVCompanion to turn off the TV after a predefined amount of time with "user idle mode" active. As for me, I think I would actually set it to a short time like 15 minutes. Obviously, LGTVCompanion would turn on the TV on mouse movement.

**Comment by JPersson77** [comment]
Hey,

I recommend you set the TV's auto power off from its 4 hours to "never" or at least for as long as your TV will allow you. Then instead rely on windows power management and LGTV Companion power management. 

I.e. enable the following:

1. User idle mode in the app (as you already have), which will blank the screen after X minutes, for example 5 minutes of idle user.

2. "Turn screen off after X minutes" in the windows power options. Set it to something longer, for example 30 minutes. This will power off the screen after 30 minutes of idle user.

Hope that helps

**Comment by sjmikler** [comment]
That would work if if Windows was turning the TV off. But it is only disabling the screen. This result in "HDMI no signal" message on the TV. Is this not expected behavior?

**Comment by JPersson77** [comment]
Yeah the TV should turn off. Can you please point to me to a timecode in a log where the TV should have powered off and I can review it. Either a new log or in the one you pasted in the other thread.

**Comment by sjmikler** [comment]
Huh, it actually works now, superb. But I don't get why it works.

When you set "turn screen off after X minutes" in Windows, the system shouldn't turn off your LG TV. 

Your app, LGTVCompanion is capable of turning off and turning on TV, because it communicates with LG TV using LG specific API. Windows does not do this, so it only stops sending signal to TV. Since TV stops receiving signal, it says "HDMI no signal".

So do you have built-in handling to detect when windows disables the screen and then you turn off the TV?

**Comment by JPersson77** [comment]
Yeah that is correct. The service component of the app listen for windows power events, including "turn screen off after x minutes" and subsequently power on off the managed devices accordingly. The original idea was to replicate, as close as possible, the behaviour of a traditional monitor. Then a few more things got added after that...

**Comment by sjmikler** [comment]
I see now, I made a wrong assumption here without testing properly, pardon me!

**Comment by JPersson77** [comment]
No worries mate. Thanks for your feedback
