### ISSUE TITLE
MacBook version

### ISSUE THREAD

**Issue by ParadoxicalEmboli** [JPersson77/LGTVCompanion#21]
Hi, I've been using this software for the past year or so with my PC and it has been amazing. I sometimes have my MacBook connected and would really appreciate an apple compatible version of this software. I realize Apple's restrictions are a possible challenge to overcome, but is it possible to make an apple version of this software?

**Comment by JPersson77** [comment]
Hi, it would be possible but require too much of an effort I'm afraid. As a potential makeshift solution you could try to piece together something similar by having your macbook trigger wakeonlan/etherwake on boot and on resume using a tool like Sleepwatcher. Similarly for macbook shutdown/sleep you  could also use Sleepwatcher to send the command code (see handshake.h) to the TV using netcat or similar.
