### ISSUE TITLE
LG C2 turns on via LAN, but doesn't detect my computer's input until I unplug/replug the HDMI cable.

### ISSUE THREAD

**Issue by brianmlatimer** [JPersson77/LGTVCompanion#212]
This seems to happen about 50% of the time I turn my computer on. It will just show the screensaver until I re-plug the HDMI. my PC seems to detect the TV however, so it is trying to display something on the C2.

![image](https://github.com/JPersson77/LGTVCompanion/assets/57278983/44df9f3e-9b58-4063-bdf0-2a1dcf24b549)
![image](https://github.com/JPersson77/LGTVCompanion/assets/57278983/a918cf2c-07de-4331-8132-604966bac20d)

**Comment by JPersson77** [comment]
Maybe you need to re-run the topology configuration. Please upload a log and I will have a look

**Comment by brianmlatimer** [comment]
[BadLog.txt](https://github.com/JPersson77/LGTVCompanion/files/15309423/BadLog.txt)
[DetectedInputLog.txt](https://github.com/JPersson77/LGTVCompanion/files/15309424/DetectedInputLog.txt)

Seems the issue is probably due to universal control detecting a "set top box" occasionally, and I have no idea how to disable this feature, as deleting it and disabling HDMI CEC seems to do nothing. I have no idea why it's detecting it.

**Comment by JPersson77** [comment]
The issue sounds unrelated to the app. However, did you try setting the input type to PC? What happens if you switch to another hdmi input and then back again?

**Comment by JPersson77** [comment]
hi @brianmlatimer any feedback on the suggestions above?

**Comment by JPersson77** [comment]
Closing due to missing feedback, please feel free to reopen as needed.
