### ISSUE TITLE
LG C2 wont turn on automatically with V4.0.0. 

### ISSUE THREAD

**Issue by Simkin84** [JPersson77/LGTVCompanion#213]
My LG C2 have been working great on all versions up until V4.0.0.

It does turn off, but not on anymore.

**Comment by JPersson77** [comment]
Please enable Debug level logging and paste a link here and I will have a look

**Comment by Simkin84** [comment]
[log.txt](https://github.com/JPersson77/LGTVCompanion/files/15369896/log.txt)

Here you go.

**Comment by JPersson77** [comment]
Thanks, if I understand the log correctly the display is not always properly powered on. I suspect that if you enable "keep topology on boot" it might start working -as a workaround. Let me know how that goes. If you can confirm i can push bugfix release shortly

**Comment by Simkin84** [comment]
Where do i find that option?

I only see "Support Windows multi monitor topology" and "Restore topology configuration immediately at logon screen"

Ticking the Restore topology did not help.

**Comment by JPersson77** [comment]
Allright, well, do I understand you correctly that the app can power on the TV, and does occasionally. But it does not do it specifically on cold boot/restart?

**Comment by JPersson77** [comment]
Please see if v4.0.1 helps the issue

**Comment by Simkin84** [comment]
4.0.1 fixed it.

Thanks!

**Comment by JPersson77** [comment]
Welcome! Thanks for reporting it!
