### ISSUE TITLE
C2 wont blank screen - daemon doesn't send useridle signals

### ISSUE THREAD

**Issue by camilalemes** [JPersson77/LGTVCompanion#216]
I started having issues with my TV, user idle options won't work.
It turns on and off with the PC, test works fine as well, but user idle does not.

Here are some of the logs I got when waiting for it to be idle, but it never did:

[Tue May 28 18:35:24][-I--][  System   ]  --- LGTV Companion Service has started (v 4.0.1) ---------------------------
[     .        .    ][D---][config.json]  {
[     .        .    ][D---][config.json]      "Device1": {
[     .        .    ][D---][config.json]          "Enabled": true,
[     .        .    ][D---][config.json]          "HDMIinputcontrol": true,
[     .        .    ][D---][config.json]          "IP": "192.168.1.245",
[     .        .    ][D---][config.json]          "MAC": [
[     .        .    ][D---][config.json]              "{hidden mac}"
[     .        .    ][D---][config.json]          ],
[     .        .    ][D---][config.json]          "Name": "LG C2",
[     .        .    ][D---][config.json]          "NewSockConnect": true,
[     .        .    ][D---][config.json]          "OnlyTurnOffIfCurrentHDMIInputNumberIs": 1,
[     .        .    ][D---][config.json]          "PersistentConnectionLevel": 0,
[     .        .    ][D---][config.json]          "SessionKey": "913759750ede226306e9e31bbf61881a",
[     .        .    ][D---][config.json]          "SetHDMIInputOnResume": true,
[     .        .    ][D---][config.json]          "SetHDMIInputOnResumeToNumber": 1,
[     .        .    ][D---][config.json]          "Subnet": "255.255.255.0",
[     .        .    ][D---][config.json]          "WOL": 2
[     .        .    ][D---][config.json]      },
[     .        .    ][D---][config.json]      "LGTV Companion": {
[     .        .    ][D---][config.json]          "AdhereDisplayTopology": false,
[     .        .    ][D---][config.json]          "AutoUpdate": true,
[     .        .    ][D---][config.json]          "BlankWhenIdle": true,
[     .        .    ][D---][config.json]          "BlankWhenIdleDelay": 1,
[     .        .    ][D---][config.json]          "ExternalAPI": false,
[     .        .    ][D---][config.json]          "IdleFsExclusionsEnabled": false,
[     .        .    ][D---][config.json]          "IdleFullscreen": true,
[     .        .    ][D---][config.json]          "IdleWhiteListEnabled": false,
[     .        .    ][D---][config.json]          "KeepTopologyOnBoot": false,
[     .        .    ][D---][config.json]          "LogLevel": 4,
[     .        .    ][D---][config.json]          "MuteSpeakers": false,
[     .        .    ][D---][config.json]          "PowerOnTimeOut": 40,
[     .        .    ][D---][config.json]          "RemoteStream": false,
[     .        .    ][D---][config.json]          "RemoteStreamPowerOff": true,
[     .        .    ][D---][config.json]          "TimingPreshutdown": false,
[     .        .    ][D---][config.json]          "Version": 3
[     .        .    ][D---][config.json]      }
[     .        .    ][D---][config.json]  }
[     .        .    ][D---][  System   ]  Host IP: 192.168.1.133/24 
[     .        .    ][-I--][    PWR    ]  *** System requests displays to power on
[     .        .    ][D---][   LG C2   ]  Enqueueing work of type: 1
[     .        .    ][D---][   LG C2   ]  Enqueueing work of type: 4
[     .        .    ][D---][  System   ]  Creating a new thread pool - 2 threads
[     .        .    ][D---][   LG C2   ]  ---  Starting work: POWER ON  -----------------
[     .        .    ][D---][   LG C2   ]  > > > SEND > > >: [webOS handshake]
[     .        .    ][D---][   LG C2   ]  < < < RECV < < <: {"type":"registered","id":"register_0","payload":{"client-key":"913759750ede226306e9e31bbf61881a"}}
[     .        .    ][D---][   LG C2   ]  > > > SEND > > >: {"type":"request","id":"getPowerState","uri":"ssap://com.webos.service.tvpower/power/getPowerState","payload":{}}
[     .        .    ][D---][   LG C2   ]  ARP override best source: 192.168.1.133, Interface index: 15, LUID: 19985273102270464, Route protocol: 2
[     .        .    ][D---][   LG C2   ]  WOL-tastic packet > 192.168.1.245    - OK
[     .        .    ][D---][   LG C2   ]  < < < RECV < < <: {"type":"response","id":"getPowerState","payload":{"state":"Active","returnValue":true}}
[     .        .    ][-I--][   LG C2   ]  Power state is ON
[     .        .    ][D---][   LG C2   ]  ---  Starting work: REQUEST  -----------------
[     .        .    ][D---][   LG C2   ]  > > > SEND > > >: {"id":"request","payload":{"id":"com.webos.app.hdmi1"},"type":"request","uri":"ssap://system.launcher/launch"}
[     .        .    ][D---][    IPC    ]  Received IPC/CLI: -daemon 2 started
[     .        .    ][D---][ Daemon 2  ]  Daemon started!
[     .        .    ][D---][   LG C2   ]  < < < RECV < < <: {"type":"response","id":"request","payload":{"returnValue":true,"id":"com.webos.app.hdmi1","sessionId":"Y29tLndlYm9zLmFwcC5oZG1pMQ=="}}
[     .        .    ][-I--][   LG C2   ]  set hdmi-input [1]
[     .        .    ][D---][   LG C2   ]  Work queue is empty
[     .        .    ][D---][   LG C2   ]  Closing connection
[     .        .    ][D---][   LG C2   ]  Socket closed gracefully
[     .        .    ][D---][   LG C2   ]  The I/O operation has been aborted because of either a thread exit or an application request (onRead)

I tried everything, even comparing the configurations with other people that have this working fine.
Please, help!

**Comment by JPersson77** [comment]
Hi @camilalemes can you try executing lgtvdaemon.exe -show in the install dir. This will show the daemon status qi Dow which will provide additional info to what is going wrong

**Comment by camilalemes** [comment]
> Hi @camilalemes can you try executing lgtvdaemon.exe -show in the install dir. This will show the daemon status window which will provide additional info to what is going wrong

Here it is, it looks normal, I think

![image](https://github.com/JPersson77/LGTVCompanion/assets/50663511/a9fa8004-c7c9-48c3-a6a9-94a4e558c1e1)

**Comment by JPersson77** [comment]
The fact that the counter remain on 0 is the culprit. Now we need to figure out why. Some controllers will cause this. Ehat have you not unplugged?

**Comment by camilalemes** [comment]
> The fact that the counter remain on 0 is the culprit. Now we need to figure out why. Some controllers will cause this. Ehat have you not unplugged?

I unplugged everything, even the usb plug for my Xbox controller, I can try removing and uninstalling the driver

**Comment by JPersson77** [comment]
That is great! Thanks too :)
