### ISSUE TITLE
Speakers not unmuting after screen sleep followed by computer sleep. 

### ISSUE THREAD

**Issue by anonacon** [JPersson77/LGTVCompanion#217]
If mute built in speakers is enabled 
AND
Screen goes to sleep
AND
Computer goes to sleep while screen is asleep

When the computer is woken from sleep, and screen turns back on, build in speakers do not unmute themselves.

Adjusting volume on the computer does not unmute speakers, only adjusting volume on the TV itself unmutes them.

I didn't have this issue before, I've tried rolling back to a previous issue but the problem persists...

Any ideas?

Thanks

**Comment by JPersson77** [comment]
Hi @anonacon yes I can reproduce this behaviour on v4.0.1 so expect a fix in next version. Thanks for reporting!

**Comment by anonacon** [comment]
@JPersson77 Thanks for looking into it. 

First of all, this:
I didn't have this issue before, I've tried rolling back to a previous issue but the problem persists...
Was supposed to read, this:
I didn't have this issue before, I've tried rolling back to a previous **version** but the problem persists...

Not sure if it is an LG update causing the issue. 

Also, I've just had it happen when the computer hadn't gone to sleep, perhaps an intermittent issue.

I'm using an LG C2.

Here is the log for the event that didn't unmute (I've redacted a few bits of information so any -'s you see are done by me)

> Mon 21:17:48 > -daemon 1 userbusy
> Mon 21:17:48 > [IPC Daemon 1] User is not idle.
> Mon 21:17:48 > Device2, spawning Thread_DisplayOn().
> Mon 21:17:48 > Device2, repeating WOL broadcast started to MAC: - using broadcast address: -
> Mon 21:17:48 > Device2, [DEBUG] (SSL) ON response 1: {"type":"registered","id":"register_0","payload":{"client-key":"-"}}
> Mon 21:17:48 > Device2, [DEBUG] (SSL) ON response 2: {"type":"response","id":13,"payload":{"returnValue":true,"state":"Active"}}
> Mon 21:17:48 > Device2, [DEBUG] (SSL) ON response 3: {"type":"response","id":14,"payload":{"state":"Active","returnValue":true}}
> Mon 21:17:48 > Device2, power state is: ON
> Mon 21:17:48 > Device2, [DEBUG] (SSL) ON response 4: {"type":"response","id":15,"payload":{"returnValue":true,"muteStatus":false,"soundOutput":"external_arc"}}
> Mon 21:17:49 > Device2, repeating WOL broadcast ended

So there is clearly a call to change muteStatus to false but it's not registering... perhaps it's attempting it too soon?

Cheers.

**Comment by JPersson77** [comment]
I hope the next release will fix your issue. I've added a check for the current status and then unmuting if it is muted

**Comment by anonacon** [comment]
@JPersson77, okay great. I've just downloaded. I'll keep an eye on it. 

I won't be that active on my computer until Friday but by the end of the weekend will definitely have a good idea. 

Thanks for your support.

**Comment by JPersson77** [comment]
Assuming this is resolved. Please feel free to reopen  as needed

**Comment by anonacon** [comment]
Yes, fix is great. Sorry for the long reply have been away and now at a festival. Was meaning to get back tomorrow but all bueno now. Regards,Benjamin. On 16 Jun 2024, at 19:40, JPersson77 ***@***.***> wrote:﻿
Closed #217 as completed.

**Comment by JPersson77** [comment]
No worries mate! Happy it works! Hope the festival is treating you nicely :)
