### ISSUE TITLE
LG Companion without router access

### ISSUE THREAD

**Issue by MAKaral27** [JPersson77/LGTVCompanion#219]
I live at a student residence, and as such, I don't have access to the network configuration. Is there any way to bypass this by using LG Companion by Bluetooth or something of the like? Would be awesome to get it up and running for my C2 and cheers anyway for taking the time to read the request:))

**Comment by dechamps** [comment]
You shouldn't need to touch the network configuration to get LGTV Companion working. It should work out of the box as long as the TV and the PC are on the same subnet (and the router does not explicitly block client-to-client communication), which may very well be the case already. Have you tried it?
