### ISSUE TITLE
Power off command putting LG E9 into unrecoverable black screen state

### ISSUE THREAD

**Issue by apranda** [JPersson77/LGTVCompanion#221]
I am using a single monitor setup with a 2019 LG E9.

On releases before 4.0, screen was able to be turned on and off normally. When turned off, the internal relay clicked and the standby light was illuminated. On release 4.0.3, the power off command causes the screen to go blank, but the internal relay does not click and the standby light does not come on. Furthermore, the TV becomes frozen in this state and cannot be powered on via the PC or remote. The TV can only be recovered by pressing the power button on the remote, which causes the relay to click and the standby light to come on. After this point, it again is able to respond to commands from the PC.

` 
[Fri Jun 07 09:36:10][-I--][  System   ]  --- LGTV Companion Service has started (v 4.0.3) ---------------------------
[     .        .    ][D---][config.json]  {
[     .        .    ][D---][config.json]      "Device1": {
[     .        .    ][D---][config.json]          "Enabled": false,
[     .        .    ][D---][config.json]          "HDMIinputcontrol": true,
[     .        .    ][D---][config.json]          "IP": "192.168.1.10",
[     .        .    ][D---][config.json]          "MAC": [
[     .        .    ][D---][config.json]              "0C:8E:29:C5:1C:82"
[     .        .    ][D---][config.json]          ],
[     .        .    ][D---][config.json]          "Name": "LG E9",
[     .        .    ][D---][config.json]          "NewSockConnect": false,
[     .        .    ][D---][config.json]          "OnlyTurnOffIfCurrentHDMIInputNumberIs": 4,
[     .        .    ][D---][config.json]          "PersistentConnectionLevel": 0,
[     .        .    ][D---][config.json]          "SessionKey": "7d7910f0216f86e594b22c9eb43a8b50",
[     .        .    ][D---][config.json]          "SetHDMIInputOnResume": true,
[     .        .    ][D---][config.json]          "SetHDMIInputOnResumeToNumber": 4,
[     .        .    ][D---][config.json]          "Subnet": "255.255.255.0",
[     .        .    ][D---][config.json]          "WOL": 4
[     .        .    ][D---][config.json]      },
[     .        .    ][D---][config.json]      "LGTV Companion": {
[     .        .    ][D---][config.json]          "AdhereDisplayTopology": false,
[     .        .    ][D---][config.json]          "AutoUpdate": true,
[     .        .    ][D---][config.json]          "BlankWhenIdle": false,
[     .        .    ][D---][config.json]          "BlankWhenIdleDelay": 10,
[     .        .    ][D---][config.json]          "ExternalAPI": false,
[     .        .    ][D---][config.json]          "IdleFsExclusionsEnabled": false,
[     .        .    ][D---][config.json]          "IdleFullscreen": false,
[     .        .    ][D---][config.json]          "IdleWhiteListEnabled": false,
[     .        .    ][D---][config.json]          "KeepTopologyOnBoot": false,
[     .        .    ][D---][config.json]          "LogLevel": 4,
[     .        .    ][D---][config.json]          "MuteSpeakers": false,
[     .        .    ][D---][config.json]          "PowerOnTimeOut": 40,
[     .        .    ][D---][config.json]          "RemoteStream": false,
[     .        .    ][D---][config.json]          "RemoteStreamPowerOff": true,
[     .        .    ][D---][config.json]          "TimingPreshutdown": false,
[     .        .    ][D---][config.json]          "Version": 3
[     .        .    ][D---][config.json]      }
[     .        .    ][D---][config.json]  }
[     .        .    ][D---][  System   ]  Host IP: 192.168.1.134/24 
[     .        .    ][-I--][    PWR    ]  *** System requests displays to power on
[     .        .    ][D---][    IPC    ]  Received IPC/CLI: -daemon 2 started
[     .        .    ][D---][ Daemon 2  ]  Daemon started!
[     .     09:36:22][-I--][  System   ]  The service has terminated
 
[Fri Jun 07 09:36:22][-I--][  System   ]  --- LGTV Companion Service has started (v 4.0.3) ---------------------------
[     .        .    ][D---][config.json]  {
[     .        .    ][D---][config.json]      "Device1": {
[     .        .    ][D---][config.json]          "Enabled": true,
[     .        .    ][D---][config.json]          "HDMIinputcontrol": true,
[     .        .    ][D---][config.json]          "IP": "192.168.1.10",
[     .        .    ][D---][config.json]          "MAC": [
[     .        .    ][D---][config.json]              "0C:8E:29:C5:1C:82"
[     .        .    ][D---][config.json]          ],
[     .        .    ][D---][config.json]          "Name": "LG E9",
[     .        .    ][D---][config.json]          "NewSockConnect": false,
[     .        .    ][D---][config.json]          "OnlyTurnOffIfCurrentHDMIInputNumberIs": 4,
[     .        .    ][D---][config.json]          "PersistentConnectionLevel": 0,
[     .        .    ][D---][config.json]          "SessionKey": "7d7910f0216f86e594b22c9eb43a8b50",
[     .        .    ][D---][config.json]          "SetHDMIInputOnResume": true,
[     .        .    ][D---][config.json]          "SetHDMIInputOnResumeToNumber": 4,
[     .        .    ][D---][config.json]          "Subnet": "255.255.255.0",
[     .        .    ][D---][config.json]          "WOL": 4
[     .        .    ][D---][config.json]      },
[     .        .    ][D---][config.json]      "LGTV Companion": {
[     .        .    ][D---][config.json]          "AdhereDisplayTopology": false,
[     .        .    ][D---][config.json]          "AutoUpdate": true,
[     .        .    ][D---][config.json]          "BlankWhenIdle": false,
[     .        .    ][D---][config.json]          "BlankWhenIdleDelay": 10,
[     .        .    ][D---][config.json]          "ExternalAPI": false,
[     .        .    ][D---][config.json]          "IdleFsExclusionsEnabled": false,
[     .        .    ][D---][config.json]          "IdleFullscreen": false,
[     .        .    ][D---][config.json]          "IdleWhiteListEnabled": false,
[     .        .    ][D---][config.json]          "KeepTopologyOnBoot": false,
[     .        .    ][D---][config.json]          "LogLevel": 4,
[     .        .    ][D---][config.json]          "MuteSpeakers": false,
[     .        .    ][D---][config.json]          "PowerOnTimeOut": 40,
[     .        .    ][D---][config.json]          "RemoteStream": false,
[     .        .    ][D---][config.json]          "RemoteStreamPowerOff": true,
[     .        .    ][D---][config.json]          "TimingPreshutdown": false,
[     .        .    ][D---][config.json]          "Version": 3
[     .        .    ][D---][config.json]      }
[     .        .    ][D---][config.json]  }
[     .        .    ][D---][  System   ]  Host IP: 192.168.1.134/24 
[     .        .    ][-I--][    PWR    ]  *** System requests displays to power on
[     .        .    ][D---][   LG E9   ]  Enqueueing work of type: 1
[     .        .    ][D---][   LG E9   ]  Enqueueing work of type: 4
[     .        .    ][D---][  System   ]  Creating a new thread pool - 2 threads
[     .        .    ][D---][   LG E9   ]  ---  Starting work: POWER ON  -----------------
[     .     09:36:23][D---][   LG E9   ]  > > > SEND (non-ssl) > > >: [webOS handshake]
[     .        .    ][D---][    IPC    ]  Received IPC/CLI: -daemon 2 started
[     .        .    ][D---][ Daemon 2  ]  Daemon started!
[     .        .    ][D---][   LG E9   ]  < < < RECV (non-ssl) < < <: {"type":"registered","id":"register_0","payload":{"client-key":"7d7910f0216f86e594b22c9eb43a8b50"}}
[     .        .    ][D---][   LG E9   ]  > > > SEND (non-ssl) > > >: {"type":"request","id":"getPowerState","uri":"ssap://com.webos.service.tvpower/power/getPowerState","payload":{}}
[     .        .    ][D---][   LG E9   ]  < < < RECV (non-ssl) < < <: {"type":"response","id":"getPowerState","payload":{"returnValue":true,"state":"Active"}}
[     .        .    ][-I--][   LG E9   ]  Power state is ON
[     .        .    ][D---][   LG E9   ]  ---  Starting work: REQUEST  -----------------
[     .        .    ][D---][   LG E9   ]  > > > SEND (non-ssl) > > >: {"id":"request","payload":{"id":"com.webos.app.hdmi4"},"type":"request","uri":"ssap://system.launcher/launch"}
[     .        .    ][D---][   LG E9   ]  < < < RECV (non-ssl) < < <: {"type":"response","id":"request","payload":{"returnValue":true,"id":"com.webos.app.hdmi4","sessionId":"Y29tLndlYm9zLmFwcC5oZG1pNA=="}}
[     .        .    ][-I--][   LG E9   ]  set hdmi-input [4]
[     .        .    ][D---][   LG E9   ]  Work queue is empty
[     .        .    ][D---][   LG E9   ]  Closing connection
[     .        .    ][D---][   LG E9   ]  Socket closed gracefully
[     .        .    ][D---][   LG E9   ]  The I/O operation has been aborted because of either a thread exit or an application request (onRead)
[     .     09:36:43][D---][    IPC    ]  Received IPC/CLI: -poweroff Device1
[     .        .    ][-I--][    CLI    ]  Force power off: Device1 
[     .        .    ][D---][  System   ]  I/O context was stopped. Resetting!
[     .        .    ][D---][   LG E9   ]  Enqueueing work of type: 2
[     .        .    ][D---][  System   ]  Creating a new thread pool - 2 threads
[     .        .    ][D---][   LG E9   ]  ---  Starting work: POWER OFF  -----------------
[     .        .    ][D---][   LG E9   ]  > > > SEND (non-ssl) > > >: [webOS handshake]
[     .        .    ][D---][   LG E9   ]  < < < RECV (non-ssl) < < <: {"type":"registered","id":"register_0","payload":{"client-key":"7d7910f0216f86e594b22c9eb43a8b50"}}
[     .        .    ][D---][   LG E9   ]  > > > SEND (non-ssl) > > >: {"type":"request","id":"getPowerState","uri":"ssap://com.webos.service.tvpower/power/getPowerState","payload":{}}
[     .        .    ][D---][   LG E9   ]  < < < RECV (non-ssl) < < <: {"type":"response","id":"getPowerState","payload":{"returnValue":true,"state":"Active"}}
[     .        .    ][D---][   LG E9   ]  > > > SEND (non-ssl) > > >: {"type":"request","id":"powerToggle","uri":"ssap://system/turnOff","payload":{}}
[     .        .    ][D---][   LG E9   ]  < < < RECV (non-ssl) < < <: {"type":"response","id":"powerToggle","payload":{"returnValue":true}}
[     .        .    ][-I--][   LG E9   ]  Power state is OFF
[     .        .    ][D---][   LG E9   ]  Work queue is empty
[     .        .    ][D---][   LG E9   ]  Closing connection
[     .     09:37:13][D---][   LG E9   ]  The file handle supplied is not valid (onClose)
[     .        .    ][D---][   LG E9   ]  The socket was closed due to a timeout (onRead)
[     .     09:37:39][D---][    IPC    ]  Received IPC/CLI: -poweron Device1
[     .        .    ][-I--][    CLI    ]  Force power on: Device1 
[     .        .    ][D---][  System   ]  I/O context was stopped. Resetting!
[     .        .    ][D---][   LG E9   ]  Enqueueing work of type: 1
[     .        .    ][D---][  System   ]  Creating a new thread pool - 2 threads
[     .        .    ][D---][   LG E9   ]  ---  Starting work: POWER ON  -----------------
[     .        .    ][D---][   LG E9   ]  ARP override best source: 192.168.1.134, Interface index: 13, LUID: 19985273152602112, Route protocol: 2
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:40][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:41][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:42][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:43][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:44][D---][   LG E9   ]  The socket was closed due to a timeout (onConnect)
[     .        .    ][D---][   LG E9   ]  Retrying connection...
[     .        .    ][D---][   LG E9   ]  Magic packets (WOL) are already being sent out
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:45][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:46][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:47][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:48][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:49][D---][   LG E9   ]  The socket was closed due to a timeout (onConnect)
[     .        .    ][D---][   LG E9   ]  Retrying connection...
[     .        .    ][D---][   LG E9   ]  Magic packets (WOL) are already being sent out
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:50][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:51][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:52][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:53][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:54][D---][   LG E9   ]  The socket was closed due to a timeout (onConnect)
[     .        .    ][D---][   LG E9   ]  Retrying connection...
[     .        .    ][D---][   LG E9   ]  Magic packets (WOL) are already being sent out
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:55][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:56][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:57][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:58][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:37:59][D---][   LG E9   ]  The socket was closed due to a timeout (onConnect)
[     .        .    ][D---][   LG E9   ]  Retrying connection...
[     .        .    ][D---][   LG E9   ]  Magic packets (WOL) are already being sent out
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:00][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:01][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:02][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:03][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:04][D---][   LG E9   ]  The socket was closed due to a timeout (onConnect)
[     .        .    ][D---][   LG E9   ]  Retrying connection...
[     .        .    ][D---][   LG E9   ]  Magic packets (WOL) are already being sent out
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:05][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:06][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:07][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:08][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:09][D---][   LG E9   ]  The socket was closed due to a timeout (onConnect)
[     .        .    ][D---][   LG E9   ]  Retrying connection...
[     .        .    ][D---][   LG E9   ]  Magic packets (WOL) are already being sent out
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:10][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:11][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:12][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:13][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:14][D---][   LG E9   ]  The socket was closed due to a timeout (onConnect)
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .        .    ][D---][   LG E9   ]  Retrying connection...
[     .        .    ][D---][   LG E9   ]  Magic packets (WOL) are already being sent out
[     .     09:38:15][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:16][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:17][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:18][D---][   LG E9   ]  WOL-tastic packet > 255.255.255.255  - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.10     - OK
[     .        .    ][D---][   LG E9   ]  WOL-tastic packet > 192.168.1.255    - OK
[     .     09:38:19][D---][   LG E9   ]  The socket was closed due to a timeout (onConnect)
[     .        .    ][--W-][   LG E9   ]  Finished retrying connection
[     .        .    ][D---][   LG E9   ]  Work queue is empty
[     .        .    ][D---][   LG E9   ]  Closing connection. Socket is already closed
`

**Comment by apranda** [comment]
I just verified that this behavior persists even if I downgrade to 3.5, so it looks like a recent TV firmware upgrade has impacted the response to the power off command. The current TV firmware version is 5.40.35

**Comment by JPersson77** [comment]
Hi, I'm wondering if maybe a pixel cleaning is going on? Have you tried waiting some time to see if it corrects itself?

**Comment by apranda** [comment]
> Hi, I'm wondering if maybe a pixel cleaning is going on? Have you tried waiting some time to see if it corrects itself?
> 
> Edit: do you get the same behaviour if you run this command in a command prompt in the install dir: `"LGTV Companion.exe" -request system/turnOff`

I left the TV in the unresponsive state for 3 hours in case it was doing a pixel refresh, but the TV did not recover.

Running the command results in the TV to go into the unresponsive state. The TV is only able to go into a normal standby state by using the remote.

**Comment by JPersson77** [comment]
Not sure why this would happen for you. First I've heard of the issue. How does a virtual button press (-button POWER) work for you?  Can you try using SSL on the TV (put connection method to auto from legacy). Just trying to gather info.

**Comment by apranda** [comment]
> Not sure why this would happen for you. First I've heard of the issue. How does a virtual button press (-button POWER) work for you? Can you try using SSL on the TV (put connection method to auto from legacy). Have you tried pulling the power cord of the TV? Just trying to gather info.

It looks like some kind of firmware bug. I was able to recover normal behavior by reducing my display output from 4K 120Hz HDR to 4K 60Hz SDR. Interestingly enough, normal behavior is maintained if I go back to 120Hz HDR! I did also recently update to Windows 11 24H2 so who knows if that did something too.

**Comment by apranda** [comment]
Well I jumped the gun there. Unresponsive again at 4K 120Hz HDR after 5min.

**Comment by apranda** [comment]
Closing this issue now since I can confirm the root cause is the TV. Turning off the TV with the app  **or with the remote** when the refresh rate is set to 120Hz will cause it to go into the unresponsive state. Refresh rates below 120Hz function normally.
