### ISSUE TITLE
[BUG] Unable to start topology configuration

### ISSUE THREAD

**Issue by maqzek** [JPersson77/LGTVCompanion#222]
## Describe the bug

Unable to initiate topology configuration. Status says Not configured, steps 5 and 6 are greyed out, clicking start pops up a window with "No WebOS devices detected. To configure your devices, ..."

#### What I've tried:
+ Uninstalling and installing the app
+ Installing 3.5 version
+ Clearing config.json
+ Restarting TV, turning off other displays
+ Trying with different Quick Start+, Always Ready combinations
+ Changing FriendlyNames, removing them, adding them to other subkeys (results in companion finding 2nd device with null ip)

## How to reproduce the bug?

It might've been after I renamed TV in device manager with FriendlyName method with regedit. I noticed this feature was off after quite some time, so many factors could be at play.

## What was the expected behavior

Self-explanatory.

## What is your system?

Win 10 22H2, build 19045.4412
LG OLED C2, WebOS 23 13.30.56, (TV Version 8.3.0-2301)

## Log file and screenshots

![Screenshot](https://i.imgur.com/WfPl743.png)

Log: https://www.prcl.dev/51c2wx3d2ac3rqg
Config: https://www.prcl.dev/5ar0iytp80xgmg9

**Comment by JPersson77** [comment]
Hi @maqzek thanks for the detailed bug report. You are already on to the explanation for this issue. Below is the relevant code snippet that fails unexpectedly when the device friendly name has been changed:

`if (FriendlyName.find(L"lg tv") != std::wstring::npos)`

So as you see "lg tv" is hardcoded, which is fine for all situations except when the user has manually changed the friendly name. It's not difficult to allow for a user configurable option but it will add complexity (for the user). I'll see if I can make this matching functionality smarter.

For now the workaround is to ensure that the "lg tv" is a substring of the friendly name

**Comment by JPersson77** [comment]
Different things. Please see the screenshot below. #1 can be anything, #2 must contain "[LG]" for the scan to work and #3 must contain "LG TV" for the topology feature to work

![image](https://github.com/JPersson77/LGTVCompanion/assets/77928210/9d2bb385-a748-4ae8-b168-218dc52a80c8)

**Comment by JPersson77** [comment]
Looks allright I think. Probably need then to add a few lines of debug code to understand what is going wrong. Are you on discord? PM me please

**Comment by JPersson77** [comment]
Excellent @maqzek thanks! 👍
