### ISSUE TITLE
[OTH] Do we have automatic CEC HDMI port switch feature?

### ISSUE THREAD

**Issue by Cr4z33** [JPersson77/LGTVCompanion#229]
I was sure I saw this feature in the past, but now I can't? 🤔

Basically all I need is automatic HDMI switch to port xx when the computer starts.

**Comment by JPersson77** [comment]
hi @Cr4z33 there is no CEC, but the app can set the hdmi input on startup with this: 
![image](https://github.com/user-attachments/assets/46004b28-2e59-46b9-90fa-993a15acb40a)

**Comment by Cr4z33** [comment]
That!

I was wrongly remembering the feature thanks!
