### ISSUE TITLE
 Change HDMI input to PC when PC has already turned on instead of wake from sleep/hibernate or off (Feature)

### ISSUE THREAD

**Issue by WilliamLeGod** [JPersson77/LGTVCompanion#23]
Example from PS5:
 - Ps5 is ON/Hdmi 2, PC is on Hdmi 1, when TV is at Hdmi 1, press the PS button on ps5 controller, TV will switch to Hdmi 2 (Ps5)

Is this possible to do this for PC by let's say making a shortcut or exe for whenever triggering it, it will do the exact same behavior like on the Ps5 controller (Can just set such shortcut/exe to a button on the pc controller)

Thanks for your hard work!

**Comment by JPersson77** [comment]
Hi,

That is possible, by using the command line. The following will switch input for Device1 to HDMI1:

Create a shortcut/script/macro pointing at executing: <install directory>\LGTV Companion.exe -sethdmi1 Device1

Full reference for the command line parameters can be found in the [readme](https://github.com/JPersson77/LGTVCompanion#readme)

**Comment by WilliamLeGod** [comment]
> Hi,
> 
> That is possible, by using the command line. The following will switch input for Device1 to HDMI1:
> 
> Create a shortcut/script/macro pointing at executing: c:\program files\LGTV Companion\LGTV Companion.exe -sethdmi1 Device1
> 
> Full reference for the command line parameters can be found in the [readme](https://github.com/JPersson77/LGTVCompanion#readme)

It works! Thank you so much!
