### ISSUE TITLE
[OTH] Winget installer stuck on v3.4.0

### ISSUE THREAD

**Issue by theiam79** [JPersson77/LGTVCompanion#230]
Any interest in adding Winget releases to the release pipeline so that they stay current with the project? I have more experience with Azure Pipelines than Github, but found this repo that might be of interest

https://github.com/vedantmgoyal9/winget-releaser

**Comment by JPersson77** [comment]
Yes for sure! I will have a look. Thanks for the relecant link

**Comment by JPersson77** [comment]
Workflow added using winget-releaser and PR submitted for v4.1.0. Closing issue.
