### ISSUE TITLE
[OTH] External KVM support / question

### ISSUE THREAD

**Issue by hakamairi** [JPersson77/LGTVCompanion#244]
I have the following setup. LG C4 connected to external KVM on HDMI 4, external KVM switches between a PC and a laptop.
I've installed and configured LGTVCompanion on both devices.

The issue is that when one goes to sleep after switching then it turns off the TV off as well, the one currently connected is not handling this in any way.

I think it's more or less similar to https://github.com/JPersson77/LGTVCompanion/issues/158 but I'm not quite sure, hence the new issue created.

Is this setup anyhow supported? How could I configure LGTVCompanion to have it working without interruptions?

**Comment by JPersson77** [comment]
Hi, 

Yeah it is not straightforward. By default the two apps will send power commands to the TV based on the power state of the PC, regardless of whether the TV is connected via HDMI.

The Multi monitor support option in the app  will recognise when a TV is attached/detached from the active desktop and turn the TV on/off respectively, but it's still a conflict between the two apps.

So the most straightforeard way is probably to ensure that automatic management of the TV is only enabled on the laptop or the stationary, exclusively.

This can be done manually, via the gui or a script. 

Or it can be done automatically, by having a script running on both PCs to detect the presence of certain usb accessorirs (mouse/keyboard) and/or HDMI devices and toggle automatic management in the app on/off respectively.

Let me know your thoughts

**Comment by hakamairi** [comment]
Hi,
Thanks for your quick answer. Any examples or pointers how such script would look like? If that works for me I'm happy to share to have it as example for others in the same situation.

**Comment by JPersson77** [comment]
I usually point towardd autohotkey scripts but it can be done in other scripting language Rio ofcourse. It involves hooking a windows message and parking the results for the correct device id and then send the appropriate command line to lgtv companion

Here is a discussion on how to run X when usb device Y is detected as a start

https://www.autohotkey.com/boards/viewtopic.php?t=98931

Let me know on how you would like to proceed  from here and I can probably help

**Comment by JPersson77** [comment]
Closing the issue due to missing feedback. Please feel free to reopen as needed
