### ISSUE TITLE
[BUG] TV doesn't turn off after screensaver

### ISSUE THREAD

**Issue by maqzek** [JPersson77/LGTVCompanion#246]
## Describe the bug

TV doesn't turn off (shows No Signal) if screensaver is set to a smaller timeout (1min) than display timeout (2mins). No such thing happens if display timeout is set earlier (1min) than screensaver (2mins). Logs shows nothing, the app just doesn't recognize anything happening.

I'm not sure what triggered this behavior, it was working fine before, I'd hoped it would resolve itself, but it's been a month, issue persists.

I've tried setting different options to on/off, re-adding TV, testing works no issues

## How to reproduce the bug?

Turn off display set to 2 minutes, screensaver Blank set to 1 minute. TV shows No Signal after 2 minutes of idle (and 1 minute after screensaver)

## What was the expected behavior

TV turns off regardless of screensaver setting.

## What is your system?

Win 10 22H2, build 19045.4894
LG OLED C2, WebOS 23 13.30.85, (TV Version 8.3.0-29)

## Log file and screenshots

Log: https://www.prcl.dev/n1zldea6xbu5em3 (This is the normal behavior with bigger screensaver timeout, as there's nothing in the log if screensaver is activated earlier)
Config: https://www.prcl.dev/0f4rwi6o3028yci

![image](https://github.com/user-attachments/assets/363593c9-af77-454f-9ff0-ddd1986eb254)

**Comment by JPersson77** [comment]
Thanks. There seem to be corner cases when using the windows screen saver. 

I've alreasy added some related  logic for handling this situation for the situation where screen dimmed events are triggered. In your case windows does not seem to send out any messages at all. Can you please paste a full log and point out the timecode when the screen  should have turned off (i e screensaver +1min). Also please let the computer run undisturbed for 30 minutes after the TV is showing the "no signal" message. Just want to verify if things are delayed (yep seen this happen)

**Comment by JPersson77** [comment]
Hi @maqzek any feedback wrt this issue?

**Comment by JPersson77** [comment]
Closed due to no input. Please feel free to reopen as needed
