### ISSUE TITLE
[BUG] Doesn't turn TV off when going into hibernate (not sleep)

### ISSUE THREAD

**Issue by D3nnis3n** [JPersson77/LGTVCompanion#247]
### Describe the bug

I use hibernate, as sleep has an issue causing games to have low fps after waking from sleep until the pc is completely restarted - that doesnt happen with hibernate.

Entering "Hibernate" does not make the program turn the TV off.

### How to reproduce the bug?

Go into hibernate (not sleep) in Windows.

### What was the expected behavior

TV turning off

### What is your system?

Windows 11 24H2 , LG G3

### Log file and screenshots

Will add later once I go to hibernate again this evening.

**Comment by D3nnis3n** [comment]
The "show" button unfortunately doesn't work in the app, it doesn't make anything appear.
What is the path to the logfile?

**Comment by D3nnis3n** [comment]
Found it, here: https://pastebin.com/XjhTLJTe

Also tested with sleep - it always works when using sleep. Never with hibernate, unfortunately.

**Comment by JPersson77** [comment]
Hi again, not sure if that is the wrong log. The log snippet shows no successful communication between the TV and the PC.

**Comment by D3nnis3n** [comment]
Hey,
it was the correct log. When using hibernation it never works, but with normal sleep it does.

Is it possible networking is turned off before the software does its magic when using hibernate, maybe?

**Comment by JPersson77** [comment]
There is not one successful attempt at communicating in the log though so at this point it looks like a misconfiguration/wrong IP for the TV. There is not enough information in the log to understand why sleep works and hibernate doesn't.

Can you upload another log please?

**Comment by D3nnis3n** [comment]
[log.txt](https://github.com/user-attachments/files/17413344/log.txt)

Here the full log, it's too big for PasteBin this time unfortunately.
I've been using sleep mostly for now, but given it started October 11 it should have hibernate tries in it.

I can also create a new one with hibernate this evening again.

**Comment by JPersson77** [comment]
In that log I can see proper communication so that is good, but nothing looks out of the ordinary. Can you try to hibernate the system once, wake it up and then sleep it immediately after, and then point out the timecodes for me please

**Comment by D3nnis3n** [comment]
Issue seems to have resolved after updating to newest AGESA 1.0.0.2a beta bios, so probably something was wrong with my bios.
