### ISSUE TITLE
[OTH] lg c4 Open the full service menu

### ISSUE THREAD

**Issue by Lang45** [JPersson77/LGTVCompanion#249]
lg c4   webos24   3.11.20
I use

"LGTV Companion.exe" -settings_other "{\"svcMenuFlag\":false}"

Open the full service menu，I use what's in the documentation
"LGTVcli.exe" -settings_other "{"svcMenuFlag": false}" device1
Cannot open。

**Comment by Lang45** [comment]
It seems that some commands cannot be used with     "LGTVcli.exe"    in the new system

**Comment by Lang45** [comment]
Post-run appearance

{"command":"settings_picture","error":"Invalid JSON: [json.exception.parse_error.101] parse error at line 1, column 2: syntax error while parsing object key - invalid literal; last read: '{c'; expected string literal"}

**Comment by JPersson77** [comment]
It should actually be: 

`C:\Program Files\LGTV Companion>LGTVcli.exe -settings_other "{\"svcMenuFlag\": false}" device2`

**Comment by JPersson77** [comment]
the backslash is the escape character. I should probably update the documentation to be clearer

**Comment by JPersson77** [comment]
Documentation was updated. Closing the issue
