### ISSUE TITLE
Display won't turn back on after turning off. Connected party did not properly respond after a period of time

### ISSUE THREAD

**Issue by syaoran68** [JPersson77/LGTVCompanion#25]
hey just updated to the latest version. v1.6.2

using a network 255.255.255.255 broadcast and it looks like that DisplayPowerOnThread() is not able to hit the TV even though the PowerOffThread works perfectly fine. 

I've added some logging data.. where i turned of the screen off. and it worked fine, but turning on i tried 3 times and it fails. 

[log data.txt](https://github.com/JPersson77/LGTVCompanion/files/8358729/log.data.txt)

**Comment by Amoeba00** [comment]
What are your Windows settings for screen timeout and/or display off?
Are you turning off the TV with your remote and then trying to resume before any of those Windows settings kick in?
What is your Power On timeout value in the app?
Are you sure your TV IP hasn't changed?  (I had similar weird issues with the resume a while back before I realized that my IP address on the TV had changed and set a DHCP reservation to prevent it from changing).

**Comment by JPersson77** [comment]
Can you try the two other network options and let me know if that makes a difference?

**Comment by JPersson77** [comment]
Hi @Amoeba00 any update on this issue?

**Comment by Amoeba00** [comment]
@syaoran68 had the issue, I was just relaying my troubleshooting tips since I had a similar issue happen to me a while back.  :-)

**Comment by JPersson77** [comment]
Whoops my bad, sorry mate!

@syaoran68 any update on this? 😁

**Comment by JPersson77** [comment]
Closinig the issue due to lack of additional feedback
