### ISSUE TITLE
[SoundOutput] Streaming Audio from TV to Mobile via Sound Output Mode Change

### ISSUE THREAD

**Issue by PLKHawaR** [JPersson77/LGTVCompanion#250]
am working on changing the sound output mode of an LG TV to "mobile_phone" using the API com.webos.service.apiadapter/audio/changeSoundOutput. After changing the output mode, I need to capture the streamed audio packets that the TV sends to the mobile phone.

Could you please provide guidance on where I can access or intercept these audio streams after switching the sound output mode? Specifically, I need information on how the TV handles the audio transmission when output is set to a mobile device, and the protocol or streaming format involved.

Looking forward to your insights on this issue.

**Comment by PLKHawaR** [comment]
am working on changing the sound output mode of an LG TV to "mobile_phone" using the API com.webos.service.apiadapter/audio/changeSoundOutput. After changing the output mode, I need to capture the streamed audio packets that the TV sends to the mobile phone.

Could you please provide guidance on where I can access or intercept these audio streams after switching the sound output mode? Specifically, I need information on how the TV handles the audio transmission when output is set to a mobile device, and the protocol or streaming format involved.

Looking forward to your insights on this issue.

**Comment by JPersson77** [comment]
Hi @PLKHawaR sorry for a delayed response had to think bout it. But unfortunately in the end I have no insight in the matter.

**Comment by JPersson77** [comment]
Closing the issue
