### ISSUE TITLE
[BUG] Can't remove or add any TV. Settings can't be saved.

### ISSUE THREAD

**Issue by cropyai** [JPersson77/LGTVCompanion#253]
### Describe the bug

The settings and configurations cannot be saved. 

### How to reproduce the bug?

I have LG C3 TV added as "LGC3" and I removed it and added my LG G4 TV. I clicked Apply button. I close the app and open it again. I see that LG G4 was not there. It keeps showing my old TV LG C3. 

### What was the expected behavior

The app should have saved the config successfully when clicked apply button.

### What is your system?

Win11

![image](https://github.com/user-attachments/assets/ba86278c-83ec-4c0f-9a00-cfd855f1e09e)

### Log file and screenshots

1:
![image](https://github.com/user-attachments/assets/de9a4f12-d8b7-4041-b47a-9eb4464991a8)

2: Removed LG C3 and clicking apply.
![image](https://github.com/user-attachments/assets/f823ff18-71a0-46d3-9415-9b20ba38bdaf)

3: Clicked apply.
![image](https://github.com/user-attachments/assets/197dda87-af95-4d89-91ed-76ea652ca3d9)

4: Closed and restarted:
![image](https://github.com/user-attachments/assets/5ba082ae-f0ab-40ff-9903-e1e86e96ab87)

Can someone help me?

I tried uninstalling the app and re-installing it wouldn't fix the problem.

**Comment by JPersson77** [comment]
Hi, can you try adding the -g4, in addition to the older.  Click Apply. 

Then remove the older TV.

Let me know if this works please

**Comment by JPersson77** [comment]
Weird. Can you please try to uninstall the app and then manually remove the configuration file. I e c:/programdata/lgtv companion/config.json (make a backup).

Then reinstall and try again. Let me know how this goes

**Comment by cropyai** [comment]
@JPersson77 after deleting the config.json, it works and saves it properly when I change settings afterwards.

**Comment by JPersson77** [comment]
Good to know. Sounds like an access issue but I don't know how to replicate so going to write it off as a one-off. Happy it works for you!

**Comment by loveyust** [comment]
Can confirm with the recent version (5.0.2) on Windows 11. Changing the permissions on the c:/programdata/lgtv companion/ folder will allow the settings to be saved again.
