### ISSUE TITLE
Cannot set fixed volume.

### ISSUE THREAD

**Issue by dennore** [JPersson77/LGTVCompanion#258]
I am trying to set a fixed volume on the LGTV to 10 when my computer starts... but i have a issue to send the json

getVolume works...
Also volumeUp works... 
but setting a value cant get it working

See screenshot
![image](https://github.com/user-attachments/assets/ab65da1a-9395-46e4-8574-ec9f7495685b)

Anyone got ideas, what i am doing wrong?

I already donated for your great tool.. but setting a volume would be awesome

**Comment by JPersson77** [comment]
Hi, use - request_with_param audio/setVolume {\"volume\":100}

**Comment by dennore** [comment]
Lol thanks it works... i tried -request_with_param but using lgtvcli.exe instead of lgtvcompanion.exe

Can be closed
