### ISSUE TITLE
Launch app at power on tv

### ISSUE THREAD

**Issue by lexcorp** [JPersson77/LGTVCompanion#28]
Hi, it's possible launch app on power on TV?

Maybe using:

ares-cli is a command-line interface (CLI) for webOS. It provides a collection of commands used for creating, packaging, installing, and launching apps or services in the command line environment. ares-cli lets you develop and test apps or services without using any IDE.

https://www.webosose.org/docs/tools/sdk/cli/cli-user-guide/#ares-launch

**Comment by JPersson77** [comment]
Hi, not possible at the moment. Adding as a feature request

**Comment by JPersson77** [comment]
Hi @lexcorp this should be possible with the CLI now
