### ISSUE TITLE
Duplicate restart words in Additional Options section?

### ISSUE THREAD

**Issue by Amoeba00** [JPersson77/LGTVCompanion#29]
I didn't notice this in 1.6.1, but in 1.6.2 - there appears to be duplicates of shutdown and power off in the "Additional options" section.  Is this a typo or there by design?  If by design, what are the differences?

![image](https://user-images.githubusercontent.com/39176113/162231212-407f91ed-9546-4346-a938-da7576176475.png)

**Comment by JPersson77** [comment]
Should be fixed in the latest version

**Comment by Amoeba00** [comment]
Confirmed.  Thanks!
