### ISSUE TITLE
Power off works power on does not. Multiple network adapters?

### ISSUE THREAD

**Issue by morespamlg** [JPersson77/LGTVCompanion#3]
The power off side works perfectly but I am not able to get it to power back on.  I tried the HDD power save settings and the quick power on is enabled.  The TV and the PC are on the same network.  The only think I can think of is if the magic packet is being set out the correct network adapter.  I have VM Ware Workstation installed and that creates multiple VMWare Network adapters.  I am wondering if the magic packet is being sent out from one of these interfaces rather than the correct interface.

**Comment by JPersson77** [comment]
Hi there, can you enable the logging and upload the log to here please so I can have a look: https://pastebin.com/

**Comment by morespamlg** [comment]
Here you go:

https://pastebin.com/ACnCY04w

**Comment by JPersson77** [comment]
Thanks,

Looking at the log I have some questions

1) It looks like you tried experimenting with different values for the power on timeout. Is that correct?

2) Can you confirm that the PC is on subnet 192.168.11.0/24? (note to self - add this piece of info to the log output and add a warning message if not). It should not matter what network adapter broadcasts the WOL, as long as it is on the same subnet. (See my notes in the readme.md on the first page of the repo)

3) Is the TV connected via cable or wifi?

It does indeed look like the TV does not respond to WOL or the WOL package does not reach it. (it looks like the magic packets are sent out from the PC though)

Here are some things for you to consider if you feel like testing:

1) You did not specifically write it, so please ensure that you have enabled 'Turn On via Wi-Fi' (regardless of if the TV is connecting via wifi or cable.

2) If you are on wifi, try using a cable to see if that changes anything. Note that this will require you to update the IP and MAC, so it might be easiest to just add another device while testing. 

3) Double check the MAC-address with what is written in the network settings of the TV.

4) You could try to use this program to see if you can wake the TV with it: https://wol.aquilatech.com/ and then let me know how that goes. This program can also be used to listen for magic packets, which can provide further clues to what is going on and help understand whether broadcasted packets f.e are simply dropped by VMWare and needs 

Let me know please how it goes. If we can find a bug in the code I will update accordingly

**Comment by morespamlg** [comment]
Thank you for all your help.  Totally my bad.  I did not read the instructions carefully enough.  I did not have the turn on via Wi-Fi enable.  After turning that on it is working perfectly.  

Thank you for everything.

**Comment by JPersson77** [comment]
Thanks for confirming, glad it works for you!
