### ISSUE TITLE
How to keep the display from turning on when I remote into PC.

### ISSUE THREAD

**Issue by PsYchitOut** [JPersson77/LGTVCompanion#30]
Hey there. I typically enjoy using the setting where it blanks the monitor after a couple minutes with no input. 
However, it causes a conflict with any remote PC software for gaming such as Steam Link or Moonlight. Problems pretty obvious, I connect to PC, it triggers the LG companion to turn on my tv. Even if I'm hundreds of miles away playing over my phone.  Only fix I've found is to go into the settings every morning before I go to work. Disable the feature that blanks the tv. Then remember to turn it back on when I get home.

**Comment by JPersson77** [comment]
Hey, It should behave just like a regular monitor in these aspect I would assume. 

But I'm a little confounded by your description of the issue - is the issue you experience that the TV turns on when you remote into the PC or that the screen is blanked after X minutes (during your remote sesssion)?

**Comment by JPersson77** [comment]
duplicate, closing this one
