### ISSUE TITLE
Screen State Toggle

### ISSUE THREAD

**Issue by elecgnosis** [JPersson77/LGTVCompanion#32]
The command line arguments are excellent. I wrote a dumb system tray icon UI to execute the commands, so instead of seven awkward remote control button presses, I can turn the screen on with my mouse.
I still have to pick the command to run from a menu depending on what the current state is though, so I'm hopeful that you might be able to add a `screentoggle` to the commands so that regardless of whether the screen is on or off, one call to this command would invert it. Same for the TV's power state.

**Comment by JPersson77** [comment]
See what you mean, but it's not straightforward to build it I think. To determine the current power-status of the TV the app needs to query it, but if the app query the TV when the TV is off there will be no response. So essentially the logic needs to be built around "indeterminate states", allowing for delays in the network etc. Seems hard to build something bulletproof out of that. 

Typically though if you don't get a response on your LAN within say 200 ms, I guess there is a high probability you won't ever so I guess one could "workaround" by sending an off command, and in the absence of a reply within 200 ms send a power-on WOL. I'll think about it

**Comment by JPersson77** [comment]
Closing this request since it's not really feasible to implement, at the moment. The system requirement would require that the user has a 2022 or later model with "always ready" enabled for this to operate properly so I think there is too much of a risk for ambiguities and unclarities around implementing this as a feature
