### ISSUE TITLE
(Support) Interaction with enabling/disabling TV input (TV wakes up despite not being enabled)

### ISSUE THREAD

**Issue by ividyon** [JPersson77/LGTVCompanion#35]
Following use case:

* Display profile management software with hotkeys (Monitor Profile Switcher)
* "Desktop" profile which enables my 3 desktop monitors and disables the LG TV
* "TV" profile which disables the desktop monitors and enables the LG TV

When I'm in my "Desktop" profile and wake the PC from screensaver/screen off, LGTV Companion seems to send a wakeup signal to the TV.

This then leads to my monitors freaking out for a while, trying to manage display modes. I assume this has to do with HiDPI settings and HDR. It takes like 20 seconds for my monitors to stop turning on/off.

Then, the TV is on, but not showing anything (as the Windows display is disabled). I didn't *want* it to be on, since I turned it off in Windows display settings!

![image](https://user-images.githubusercontent.com/1077140/167266635-0b94fe65-fb06-4551-bc8f-b8693300146d.png)

In this image, the TV is input 3, and this depicts my "Desktop" profile.

Questions:
* Can the wakeup signal only be sent if the display is enabled?
* Can I also disable any other interaction (auto enable monitor on startup, etc.) if the display is disabled?

Essentially, I'd like to use the LGTV Companion features when I'm in the "TV" profile, but not when I'm in the "Desktop" profile.

**Comment by JPersson77** [comment]
I see how you mean, I'll add it as a feature request and see what can be done about it. 

In the meanwhile you can try experimenting with the command line parameters of LGTV Companion. If you can use the monitor profile switcher to launch the app with command line parameters you can directly control power on/off state and disable/enable automatic management. See the reference [here](https://github.com/JPersson77/LGTVCompanion#commandline-arguments)

**Comment by JPersson77** [comment]
@ividyon Hi I have a test build for you if you want to beta-test. Let me know and I'll provide a link

**Comment by JPersson77** [comment]
Please check out the latest release which should do what you want: [Releases](https://github.com/JPersson77/LGTVCompanion/releases)

**Comment by JPersson77** [comment]
Closed due to feature has been implemented
