### ISSUE TITLE
At startup LGTVCompanion generates an error

### ISSUE THREAD

**Issue by mmcgee01** [JPersson77/LGTVCompanion#37]
Error: Failed to initialize Toast Notifications: 3
This error is generated consistently on startup.

**Comment by mmcgee01** [comment]
I managed to resolve it.I am running Windows 11, 21H2. LGTV Companion v1.62.I do see "LGTV Companion (Daemon)" on the start menu.The error occurs when Account File Redirection is enabled in group policy for the “Start Menu”.If that setting is disabled & reverted the issue goes away. i.e. The accounts “Start Menu” must be located on the local disk.  From: JPersson77Sent: Wednesday, June 15, 2022 1:20 PMTo: JPersson77/LGTVCompanionCc: mmcgee01; AuthorSubject: Re: [JPersson77/LGTVCompanion] At startup LGTVCompanion generates an error (Issue #37) Hi, some immediate questions:what OS are you running? Please include build number if you can.Is LGTV Companion running sandboxed/emulated?Do you have an icon on the windows start menu named "LGTV Companion (Daemon)"?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by JPersson77** [comment]
Interesting! I'll see how it can be worked around to mitigate the error and provide the functionality with AFR. Thanks for feedback!

**Comment by JPersson77** [comment]
Check out the new version which does not throw the error. The issue with file redirection is with a third party library so some work needs to be done there. As a consequence of this issue windows will not show notifications of new/updated versions in this (rare) user case until it can be sorted properly.

**Comment by JPersson77** [comment]
Closing due to above mentioned workaround implemented
