### ISSUE TITLE
LG NANO90 wont turn on

### ISSUE THREAD

**Issue by mbushnaq00** [JPersson77/LGTVCompanion#4]
I have the LG 55" Nano90 and have installed the Lgtvcompanion as per the instructions. However, the function to turn on the TV is not working. I can turn it off without issues, but went bringing the PC back from sleep or turning it on does not turn on the TV.

I tried the following troubleshooting steps:

- Checked that "Turn on with Mobile" is enabled in the device connection settings
- Turned off HDD Eco Mode
- Check that Quickstart+ is enabled
- Set a Reserved IP in the DHCP ip pool for the TV
- Verified that the MAC address is correct in the app

The mobile app "thinq" from LG can turn on the TV without issues, which indicates an issue with the Lgtvcompanion app itself.

Log info FYI:

```
Thu 14:33:04 > IPC command received: -poweron Device1
Thu 14:33:04 > Device1, spawning DisplayPowerOnThread().
Thu 14:33:04 > Device1, repeating WOL broadcast started to MAC: <ADDRESS>
Thu 14:33:25 > Device1, WARNING! DisplayPowerOnThread(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Thu 14:33:46 > Device1, WARNING! DisplayPowerOnThread(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Thu 14:33:46 > Device1, repeating WOL broadcast ended
```

**Comment by mbushnaq00** [comment]
> Hi there,
> 
> Thanks for your feedback and let's try to solve. Can you verify that the PC and TV is on the same VLAN/subnet?

Yes it is in the same VLAN/subnet. 

I tried sending a WOL packet and the TV turns on, but through the app it does not work

**Comment by JPersson77** [comment]
Thanks for verifying. I don't have an immediate solution, so more investigation is needed . If you don't mind helping me troubleshoot further can I ask you to download a WOL client/sniffer from here: https://wol.aquilatech.com/ . This app has a built in packet sniffer which you can use to inspect that 1) the app broadcasts the WOL, and 2) that the contents of the magic packet is correct (compare it with the WOL-packet sent from the other app which can turn on the TV). I will patch the code if we find a bug.

**Comment by mbushnaq00** [comment]
> Thanks for verifying. I don't have an immediate solution, so more investigation is needed . If you don't mind helping me troubleshoot further can I ask you to download a WOL client/sniffer from here: https://wol.aquilatech.com/ . This app has a built in packet sniffer which you can use to inspect that 1) the app broadcasts the WOL, and 2) that the contents of the magic packet is correct (compare it with the WOL-packet sent from the other app which can turn on the TV). I will patch the code if we find a bug.

Thanks a lot for your support. I have installed the wol app that you mentioned and tried to broadcast a wol packet with the TV MAC address which did not work, however when I choose the option FQDN with the TV IP instead of broadcast the TV would turn on instantly. I tried using the listener in the app, but it only shows the result when only broadcasting, FQDN does not showup. Also I noticed one issue in the broadcast packet details, I currently have 2 network cards, one is a Wifi which is connected to the same network as the TV, and another is a wired connection which is connected directly to a NAS box. The broadcast source seems to always go through wired connection (192.168.0.x) which is why the TV is not getting the WOL packet.

Below are the packet details for broadcast from the app and LGTV companion:

**Aquilatech WOL:**

`--------------------- Received Packet ---------------------
Date:               Saturday, April 17, 2021
Time:               10:51:42 AM
Source:             192.168.0.100:9
Destination:        255.255.255.255
Length:             102
Protocol:           Udp
Port:               9
Hostname:           NANO90 TV
MAC Address:        <MAC ADDRESS>

Raw Data:
          FF FF FF FF FF FF AC F1 08 EF D1 02 AC F1 08 EF 
          D1 02 AC F1 08 EF D1 02 AC F1 08 EF D1 02 AC F1 
          08 EF D1 02 AC F1 08 EF D1 02 AC F1 08 EF D1 02 
          AC F1 08 EF D1 02 AC F1 08 EF D1 02 AC F1 08 EF 
          D1 02 AC F1 08 EF D1 02 AC F1 08 EF D1 02 AC F1 
          08 EF D1 02 AC F1 08 EF D1 02 AC F1 08 EF D1 02 `

**LGTV Companion:**

`--------------------- Received Packet ---------------------
Date:               Saturday, April 17, 2021
Time:               11:02:19 AM
Source:             192.168.0.100:56340
Destination:        255.255.255.255
Length:             102
Protocol:           Udp
Port:               9
Hostname:           NANO90 TV
MAC Address:        AC:F1:08:EF:D1:02

Raw Data:
          FF FF FF FF FF FF AC F1 08 EF D1 02 AC F1 08 EF 
          D1 02 AC F1 08 EF D1 02 AC F1 08 EF D1 02 AC F1 
          08 EF D1 02 AC F1 08 EF D1 02 AC F1 08 EF D1 02 
          AC F1 08 EF D1 02 AC F1 08 EF D1 02 AC F1 08 EF 
          D1 02 AC F1 08 EF D1 02 AC F1 08 EF D1 02 AC F1 
          08 EF D1 02 AC F1 08 EF D1 02 AC F1 08 EF D1 02 `

**Comment by JPersson77** [comment]
Great, thanks a bunch for your investigations. Interesting use case, and it makes sense that the WOL-packages are dropped.

There is actually no code which selects NIC for winsock operations, it's just broadcasted and Windows decides by which NIC. Usually a wired NIC will take priority over a wireliess so that should maybe explain the problem. I will investigate the opportunity to select NIC, or maybe sending on all attached network interfaces. meanwhile, as a potential workaround, you could try to manually set the priority order of the NICs. Please see this for more info on hos: https://www.windowscentral.com/how-change-priority-order-network-adapters-windows-10

Please let me know how that goes. Have a nice weekend!

**Comment by mbushnaq00** [comment]
thanks a lot for the workaround, the TV turns on now after setting the interface metric to 1 on my Wifi adapter :)

hopefully there are no other bugs, I will report back if I encounter any other issue.

Again, thanks a lot for your effort in building this app, it is really needed for folks who use their TVs as monitors :)

**Comment by JPersson77** [comment]
Perfect, thanks for letting me know and for helping me testing the issue. Happy about the app working for you now. Will still consider some additional functionality for multiple client NICs, and will add this some additional info to the troubleshooting guide. Cheers!
