### ISSUE TITLE
Feature request - Don't blank screen while watching video

### ISSUE THREAD

**Issue by psbeau** [JPersson77/LGTVCompanion#41]
Screen blank
Unfortunately, this nice little feature blanks the screen while I'm watching a vidoe.
Could be solved by detecting full screen:

QUERY_USER_NOTIFICATION_STATE pquns;
SHQueryUserNotificationState(&pquns);
QUNS_RUNNING_D3D_FULL_SCREEN – fullscreen (Direct3D application is running in exclusive mode, i.e. fullscreen)

**Comment by dechamps** [comment]
The whole point of the LGTVCompanion's user idle detection feature is precisely to blank the screen *even when using a full screen application*. See #13.

If you want to prevent the screen from being turned off when using a full screen app, don't use the user idle detection feature - instead, use a blank screensaver or the Windows screen auto power off feature.

**Comment by psbeau** [comment]
" that means there is definitely something wrong with your settings " Black level was on "Full"  - I only got the TV yesterday

Anyway, I have implemented it myself, now LGTVC Screen Blank works as I want.

**Comment by JPersson77** [comment]
Closing due to feature request was implemented as a user configurable option in v1.9.0
