### ISSUE TITLE
(Support) Any way not to shutdown TV when input source is not PC?

### ISSUE THREAD

**Issue by hoho97** [JPersson77/LGTVCompanion#42]
I've been using my TV for PC monitor and PS5 (and sometimes netflix) as well

When I switch input source to PS5, the TV still turn off if I leave the PC idle long enough to off the screen

Is there any workaround so when I am playing PS5 the TV won't turn off automatically? Thanks

**Comment by JPersson77** [comment]
Hi, there is a feature for this. Check out the per device configuration

![Skärmbild 2022-07-21 084127](https://user-images.githubusercontent.com/77928210/180147402-0679b229-fc31-41a1-b5dc-c9fbc3e31c12.jpg)

**Comment by hoho97** [comment]
> Hi, there is a feature for this. Check out the per device configuration
> 
> ![Skärmbild 2022-07-21 084127](https://user-images.githubusercontent.com/77928210/180147402-0679b229-fc31-41a1-b5dc-c9fbc3e31c12.jpg)

thanks for response. I do not tick this option

Do I need to set my PC never turn off display as well?

**Comment by JPersson77** [comment]
Hi again, you can keep that windows setting at whatever you prefer. When you tick this option then your display will just not process any power/screen off events, including those that windows generate when turning off displays

**Comment by JPersson77** [comment]
Closed
