### ISSUE TITLE
Only turn off the TV and shortcuts

### ISSUE THREAD

**Issue by imartz0** [JPersson77/LGTVCompanion#46]
Hello, 
I wanted to know if it is possible to just synchronize the turning off of the TV
I also wanted to know if I can only use the shortcuts, if I uncheck "restart" in the settings the shortcuts don't work
Thank you very much

**Comment by JPersson77** [comment]
Actually, come to think of a sort of workaround which in effect do what you want, temporarily. If you have automatic management of the display enabled in the UI but change the MAC-address of the display (in the configuration) to something which is invalid then I would assume the display will not turn on automatically, but it should still turn off properly. Not exactly a pretty workaround, but it might achieve what you want for now :)

**Comment by imartz0** [comment]
> Hi @imartz0,
> 
> That is not exactly possible! I can consider adding it as an option.
> 
> What you describe about unchecking "restart" and not being able to use the command line sounds like a bug - will investigate!
> 
> You can certainly control the TV using only the command line (i e no automatic on/off...). First you need to disable the automatic management of the device in the UI or using the command line and then you can run the executable with the proper command line argument. Reference to the readme: [link](https://github.com/JPersson77/LGTVCompanion#readme)

Hi again, It worked perfect since I configure it using AHK but now it stop working. Only the command to turn on the tv works. Thank you!

**Comment by JPersson77** [comment]
Hi @imartz0 can you paste a log over at pastebin please and also indicate the timecode when the issue occurs so I can have a look?

**Comment by imartz0** [comment]
> Hi @imartz0 can you paste a log over at pastebin please and also indicate the timecode when the issue occurs so I can have a look?

I fixed it by rescanning the tv again. Thank you!

**Comment by JPersson77** [comment]
Good to hear! Maybe double check that you have set your router to permanently assign the same IP to the TV. THanks too!
