### ISSUE TITLE
This app was featured in Linus Tech Tips

### ISSUE THREAD

**Issue by StefanLobbenmeier** [JPersson77/LGTVCompanion#47]
Hey :) not an issue, but more of a heads up. 

In the latest LTT video they briefly talk about this app: https://youtu.be/4mgePWWCAmA?t=20m48s

If you like you could add this as a reference in the readme, e.g. the following quotes could be fun:

> That is a really janky solution. But... it works! LTT at https://youtu.be/4mgePWWCAmA?t=21m14s

> That was really fast! LTT at https://youtu.be/4mgePWWCAmA?t=21m29s

> How cool is Jpersson77! LTT at https://youtu.be/4mgePWWCAmA?t=21m58s

**Comment by StefanLobbenmeier** [comment]
Of course you dont have to do anything, but it probably is nice being appreciated by a "celebrity". The repo might also get some more stars because of this shoutout.

**Comment by JPersson77** [comment]
Haha, that did my evening! Thanks for heads up Stefan 👍  :)

Thanks for suggestions as well, I think it sounds good! Let's do it :)

**Comment by To1ne** [comment]
Came here to say this!

I love the internet.

**Comment by dechamps** [comment]
I am glad that can now say that "I was named in an LTT video".

![image](https://user-images.githubusercontent.com/866859/186537709-0e446786-9d84-4b73-bb41-d0cd5c5b0a04.png)

😁
