### ISSUE TITLE
Alternatives for other TV brands?

### ISSUE THREAD

**Issue by couleurm** [JPersson77/LGTVCompanion#49]
Hey, do you know any other alternatives to make the experience on Samsung TVs less crappy? I've got a UE65NU7105KXXC by the way

**Comment by JPersson77** [comment]
Hi @couleurm sorry to say I'm not aware of anything similar for a Samsung. But a quick google shows the necessary APIs seem to exist so it should be a possibility at least

**Comment by JPersson77** [comment]
Hi @iizu yeah that sounds about right. I noticed that Samsung TVs can be powered on with the same mechanism (WOL)

**Comment by JPersson77** [comment]
I did actually reach out to samsung to ask for a loaner to see what could be done, but got a negative response. There is a similar Tizen API as WebOS so I'm guessing it can be done. Closing this issue for now though since I don't have the hardware
