### ISSUE TITLE
Add the minimize button, minimize on close option

### ISSUE THREAD

**Issue by nikitasatcik** [JPersson77/LGTVCompanion#53]
Hi @JPersson77,

Somehow, the companion app GUI is missing the "minimize" button. 
It would be useful to add such button and also an option to minimize to tray on close.

**Comment by xingfanxia** [comment]
Yeah it's kinda annoying it has to float somewhere on the screen

**Comment by JPersson77** [comment]
Hi,

I didnt think anyone wanted to keep the window open once it was initially
configured tbh but I will look into an option to "dock to tray".

Kind regards

**Comment by JPersson77** [comment]
@nikitasatcik @xingfanxia any feedback on the above? Want to get feedback on this so I can maybe be clearer on how the configuration window should be used.

**Comment by JPersson77** [comment]
Added a minimize button to the latest release! But again, there is no need to keep the configuration UI open after all ihas been configured. The UI is only used for configuring the service.

**Comment by JPersson77** [comment]
Closing this issue dues to missing feedback and the minimize button request was implemented
