### ISSUE TITLE
LG C2 with french words don't shutdown/resart

### ISSUE THREAD

**Issue by Arthurdevid** [JPersson77/LGTVCompanion#55]
Hello

Brand new owner of a an LG C2 here.

Thanks for your software !

My OS is in french and the words are detected but they are not working.

And when i enable it, my restart or shutdown, take very long, not like usual. 

I have look at the log and i see each time i do a shutdown, the soft thinks it's a restart and same for restart but not working.

**Comment by JPersson77** [comment]
Hi @Arthurdevid, 

Thanks for feedback! I need some additional info. 

Can you please provide a screenshot of your "restart words" when you have it properly configured. It should be configured so that you have a checkbox next to the word which in french means "restart". (Click apply etc to make it active)

Then, with this configuration, enabled can you confirm whether the display turn off or stay awake for a system shutdown and also whether the display turn off or stay awake for a system reboot/restart. 

Then, please attach the log here and a timestamp of when the display did not behave as expected.

Thanks for assisting!

**Comment by Arthurdevid** [comment]
<img width="346" alt="185311" src="https://user-images.githubusercontent.com/92452954/188206625-6ddebd34-1168-4d80-9b7c-ea08947b6630.png">

When shutdown 

you can see :

Fri 16:54:54 > IPC, Daemon has started.
Fri 19:22:18 > The service terminated.

Fri 19:22:18 > LGTV Companion Service started (v 1.7.0) --------------

Nothing here 

And same when restarting

**Comment by JPersson77** [comment]
Hi, 

thanks!

If I understand my google translate correctly (forgive me if I'm wrong) only "redémarrer" seems to mean "restart". So from the screenshot it looks like you need to untick the other ones. Basically you need to have it configured analogous to this: 
![Skärmbild 2022-09-02 193618](https://user-images.githubusercontent.com/77928210/188208036-a501971c-2556-457e-bacc-66663bb0fe17.jpg)

(Remember to apply the settings)

OK, so now that we are assumedly correctly configured and if it still does not work I need the following info: 

1) please tell me:
- does the display shut down when restarting the system? yes or no?
 - does the display shut down when the system is shutting down? yes or no?

2) more information from the log. Can you please paste the full log, and indicate to me the timepoints when the system is A) restarting and B) shutting down. You can use pastebin for example and just copy the link here. There is no personal information in the log.

3) confirmation that you have event 1074 in the event log which correspond to the times the system is shutting down/restarting. You need to start the event viewer, create a custom view which looks like the below screenshot to properly sort them out. Please paste a screenshot here for the ones which correspond to A) the system restarting and B) the system shutting down.

**Comment by Arthurdevid** [comment]
Hi,

Sorry for wasting your time, beacause now it's working perfectly !

i have mis interpreted, this sentence : 'you must in the 'additional settings' dialog click the correct checkboxes to indicate what words refer to the system restarting/rebooting'.  I thought, if it's more than one checkbox it must be for something...

But now i see the one checkbox on the screenshot documentation, it make sense haha 

Thanks for your work on this wonderfool tools.

You can close, thanks a lot.

**Comment by JPersson77** [comment]
Hi,

that's great to hear! Thanks for feedback and helping me figure it out. Maybe I can consider rewording the hint text :)

Have a nice evening
