### ISSUE TITLE
Really great and useful application!

### ISSUE THREAD

**Issue by AFranklin520** [JPersson77/LGTVCompanion#56]
I've been trying this out for a few weeks now, and I just have to say it works exactly as advertised. I really appreciate you and your excellent work.

**Comment by kimpurcell** [comment]
Is there an equivalent that works for the LG 48GQ900?

**Comment by AFranklin520** [comment]
> Is there an equivalent that works for the LG 48GQ900?

It might just work with any LG TV. I have a NANO85, not OLED and it works great. Just give it a shot, the worst that can happen is nothing. Just make sure to follow the instructions exactly or it won't work.

**Comment by JPersson77** [comment]
@kimpurcell it should work for all modern LG TV using WebOS.

@AFranklin520 thanks a bunch mate!

**Comment by kimpurcell** [comment]
> @kimpurcell it should work for all modern LG TV using WebOS.
> 
> @AFranklin520 thanks a bunch mate!

Thanks. That means it won’t work on the LG 48GQ900, because it’s a monitor and doesn’t come with WebOS or Wi-Fi.
