### ISSUE TITLE
LG not start when pc run.

### ISSUE THREAD

**Issue by devNostyle** [JPersson77/LGTVCompanion#57]
Hi,
I try my best,  but porgram not start when I turn on PC.
turn off seems work well, but only that.

**Comment by JPersson77** [comment]
Hi @devNostyle 

I assume you have followed the setup guide in the readme, but can you please confirm you have done this: 

- Ensure that the TV can be woken via the network. For the CX line of displays this is accomplished by navigating to Settings (cog button on remote)->All Settings->Connection->Mobile Connection Management->TV On with Mobile, and then enable 'Turn On via Wi-Fi'. For C1 and C2 it's All Settings->General->Devices->External Devices->TV On With Mobile->Turn on via Wi-Fi

Then have a look at these troubleshooting steps:

- When connecting the TV via Wi-Fi it seems some users must enable "Quickstart+" and disable "HDD Eco mode" to avoid the NIC becoming inactive. (physical network cable does not seem to need this)
- Try reconfiguring the device and use one of the other wake-on-lan network options, primarily use option three, using a subnet mask.
- Ensure the network is not dropping WOL-broadcasts.
- The MAC-address configuration for the device in the application is erroneous.

If you can't get it to work by following the above please enable logging in the global options and upload the full log to pastebin and paste the link here and I will have a look.

**Comment by devNostyle** [comment]
ehh, sry 

Ensure that the TV can be woken via the network. For the CX line of displays this is accomplished by navigating to Settings (cog button on remote)->All Settings->Connection->Mobile Connection Management->TV On with Mobile, and then enable 'Turn On via Wi-Fi'. For C1 and C2 it's All Settings->General->Devices->External Devices->TV On With Mobile->Turn on via Wi-Fi

FIXED my issue, all work great now !
