### ISSUE TITLE
Installation Issues - Am I dumb or just missing something :'(

### ISSUE THREAD

**Issue by samkirkh08** [JPersson77/LGTVCompanion#59]
Gday mate, 

Saw this on Linus's video and is just what I have been after, but after some time I just cannot figure out how to instal?

I will step you through what I have done thus far as Im almost certain its that I dont know how to use github very well (new user!)

1. From this page (https://github.com/JPersson77/LGTVCompanion)  I download the code as zip
2. I unzip folder
3. I cant immediately see any installation files in the main folder so expect this to be in the 'LGTV Companion Setup' folder
4. The only file in this folder is a WIXPROJ file, which I did some research into and downloaded Wix Toolset to try and open but still nothing
5. I go through the other folders and I just cant locate anything that will run natively on my computer. 

Any ideas?

Thanks very much for your help!

**Comment by dechamps** [comment]
There's no need to download the code. What you're looking for is the [releases page](https://github.com/JPersson77/LGTVCompanion/releases).

@JPersson77 In my experience people unfamiliar with GitHub often get confused like this. The way I fix it in my own projects is by adding a link in bold letters at the top of the README to direct people to the releases page ([example](https://github.com/dechamps/FlexASIO)). That seems to be effective. Also under the ["Installation and usage"](https://github.com/JPersson77/LGTVCompanion#installation-and-usage) section of the README you might want to make "Download the setup package and install" a link to the releases page as well.

**Comment by JPersson77** [comment]
@dechamps good idea! Let's do that!

@samkirkh08 what @dechamps said. Just download and install the latest release from the releases page and install it as per usual.

**Comment by samkirkh08** [comment]
Thanks very much @dechamps & @JPersson77!
