### ISSUE TITLE
LG companion app is making TV turn off even when in use, can only wake up with remote

### ISSUE THREAD

**Issue by Eden365** [JPersson77/LGTVCompanion#60]
Without the companion app, tv works fine. When i set everything up. The TV is automatically going dark after a minute and then no mouse or keyboard movement will wake it. Pressing a button on the remote instantly wakes the tv again.

Have I done something wrong, please help!

**Comment by JPersson77** [comment]
Hi, it sounds like the application can communicate with the display, but not wake it. 

I assume you have followed the setup guide in the readme, but can you please confirm you have done this:

Ensure that the TV can be woken via the network. For the CX line of displays this is accomplished by navigating to Settings (cog button on remote)->All Settings->Connection->Mobile Connection Management->TV On with Mobile, and then enable 'Turn On via Wi-Fi'. For C1 and C2 it's All Settings->General->Devices->External Devices->TV On With Mobile->Turn on via Wi-Fi

Then have a look at these troubleshooting steps:

- When connecting the TV via Wi-Fi it seems some users must enable "Quickstart+" and disable "HDD Eco mode" to avoid the NIC becoming inactive. (physical network cable does not seem to need this)
- Try reconfiguring the device and use one of the other wake-on-lan network options, primarily use option two, connect using an IP adress.
- Ensure the network is not dropping WOL-broadcasts.
- The MAC-address configuration for the device in the application is erroneous.

If you can't get it to work by following the above please enable logging in the global options and upload the full log to pastebin and paste the link here and I will have a look.

**Comment by Eden365** [comment]
> 

Hi friend, thank you so much for getting back to me. 

Correct, I followed your guide and I enabled the turn on via wi-fi. That all works great!

- I have quickstart + enabled

Here is the log data from when I was having issues - 

https://pastebin.com/arpxMpQj

It appears this is the error that is causing my issue - _A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond Device1, repeating WOL broadcast ended_

Is this what you referred to as dropping WOL-broadcasts? How do i fix that?

It was working fine today. TV was automatically turning off when idle and it was waking with movement of my mouse. I only run into issues when the automatic blank is enabled and I cannot wake the TV and the remote is required to wake up the TV.

Thank you so much.

**Comment by dechamps** [comment]
> Here is the log data from when I was having issues -
> https://pastebin.com/arpxMpQj

Your log shows you are using broadcasts. Have you tried the "Device IP-address" option? It should be more reliable. Make sure your LGTVCompanion is up to date as there have been improvements (#22) in this area.

**Comment by Eden365** [comment]
> > Here is the log data from when I was having issues -
> > https://pastebin.com/arpxMpQj
> 
> Your log shows you are using broadcasts. Have you tried the "Device IP-address" option? It should be more reliable. Make sure your LGTVCompanion is up to date as there have been improvements (#22) in this area.

Thank you. I'll change it to that and see how I go.

**Comment by JPersson77** [comment]
Hi @Eden365 any progress with this?

**Comment by Eden365** [comment]
> Hi @Eden365 any progress with this?

Yes! I believe changing it to Device IP-address and resetting my router fixed this issue!
