### ISSUE TITLE
Test is greyed out

### ISSUE THREAD

**Issue by ThinkSalat** [JPersson77/LGTVCompanion#61]
I added manually using my wifi connection and the test option is greyed out,.

![image](https://user-images.githubusercontent.com/31082405/191306736-d089209f-9bd3-4258-b7ff-2492b952ad6d.png)

**Comment by JPersson77** [comment]
Click apply and try again. Should work!

**Comment by ThinkSalat** [comment]
Thanks! That' worked. Now i'm getting this error 

![image](https://user-images.githubusercontent.com/31082405/191308826-16008e24-fb8f-45e0-a9c0-a13d6027cbfd.png)

**Comment by ThinkSalat** [comment]
Weird. it's running. I have the dhcp thing configured correctly. Still getting the same error. I reset my routers. I'll try resetting my computer

**Comment by ThinkSalat** [comment]
By the way, this is my config

![image](https://user-images.githubusercontent.com/31082405/191312785-c0a4c600-54fa-4d90-943d-e940abc80383.png)

**Comment by ThinkSalat** [comment]
HOLD up, I restarted the service and the UI and the test worked! Incredible, thank you

**Comment by JPersson77** [comment]
Ah excellent! We'll just write it off as a fluke then. Happy it works!

**Comment by ThinkSalat** [comment]
Thanks for such excellent support and feedback - I have another question. So I turn off the tv - how do I get it to turn on again based on input from my computer? Is that part of this program as well>

**Comment by JPersson77** [comment]
You are welcome! Yeah the application will turn the display on/off similarly to how a regular PC-monitor will behave. So I advise you configure the windows power settings to turn the display off after, say, 30 minutes of user inactivity and optionally enable the user idle detection/screen blanking feature in LGTV companion and set it at 5 minutes or so. And then you should be able to leave the remote control untouched for most regular power on/off situations

**Comment by ThinkSalat** [comment]
Hey @JPersson77, last night I left the tv on and let it turn off on its own in accordance with the instructions, and this morning it didn't wake when I started using my coptuer - my original monitor turned on (laptop). I'm using an LG C1
here's my settings:
![image](https://user-images.githubusercontent.com/31082405/191510074-6fc6ac96-0823-4dc3-b830-4a039e4b50aa.png)
![image](https://user-images.githubusercontent.com/31082405/191510134-86d3ba02-d857-4f72-8db9-5d0add04de2e.png)

I've completed the following:
When connecting the TV via Wi-Fi it seems some users must enable "Quickstart+" and disable "HDD Eco mode" to avoid the NIC becoming inactive. (physical network cable does not seem to need this)


AM unsure how to the following part. Is this pat of the admin panel of the router or is this on the tv itself? I can't seem to find this option on my tv
Try reconfiguring the device and use one of the other wake-on-lan network options, primarily use option three, using a subnet mask.
Ensure the network is not dropping WOL-broadcasts.

**Comment by JPersson77** [comment]
Thanks for report, can you confirm the TV has the same IP-adress today as
yesterday? Check your TVs network settings. I e 192.168.50.115. Then upload
the log to pastebin so I can have a look at it. Cheers!

**Comment by ThinkSalat** [comment]
Yes, The ip is the same! And where exactly is the log stored? btw I'm sending a donation your way and when I have a second I will help update your README (the rest of your code is way above my level)

**Comment by JPersson77** [comment]
Thanks mate it is much appreciated! The log is stored typically in
c:/programdata/lgtv companion/ but you can also access it by clicking on
the "log" hyperlink in the global options page.

If the IP is correct then the next thing to try would be the other two
network options in the device configuration page (broadcast to subnet,
network broadcast .... in that order). Also, if you can't make it work and
you are connecting the TV wirelessly to your LAN, try to connect with a
cable (if possible).

But, yes the log will tell me more :)

**Comment by ThinkSalat** [comment]
Here's the paste bin https://pastebin.com/m1jtzwVs

And whjat you mean trying the other two network options is using these?

![image](https://user-images.githubusercontent.com/31082405/191572454-d5d70be4-b2b0-4a06-a2e6-a12ea9178b51.png)



I'll continue troubleshooting. Unfortunately it's a little time consuming as I've only noticed it happening in the morning. For example last night I took your advice and let the television turn off by itself - not using the power button on the remote. In the morning my computer didn't activate the tv.

**Comment by JPersson77** [comment]
Note to self: do not email responses as it does not work properly

Hi, thanks, the log does not indicate that anything is going wrong actually. The software seem to be able to communicate with the TV, and is getting a response from the TV.

Yes, you can try those other two options to see if anyone works better. Are you using a wired connection to the TV or a cable?

Can you confirm also that you have done this: 
  
-Ensure that the TV can be woken via the network. For the CX line of displays this is accomplished by navigating to Settings (cog button on remote)->All Settings->Connection->Mobile Connection Management->TV On with Mobile, and then enable 'Turn On via Wi-Fi'. For C1 and C2 it's All Settings->General->Devices->External Devices->TV On With Mobile->Turn on via Wi-Fi.

**Comment by dechamps** [comment]
> The only time it errors is in the morning after about 8 hours.

If you're using WiFi, it's important to keep in mind that, in order for WoL to work, the TV must stay *continuously* connected to the WiFi network for the entire time that it's off (i.e. 8 hours in your case). If the TV is disconnected from the WiFi network for any reason while it is off, it will *not* automatically reconnect and you will need to turn on the TV manually.

The TV could get disconnected from the WiFi network for any number of reasons. Your WiFi access point (router) might have rebooted during the night (firmware update, power loss, etc.). It might have decided to change channels. Interference might have killed the connection. Or maybe your particular WiFi access point just decides to arbitrarily kick stations (clients) out after a period of inactivity.

If you have access to your WiFi access point logs, you might be able to confirm what happened during the night.

**Comment by JPersson77** [comment]
I understand your reasons for keeping it wireless. 

Since it fails to wake up after being off during the night (an extended period) I find it likely that the TV is losing contact and can't automatically reconnect with the network, and only a manual power on will make it connect again. The reason for this in my experience might be twofold: either your router/accesspoints for some reason goes down occasionally during the night causing the TV to disconnect and not automatically reconnect. Or the wireless NIC in the TV disconnects after some time from the network, potentially due to some power saving. 

So yeah, a wired cable will probably help, let me know how your troubleshooting goes please

**Comment by ThinkSalat** [comment]
Hello @JPersson77 ! Wiring it up was the solution! Perhaps the wifi network automatically drops connections or something for some kind of power saving mode. I also use a mesh setup but I highly doubt that has anything to do with it, as it would've caused other problems. Anyway I will mark this closed. Thank you very much :)

**Comment by JPersson77** [comment]
Thanks @ThinkSalat I think we can conclude from this and other issues that the wifi-adapter in the CX-C2 lines exhibit this behaviour. Happy it works with a cable! Have a nice weekend! :)

**Comment by ThinkSalat** [comment]
Hi @JPersson77 is this the thread you meant to reply to? I resolved it through using hardwired cable with the tv.
