### ISSUE TITLE
Does my computer need to run on the same wifi connection as the TV?

### ISSUE THREAD

**Issue by Evolx1** [JPersson77/LGTVCompanion#62]
For some reason my tv can't connect to a 5ghz wifi connection. But my computer can. It is much more reliable than the normal wifi. 

Will this affect the companion app?

**Comment by dechamps** [comment]
Ideally they should be on the same Ethernet segment (IP subnet).

If you have one WiFi network that is advertised as both 2.4 and 5 GHz (which is the normal way to do it), it will work.

If you have two WiFi networks, but they are connected to the same Ethernet segment, it will work.

If you have two independent WiFi networks that use different IP subnets, expect trouble.

**Comment by Evolx1** [comment]
> Ideally your computer and the TV should be on the same Ethernet segment (IP subnet).
> 
> If you have one WiFi network that is advertised as both 2.4 and 5 GHz (which is the normal way to do it), it will work.
> 
> If you have two WiFi networks, but they are connected to the same Ethernet segment (i.e. they share the same IP block), it will work.
> 
> If you have two independent WiFi networks that use different IP subnets, expect trouble.

Hmmm I'll have to try it again. 

What about Ethernet? Is it possible to leave my computer connected with Ethernet and then the TV setup with wifi?

**Comment by dechamps** [comment]
Yes. You can do wired Ethernet on the computer and Ethernet on the TV, WiFi on both, Ethernet on one and WiFi on another, etc. It doesn't matter. All that matters is that they share the same Ethernet segment (IP block).

**Comment by Evolx1** [comment]
> Yes. You can do wired Ethernet on the computer and Ethernet on the TV, WiFi on both, Ethernet on one and WiFi on the other, etc. It doesn't matter. All that matters is that they share the same layer 2 segment (IP subnet).

Awesome. Thank you so much :)

**Comment by JPersson77** [comment]
> > Yes. You can do wired Ethernet on the computer and Ethernet on the TV, WiFi on both, Ethernet on one and WiFi on the other, etc. It doesn't matter. All that matters is that they share the same layer 2 segment (IP subnet).
> 
> Awesome. Thank you so much :)
> 
> ip subnet is ipv4 and ipv6 protocols? Those address are the same across all my connections. Is that what you're referring to?

There is much to be read and learned about this but generally speaking if your TV has an IP of 192.168.1.x (as an example) and your PC has an IP of 192.168.1.y (as another example) then they are on the same subnet (i.e. they share the same IP block as mentioned above)

Closing this issue since I'm not sure there is an issue here. Feel free to start another issue as needed
