### ISSUE TITLE
Does not work with "sleep" command

### ISSUE THREAD

**Issue by argon932** [JPersson77/LGTVCompanion#64]
I use "Sleep" instead of "Shut Down" because my computer is in a remote location and I need to be able to wake it via USB. The TV does not turn off with this. It would be nice to have this supported.

For now, I made an event scheduler and command line arguments to do this using:
https://www.mediafire.com/file/2azlcjl9bcqufmg/Monitor_Off_When_Sleep.7z/file

Import Monitor Off When Sleep.xml in Windows Task Scheduler.
Put LGTV Companion.lnk in C:\Program Files\LGTV Companion\

**Comment by JPersson77** [comment]
Hi @argon932 ,

this is already a functionality of the app. Can you copy a log at pastebin or similar and paste the link here and I can have a look. Please indicate timecodes when the PC is put to sleep so I can look for relevant events in the log.

**Comment by argon932** [comment]
I will double check maybe it's a fluke. Is there a way to not have the program popup whenever I return from sleep? I always have to minimize it.

**Comment by JPersson77** [comment]
Allright, if you need me to look at the log let me know here. Also there should be nothing popping up when you resume from sleep. Is that the UI/options dialog? Do you keep it open for any particular reason? Once it is configured you can just close it as its only function is to configure the service.

**Comment by argon932** [comment]
I have no idea what was going on. I reinstalled the program and it now correctly shuts it off when I go into sleep. It also no longer pops back up whenever I come out of sleep, despite me closing the window every time. So both my issues have seemingly been fixed. I will report back if they return. Thanks.

**Comment by JPersson77** [comment]
Good to hear! Let's hope it keeps on working!
