### ISSUE TITLE
TV not waking up.

### ISSUE THREAD

**Issue by stlmike** [JPersson77/LGTVCompanion#65]
TV is not waking up after using test.  

I  had to manual enter my tv info and scan did not find my tv.  I did XXX out my ip and mac address.. See below for my pastebin

https://pastebin.com/jBdLRx6L

**Comment by JPersson77** [comment]
Hi @stlmike, it looks like the application can communicate with the display, but not wake it.

I assume you have followed the setup guide in the readme, but can you please confirm you have done this:

- Ensure that the TV can be woken via the network. For the CX line of displays this is accomplished by navigating to Settings (cog button on remote)->All Settings->Connection->Mobile Connection Management->TV On with Mobile, and then enable 'Turn On via Wi-Fi'. For C1 and C2 it's All Settings->General->Devices->External Devices->TV On With Mobile->Turn on via Wi-Fi


Then have a look at these troubleshooting steps:

- When connecting the TV via Wi-Fi it seems some users must enable "Quickstart+" and disable "HDD Eco mode" to avoid the NIC becoming inactive. (physical network cable does not seem to need this)
- Try reconfiguring the device and use one of the other wake-on-lan network options, primarily use option two, connect using an IP adress.
- Ensure the network is not dropping WOL-broadcasts.
- The MAC-address configuration for the device in the application is erroneous.

Let me know if none of the above helps

**Comment by stlmike** [comment]
Hello

When I press Test the monitor powers off and does come back on.  It goes black out after xxx amount of minutes (without loosing power) So i guess that part is working.

I do have my tv directly connected to ethernet. 

I had to manual config my device as scanning will not return any results.

I half to enter mac address as when I tried to save I get The configuration is incorrect or missing information.

**Comment by JPersson77** [comment]
Hi @stlmike ,

From reading what you write I am not sure what is not working for you. 

1) I read that using the test function is working for you. But you also wrote initially that the TV does not power on after using test. Can you confirm that the test function works properly but that the TV can not power on in other situations, f e when the PC is booting up, resuming from sleep etc.
2) Can you confirm that you have done what I wrote in the post above? Particularly about enabling 'Turn on via Wi-Fi' and trying other network options. 
3) The MAC-address needs to be correct for LGTV-companion to be able to power on the display. It can be found in the network options of the TV. Can you confirm that you have double checked this? I'm afraid I don't understand from your last reply what you did specifically in this regard.

**Comment by JPersson77** [comment]
Hi @stlmike any feedback on the this issue?

**Comment by stlmike** [comment]
Sorry forgot to reply, it randomly started working..

**Comment by JPersson77** [comment]
OK, great! Thanks for feedback!
