### ISSUE TITLE
Feature request: Respond to windows display configuration changes and power TV appropriately.

### ISSUE THREAD

**Issue by isidor3** [JPersson77/LGTVCompanion#66]
Maybe a weird use case, but I have a secondary display I sometimes connect to my PC. I currently have windows configured to only output on that display when it's connected, and it will remember this and properly disable output to the TV when I connect the secondary display. 

When this happens today, the TV loses the input signal and shows the LG "no input detected" screensaver. It would be convenient if the app could detect this configuration change and turn off the TV when this occurs, and potentially wake it back up when second screen is disconnected and the configuration reverts.

**Comment by JPersson77** [comment]
I have a similar use case where I sometimes connect an external display (projector) and it would absolutely make sense that LGTV companion responds to this change in display topology. You can maybe consider using the command line shortcuts to work around this for now. Command line reference [here](https://github.com/JPersson77/LGTVCompanion#commandline-arguments)

**Comment by JPersson77** [comment]
Hi isidor3, I have a beta version for you to trial. Let me know if you want to try it please

**Comment by JPersson77** [comment]
Closing due to feature implemented
