### ISSUE TITLE
Feature request: control energy saving settings

### ISSUE THREAD

**Issue by anzial** [JPersson77/LGTVCompanion#67]
Hi there, awesome app, use it everyday :) I love the -screenoff/-screenon commands, mapped them to keys on my keyboard (well, a macro). I was wondering if the same could be done for power saving features, it's annoying that the tv doesn't remember them for individual video profiles and it's set globally for everything. I would be really grateful if I could use a command line to control that as well to be able to switch on the fly as needed. In any case, keep up the great work and hope to see some other features you will come up in future! Thanks for making it easy for us LG TV users 👍

**Comment by anzial** [comment]
oops, yes, I used screenon and off a lot, not the poweron/off lol, sorry for the confusion. It's not an issue, btw, I only mentioned as analogy for what may be a useful feature to control energy saving feature of the tv from the commandline as well.

**Comment by JPersson77** [comment]
Ah, gotcha! I will keep it in the list of feature requests - it is potentially in the scope of this application (power savings)

**Comment by JPersson77** [comment]
Have a look at v3.0.0 which implements a lot more control over the managed devices via command line

**Comment by JPersson77** [comment]
implemented - closing
