### ISSUE TITLE
Strange behavior on LG C1

### ISSUE THREAD

**Issue by ThinkSalat** [JPersson77/LGTVCompanion#68]
Hello there,

I've just return from a long vacation, bringing my laptop with me. My tv is now randomly  turning, even if it's not hooked up by hdmi to my computer on which I have installed LGTV Companion, but it smells related to me.

Another thing is this: and sorry to put two separate issues into one, but when I'm watching youtube videos, after a certain point,  the screen goes blank. Is there any known solution?
Here's my config
![image](https://user-images.githubusercontent.com/31082405/195989014-569b81ae-edfa-4103-a8af-0a25612a802c.png)
![image](https://user-images.githubusercontent.com/31082405/195989025-781f0d3b-bb10-4648-9be9-283a2f982591.png)

**Comment by JPersson77** [comment]
Hi @ThinkSalat ,

1. You should probably uncheck the checkbox "manage this device". If you configure a PC to control your display it will continue to do so regardless of whether it is connected via HDMI or not. The app communicates with the display via your LAN.
2. It should be the option to "Automatically blank, i e turn off transmitters...".  It will blank the screen if there is no user iput via keyboard, mouse or controller. You can experiment with a normal blank windows screensaver instead if you want videos and games to be able to show indefinitely

**Comment by ThinkSalat** [comment]
Thanks! I'm going to give these a try! Didn't realize it was still communicating with the LAN. This still allows normal functionality though right?

**Comment by JPersson77** [comment]
Unchecking "manage this device" means the app will not tell the display to turn on/off  anymore in response to the system turning on/off so you probably need to check it again if/when you connect the display.

**Comment by ThinkSalat** [comment]
Got it, thank you.

**Comment by JPersson77** [comment]
welcome mate :)

**Comment by ThinkSalat** [comment]
Now it seems to be not sleeping at all. My screen saver has always been set to just turn off after 1 minute but it's not turning on at all anymore... not sure if it has anything to do with lgtv companion. i'll see if shuting the service off will cause the screen saver to work again

**Comment by ThinkSalat** [comment]
Ok, youj're not gonna believe it, but I disabled the lgtv companion service, and my screen saver still isn't activating. so my oled is just sitting there on.

**Comment by ThinkSalat** [comment]
I think just for safety i'll set it to blank after 20 minutes. shuold prevent burn in, but give me enough time for most youtube videos

**Comment by JPersson77** [comment]
Maybe try running an admin command prompt and "powercfg /requests" to find out what prevents the screensaver from kicking in. This windows behavior is the reason the blanking feature was implemented in the app.

**Comment by ThinkSalat** [comment]
![image](https://user-images.githubusercontent.com/31082405/196053330-1babb58f-5efa-4e29-87c6-f04d2cf5c1af.png)
/

Weird... so Spotify has something to do with this? God I'm so confused, it was working perfectly before :(

**Comment by JPersson77** [comment]
No worries at all, not sure I can help you troubleshoot spotify further though I'm afraid

**Comment by ThinkSalat** [comment]
I turned it back on to managed and it's working much better now. I think with the 20 minute timer for blanking the screen, we should be good, can always turn it off if watching a movie or something.

**Comment by ThinkSalat** [comment]
Unfortunately now again it's not working again, though I've not changed any settings.

**Comment by JPersson77** [comment]
Hi @ThinkSalat please define not working.

**Comment by ThinkSalat** [comment]
Sorry, the screen doesn’t turn off anymore. Just dims. On Oct 17, 2022, at 2:09 PM, JPersson77 ***@***.***> wrote:﻿
Hi @ThinkSalat please define not working.

**Comment by ThinkSalat** [comment]
Hello,

I turned the setting to turn the screen off after 20 minutes, but the screen isn't turning off now. It seems completely random when the screensaver or lgtv companion turns the screen off.

**Comment by JPersson77** [comment]
hi @ThinkSalat did you get this sorted?

**Comment by JPersson77** [comment]
Closing due to missing feedback. I also think the multi monitor features and user idle mode additions should help with the issues mentioned by OP. Feel free to reopen as necessary
