### ISSUE TITLE
LG C1 48" turns off succesfully, but not on.

### ISSUE THREAD

**Issue by Cr4z33** [JPersson77/LGTVCompanion#69]
I've disabled LAN power saving both in Windows 11 (Pro Insider Build) and in my ASUS ROG Strix X570-F Gaming BIOS and enabled wake on LAN.

I've also followed your instructions step-by-step.

No matter what else I tried the TV keeps turning off succesfully but on.

Here's the log:
`Tue 11:24:08 > LGTV Companion Service started (v 1.7.0) ---------------------------
Tue 11:24:08 > Configuration file successfully read
Tue 11:24:08 > Data path: C:\ProgramData\LGTV Companion\
Tue 11:24:08 > Device1, [LG] webOS TV OLED48C15LA, with IP 192.168.1.232 initiated (Enabled:yes, WOL:2, PairingKey:72ba7c8fca17021d169564b6753edd18, MAC: B4:B2:91:5D:9D:4D , VerifyHdmiInput:off, SetHdmiInput:off, BlankOnIdle:off)
Tue 11:24:08 > Device2, [LG] webOS TV OLED65GX6LA, with IP 192.168.1.7 initiated (Enabled:yes, WOL:2, PairingKey:n/a, MAC: 5C:85:7E:39:D5:14 , VerifyHdmiInput:off, SetHdmiInput:off, BlankOnIdle:off)
Tue 11:24:08 > Setting shutdown parameter level 0x3FF
Tue 11:24:08 > ** System requests displays ON.
Tue 11:24:08 > Device1, spawning DisplayPowerOnThread().
Tue 11:24:08 > Device1, repeating WOL broadcast started toTue 11:24:08 > Device2, repeating WOL broadcast started to MAC: 5C:85:7E:39:D5:14 using IP address: 192.168.1.7
Tue 11:24:08 >  failed with code 1231
Tue 11:24:08 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 11:24:08 > Device2, WARNING! DisplayPowerOnThread(): connect: Tentativo di operazione del socket verso una rete non raggiungibile
Tue 11:24:08 > Device1, WARNING! DisplayPowerOnThread(): connect: Tentativo di operazione del socket verso una rete non raggiungibile
Tue 11:24:10 >  failed with code 1231
Tue 11:24:10 >  failed with code 1231
Tue 11:24:10 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 11:24:12 >  failed with code 1231
Tue 11:24:12 > Device2, WARNING! WOLthread WS sendto(): 10051
Tue 11:24:12 >  failed with code 1231
Tue 11:24:12 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 11:24:14 > Device1, WARNING! DisplayPowerOnThread(): connect: Tentativo di operazione del socket verso una rete non raggiungibile
Tue 11:24:14 >  failed with code 1231
Tue 11:24:14 > Device2, WARNING! WOLthread WS sendto(): 10051
Tue 11:24:14 >  failed with code 1231
Tue 11:24:14 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 11:24:16 >  failed with code 1231
Tue 11:24:16 > Device2, WARNING! WOLthread WS sendto(): 10051
Tue 11:24:16 >  failed with code 1231
Tue 11:24:16 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 11:24:18 >  failed with code 1231
Tue 11:24:18 > Device2, WARNING! WOLthread WS sendto(): 10051
Tue 11:24:18 >  failed with code 1231
Tue 11:24:18 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 11:24:20 > Device2, repeating WOL broadcast ended
Tue 11:24:20 > Device1, repeating WOL broadcast ended
Tue 11:24:35 > IPC, Daemon has started.`

**Comment by JPersson77** [comment]
btw, does the 65" turn on properly?

**Comment by Cr4z33** [comment]
It actually turns out the LAN connections goes online only like 20 seconds after logging into Windows... need to find out why.

Thank you anyway and sorry for having wasted your time hehe.

**Comment by JPersson77** [comment]
No worries, that sounds like an excessively long time. Maybe try updating/reverting your NIC-drivers

**Comment by dechamps** [comment]
Another explanation could be that your Ethernet switch takes an abnormally long time to establish the link (some Cisco switches are notoriously slow at this for example, but it can be fixed by changing their configuration), or that your LAN DHCP server is especially slow.

**Comment by Cr4z33** [comment]
> Another explanation could be that your Ethernet switch takes an abnormally long time to establish the link (some Cisco switches are notoriously slow at this for example, but it can be fixed by changing their configuration), or that your LAN DHCP server is especially slow.

Switch is fine. 😉
