### ISSUE TITLE
LG C2 does not respond anymore after reset

### ISSUE THREAD

**Issue by ef804s** [JPersson77/LGTVCompanion#73]
Here is the config file:
    "Device1": {
        "Enabled": true,
        "HDMIinputcontrol": true,
        "IP": "192.168.1.11",
        "MAC": [
            "74:E6:B8:C9:E9:CC"
        ],
        "Name": "lgc2",
        "OnlyTurnOffIfCurrentHDMIInputNumberIs": 1,
        "SessionKey": "4a8fe4af610e1c149a2a60bc5d2c49f1",
        "SetHDMIInputOnResume": true,
        "SetHDMIInputOnResumeToNumber": 1,
        "Subnet": "255.255.255.0",
        "WOL": 3
    },
    "LGTV Companion": {
        "AutoUpdate": false,
        "BlankWhenIdle": true,
        "BlankWhenIdleDelay": 10,
        "ExtendedLog": true,
        "LocalEventLogRestartString": [
            "restart"
        ],
        "LocalEventLogShutdownString": [
            "shutdown",
            "power off"
        ],
        "PowerOffDuringRDP": false,
        "PowerOnTimeOut": 40,
        "Version": 2
    }

The ip address and the mac are correct (verified). Here is the log:

Wed 03:34:13 > LGTV Companion Service started (v 1.7.0) ---------------------------
Wed 03:34:13 > Configuration file successfully read
Wed 03:34:13 > Data path: C:\ProgramData\LGTV Companion\
Wed 03:34:13 > Device1, lgc2, with IP 192.168.1.11 initiated (Enabled:yes, WOL:3, SubnetMask:255.255.255.0, PairingKey:4a8fe4af610e1c149a2a60bc5d2c49f1, MAC: 74:E6:B8:C9:E9:CC , VerifyHdmiInput:1, SetHdmiInput:1, BlankOnIdle:on(10m))
Wed 03:34:13 > Host IP detected: 192.168.1.9
Wed 03:34:13 > Setting shutdown parameter level 0x3FF
Wed 03:34:13 > ** System requests displays ON.
Wed 03:34:13 > Device1, spawning DisplaySetHdmiInputThread().
Wed 03:34:13 > Device1, spawning DisplayPowerOnThread().
Wed 03:34:13 > Device1, repeating WOL broadcast started to MAC: 74:E6:B8:C9:E9:CC using broadcast address: 192.168.1.255
Wed 03:34:13 > IPC, Daemon has started.
Wed 03:34:14 > Device1, established contact. Set HDMI input: 1
Wed 03:34:14 > Device1, established contact: Display is ON.  
Wed 03:34:15 > Device1, repeating WOL broadcast ended
Wed 03:34:16 > IPC, force power OFF: device1
Wed 03:34:16 > Device1, spawning DisplayPowerOffThread().
Wed 03:34:16 > Device1, established contact: Device is OFF.
Wed 03:34:20 > IPC, force power ON: device1
Wed 03:34:20 > Device1, spawning DisplayPowerOnThread().
Wed 03:34:20 > Device1, repeating WOL broadcast started to MAC: 74:E6:B8:C9:E9:CC using broadcast address: 192.168.1.255
Wed 03:34:20 > Device1, established contact: Display is ON.  
Wed 03:34:22 > Device1, repeating WOL broadcast ended
Wed 03:34:27 > IPC, force power OFF: device1
Wed 03:34:27 > Device1, spawning DisplayPowerOffThread().
Wed 03:34:27 > Device1, established contact: Device is OFF.
Wed 03:34:31 > IPC, force power ON: device1
Wed 03:34:31 > Device1, spawning DisplayPowerOnThread().
Wed 03:34:31 > Device1, repeating WOL broadcast started to MAC: 74:E6:B8:C9:E9:CC using broadcast address: 192.168.1.255
Wed 03:34:31 > Device1, established contact: Display is ON.  

The C2 is set to the correct wired ethernet parameters (static IP via DHCP). The parameter "Turn on via Wi-Fi" is on.
Please help.

Fred

**Comment by JPersson77** [comment]
Hi Fred, can you define "does not respond" please. From reading the log it seems everything is working allright and the TV seems to be responding immediately

**Comment by ef804s** [comment]
Hi,

reset means resetting the C2: "General" "System" "Reset to Initial Settings"
The C2 does not turn on or off, if the C2 menu system is active, I can see a flicker when I issue an ON or OFF command from the your GUI.

I think it is a problem in WebOS, is there a "hard" reset?
Thanks for looking into the issue.

Fred

**Comment by ef804s** [comment]
I closed the issue by accident

**Comment by JPersson77** [comment]
Try to delete the device in the app and re-add it. The SessionKey is probably wrong since the TV was reset.

I assume this should work, and I think I should add some check or mechanism for detecting this condition

**Comment by ef804s** [comment]
Hi,

thank you so much! This solved my issue.

Best regards,

Fred
