### ISSUE TITLE
windows monitor topology feature in v1.8.0 - documentation

### ISSUE THREAD

**Issue by drspamilton** [JPersson77/LGTVCompanion#75]
Thank you for your hard work. I don't quite understand how 1.8 differs from 1.7 as far as powering on and off. Can someone explain? Thank you.

**Comment by JPersson77** [comment]
Thanks too! Absolutely!  The difference is that 1.7 powered on and powered off all your devices following the power state of your PC, while 1.8 also takes into account what devices you have actually enabled in the windows monitor configuration.
![monitors](https://user-images.githubusercontent.com/77928210/199921182-3640fcc3-583c-4753-a428-c54de040c2db.jpg)

So the application should now manage multiple devices much better. Remember to go through the configuration guide though to set it up properly.
