### ISSUE TITLE
Automatic screen blanking doesn't trigger, but does work from command line

### ISSUE THREAD

**Issue by adam-koebel** [JPersson77/LGTVCompanion#76]
My display is an LG C2. I have Quick Start+ and Always Ready enabled. LGTV Companion gets a pairing key (see it in the log). And I know it's connecting because the test works and I can also trigger the "screen off" function via command line. But the automatic screen off when idle is not working. I set it to 1 minute, don't touch mouse or keyboard but it never initiates the screen off event (don't even see it attempted in the log). Is there some setting in Windows perhaps that would prevent your app from recognizing the lack of input?

I have another issue that may or may not be related. I used an older version of your app on my old TV (a B8), before you added this new feature. That TV is no longer connected anywhere and yet when I scan for new TVs it finds that old TV with its old IP/MAC address (said IP is not even used on my router anymore). Only way I could get the C2 to work was to manually add it because the scan would only pick up the old one. So I am wondering if there is some "ghost" of that old TV somewhere interfering with this. Though I see no references to it in the config file, or my registry so I have no idea where it's possibly pulling that old IP and MAC address from. 

I have uninstalled and reinstalled, and tried both 1.7 and 1.8. Also obviously restarted the PC a few times as well as restarted the router.

Thank you

**Comment by JPersson77** [comment]
Hi @adam-koebel, can you as a first step try executing "LGTVdaemon.ex -show" and observe the output of the window that opens. It should show you the time of last input (mouse, keyboard, controller) as well as the communication with the service. It might give you additional clues. Please report back your findings.

The scan feature does not work as one might expect, by reading for example EDID-values over HDMI. The reason is that the first versions knew nothing about what devices was connected over HDMI. But I'm thinking of changing the scan feature to do that instead. Now it polls the registered digital media devices, which you can see in the device manager (you might have to show hidden devices for your old B8 to show up). As you've discovered the C2 does not behave like the older siblings and thus it does not show up in a scan and you have to add it manually.

**Comment by JPersson77** [comment]
Actually what I just wrote about changed behaviour in C2 is not all accurate. I just now tried and I can actually see that my 42C2 can be found in the digital media devices in the device manager and subsequently a scan in the app does pick it up. Not entirely sure about windows inner workings and the timing of windows adding the device to the device manager. Will see if I can figure out some more details and add to the documentation

**Comment by adam-koebel** [comment]
OK I just tried the -show command and the "seconds ago" stays at 0 with new input tick numbers happening every second. 

So then I started to unplug USB devices with that window up and I found the culprit: my USB DAC. I have no idea why that is preventing the idle detection. The DAC is a "XMOS XHRA-2HPA" in device manager (Monoprice Monolith Headphone DAC/Amp). Unfortunately it has no kind of power saving settings so I'm not sure why it would be preventing the idle.

**Comment by JPersson77** [comment]
Not sure why the USB DAC would be the culprit. I tried googling the Monolith,  but cannot see anything in the feature list that would be troublesome. It's just an USB-DAC and usually that does not interfere. I cannot find any mentions of a driver download either so I assume there is nothing to update in that regard. Maybe try switching from a usb 3 to usb 2 contact or vice versa if that is an option? 

Can you confirm that your PC behaves normally wrt going into sleep/hibernation and windows screensaver?

**Comment by adam-koebel** [comment]
Thanks for your assistance. After a lot of googling I was able to find a solution buried away on reddit: https://www.reddit.com/r/techsupport/comments/dmylee/fixed_a_problem_with_dac_interrupting_sleep_mode/

For some reason some USB audio devices create a generic named input device, which it doesn't seem to be needed for any functionality. Disabling that in device manager solves the issue.

**Comment by JPersson77** [comment]
Excellent! I suspected something acting foul along these lines.. Some DACs actually have a need for registering a HID input device of course but I guess there are many ways it can also be implemented in the wrong way. Happy it was solved!
