### ISSUE TITLE
Blanking vs Power Off & Display Detection

### ISSUE THREAD

**Issue by Ghan04** [JPersson77/LGTVCompanion#77]
I recently got an LG C2 for my computer to go with my two other monitors. I've been experimenting with this application and have a question - I hope I'm understanding this correctly.

With Windows power settings, you can configure it to turn off the displays after a timeout. With Companion, this will result in the TV turning off completely, which looks to Windows like a display unplug and causes it to reconfigure the screen layout.

With display blanking via the app, it will simply stop the display input to the TV, but Windows still sees it as a connected device. The issue here is that nothing happens with any other connected monitors - they still display as normal.

Is there any way to combine the behavior of these two, where the TV just blanks its input, but does not turn off entirely, when the Windows power timeout triggers to turn off displays? I would prefer if the TV only turns off when the computer does, because display disconnect/reconnect events throughout the day cause strange behaviors with application window sizing and position.

**Comment by JPersson77** [comment]
Hi @Ghan04, when using windows power settings the C2 will indeed power off, and this sometimes has the behavior you describe. You should be able to enable "always ready" (but I would untick the  wallpaper feature) in the settings for the TV and. In my experience with a 42C2, this alleviates the issue. Try it and please let me know how it goes.

**Comment by dechamps** [comment]
See also the discussion in #71 about display disconnection events.

**Comment by Ghan04** [comment]
Perfect, that features seems to resolve the issue so Windows doesn't reconfigure the display layout when the TV turns off. Thank you!
