### ISSUE TITLE
TV doesn't turn on anymore

### ISSUE THREAD

**Issue by Cr4z33** [JPersson77/LGTVCompanion#79]
Since latest app update I've noticed that the companion app is able to turn the TV off, but not on anymore.
I noticed this in the logs, but have no clue what it means.
All I can  say is that the IP address `192.168.4.232` is still correct.
`Tue 14:55:25 > LGTV Companion Service started (v 1.8.0) ---------------------------
Tue 14:55:25 > Configuration file successfully read
Tue 14:55:25 > Data path: C:\ProgramData\LGTV Companion\
Tue 14:55:25 > Device1, [LG] webOS TV OLED48C15LA, with IP 192.168.4.232 initiated (Enabled:yes, WOL:2, PairingKey:72ba7c8fca17021d169564b6753edd18, MAC: B4:B2:91:5D:9D:4D , VerifyHdmiInput:off, SetHdmiInput:off, BlankOnIdle:off)
Tue 14:55:25 > Device2, [LG] webOS TV OLED65GX6LA, with IP 192.168.4.200 initiated (Enabled:no, WOL:2, PairingKey:n/a, MAC: 5C:85:7E:39:D5:14 , VerifyHdmiInput:off, SetHdmiInput:off, BlankOnIdle:off)
Tue 14:55:25 > Setting shutdown parameter level 0x3FF
Tue 14:55:25 > ** System requests displays ON.
Tue 14:55:25 > Device1, spawning DisplayPowerOnThread().
Tue 14:55:25 > Device1, repeating WOL broadcast started to MAC: B4:B2:91:5D:9D:4D using IP address: 192.168.4.232
Tue 14:55:25 > GetBestRoute2() failed with code 1231
Tue 14:55:25 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 14:55:25 > Device1, WARNING! DisplayPowerOnThread(): connect: Tentativo di operazione del socket verso una rete non raggiungibile
Tue 14:55:27 > GetBestRoute2() failed with code 1231
Tue 14:55:27 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 14:55:29 > GetBestRoute2() failed with code 1231
Tue 14:55:29 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 14:55:31 > GetBestRoute2() failed with code 1231
Tue 14:55:31 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 14:55:31 > Device1, WARNING! DisplayPowerOnThread(): connect: Tentativo di operazione del socket verso una rete non raggiungibile
Tue 14:55:33 > GetBestRoute2() failed with code 1231
Tue 14:55:33 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 14:55:35 > GetBestRoute2() failed with code 1231
Tue 14:55:35 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 14:55:37 > GetBestRoute2() failed with code 1231
Tue 14:55:37 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 14:55:37 > Device1, WARNING! DisplayPowerOnThread(): connect: Tentativo di operazione del socket verso una rete non raggiungibile
Tue 14:55:39 > GetBestRoute2() failed with code 1231
Tue 14:55:39 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 14:55:41 > GetBestRoute2() failed with code 1231
Tue 14:55:41 > Device1, WARNING! WOLthread WS sendto(): 10051
Tue 14:55:43 > Device1, WARNING! DisplayPowerOnThread(): connect: Tentativo di operazione del socket verso un host non raggiungibile
Tue 14:55:43 > GetBestRoute2() failed with code 1232
Tue 14:55:43 > Device1, WARNING! WOLthread WS sendto(): 10065
Tue 14:55:45 > GetBestRoute2() selected interface index 73 LUID 1689399666409472 route protocol 2
Tue 14:55:47 > Device1, repeating WOL broadcast ended
Tue 14:55:51 > IPC, Daemon has started.
`

**Comment by JPersson77** [comment]
Hi @Cr4z33 from reading the log it looks like the network is unreachable for some time after the app is started. Is it only on PC boot or resume from sleep that this issue occurs? What happens if you in the main GUI select "Test" in the drop-down menu for the 48"?

**Comment by Cr4z33** [comment]
Hi (for some unknown motherboard bug) the network is unavailable indeed, but this is happening since day one and I already setup the companion to WOL the TV after 21 seconds.

Test does turn the TV off and that is what is already happening. 🙂

**Comment by JPersson77** [comment]
If you are referring to the option "power on timeout" it does the opposite as it will terminate attempts at 21 seconds (default 40). (I will add more explanatory texts for net version as I noticed it causes some confusion).

Can you try setting this option to 40? If I interpreted your correct?

**Comment by Cr4z33** [comment]
Ohhhh I thought it would **_START_** attempting to WOL after (my case) 21 seconds lol!

OK I set it to 40 and will run a shutdown/power on test.
