### ISSUE TITLE
No longer working after last LG update

### ISSUE THREAD

**Issue by Chad711** [JPersson77/LGTVCompanion#82]
Yesterday I had a new update for the TV. Since this this does not seem to work (will not turn on TV on power up). Anyone else having this issue?

**Comment by JPersson77** [comment]
No such issue (42C2). Verify that your tv IP did not change and that its still connected to LAN. If that does not help enable the log and paste it here so I can have a look

**Comment by Chad711** [comment]
Not sure what the issue was, you can disregard. It's working good today. Thank you
