### ISSUE TITLE
Multiple HDMI CEC devices

### ISSUE THREAD

**Issue by konax3** [JPersson77/LGTVCompanion#88]
I have a random issue with my LG42C2 and the HDMI Source select. I have the computer and a fire stick connected to my TV. 
When I power on the PC, the TV is powered on too and always goes to the correct HDMI source (HDMI 4 in my case) like i've configured and LG Companion App but sometimes after a few seconds the tv is powered on, the fire stick changes the source HDMI to his own (HDMI 3).

Is there any way to delay the selection of the HDMI source or something similar to avoid the fire stick to changes the HDMI source without disable the CEC, obviously??

Thanks in advance.

**Comment by JPersson77** [comment]
Hi @konax3 I see what you mean. I'll think about if there is some neat way to achieve this

**Comment by fehbari** [comment]
FWIW, I experience the same issue with my living room C9 without the app. If I turn on my PS5 or Switch, the TV automatically switches to them, but after a few seconds, it turns on my Apple TV and switches to it. Something seems inherently wrong about how LG TVs handle certain HDMI-CEC devices, doesn't seem to be specifically an issue with LGTVCompanion. For instance my bedroom C2 is only used with a PC (LGTVCompanion) and a console, and it's not an issue there.

**Comment by JPersson77** [comment]
Hi @fehbari thanks for your input! Yeah you are right, this is more of an issue with race conditions over HDMI-CEC on LG TV's. But on the LGTV companion side pf things what can be done is to work around the issue, maybe. I can imagine delaying the input switch command, sending it twice with a delay, monitor input switches and reset input etc.

**Comment by hapklaar** [comment]
This is not a problem with LGTV's handling of CEC. It's just that the device (CEC enabled HDMI device) is telling the TV to switch inputs to the port they are connected to. A simple fix could be to disable HDMI-CEC on the firetv stick if possible?

**Comment by JPersson77** [comment]
The scripting support available in v3.0 can be used to send a delayed HDMI switch command to the TV

**Comment by JPersson77** [comment]
Closing this issue as the CEC issue isn't in scope of the app to work around. Feel free to reopen as necessary
