### ISSUE TITLE
LG Companion powering off display when I load full screen game after switching GPUs

### ISSUE THREAD

**Issue by jsaltzman** [JPersson77/LGTVCompanion#90]
Today I upgraded from a 3060 ti to a 3080. Now when I launch full screen games, I am noticing my LG C2 turn off (being used as a monitor). I tried removing the C2 and re adding it to the LG companion but the issue still occurs.

**Comment by JPersson77** [comment]
hi @jsaltzman congrats on the new hardware! What version LGTV Companion are you running? Please paste the full log here and I'll have a look at what's going on

**Comment by JPersson77** [comment]
hi @jsaltzman any update on this issue?

**Comment by jsaltzman** [comment]
Thanks for the response. I have not responded because it seems like this sort of ironed itself out.

**Comment by JPersson77** [comment]
Good to know thanks!
