### ISSUE TITLE
App no longer works with C2 software update version 03.21.45

### ISSUE THREAD

**Issue by kristoferen** [JPersson77/LGTVCompanion#91]

**Comment by JPersson77** [comment]
Hi @kristoferen I have the same firmware on my 42C2 and it is working as usual.

Can you describe what is not working more specifically? What version LGTV Companion are you running? Please paste a full log here and I will help you

**Comment by JPersson77** [comment]
hi @kristoferen any update on this?

**Comment by kristoferen** [comment]
I apologize. It seems that reinstalling and reconfiguring it solved the issue, so not firmware related at all.

**Comment by JPersson77** [comment]
No worries, thanks for your feedback!
