### ISSUE TITLE
Feature Request: Change Picture Mode via CLI

### ISSUE THREAD

**Issue by TheEarthrise** [JPersson77/LGTVCompanion#92]
Hello,

would it be possible to change the picture mode via CLI? I use the 'Dark Space' Mode for usual work with only 30% OLED brightness and the 'Game Mode' with 100% OLED brightness for gaming. It is a bit painfully to use the remote every time, with a CLI command I could do the change with just one button press.

**Comment by dechamps** [comment]
You should take a look at [bscpylgtv](https://github.com/chros73/bscpylgtv) which provides a command line interface for many LGTV functions.

**Comment by JPersson77** [comment]
Hi @TheEarthrise there are other software like pointed out which can accomplish this. Closing the issue since it's generally not in the scope of this application
