### ISSUE TITLE
When using a laptop with usb c to hdmi...

### ISSUE THREAD

**Issue by eotaekyong** [JPersson77/LGTVCompanion#94]
My laptop and TV are connected via usb c to hdmi.
I am very satisfied with the power off and on function and it works well.

"process power and screen off events only when the display input source is set to hdmi"

The above function is not working. It is a necessary function when using only a laptop separately. Please solve it.

**Comment by dechamps** [comment]
Why do you mean by "is not working"?

Please explain what HDMI input number you've set the option to, which sources you are using on which HDMI inputs, what you expected to happen, and what actually happens.

Note that if your laptop is your only source, then there is no point in enabling this option. It is only useful when using multiple sources connected to a single TV, to prevent LGTVCompanion from turning off the TV when another source is currently in use.

**Comment by eotaekyong** [comment]
I am using my laptop as the sole source.

When connecting a laptop to a TV, the function to turn on the TV is useful, but
The goal is that the TV won't turn on when you remove the usb c in the laptop.

thank you.

**Comment by dechamps** [comment]
That is not what the "process power and screen off events only when the display input source is set to hdmi" option is for. That option is for disabling power off events depending on which HDMI input number the TV is currently on. In your case your TV is always on the same HDMI input (the one you would connect your laptop to), therefore this option is not useful in your scenario.

It looks like what you're looking for is a way to disable LGTVCompanion if the PC it's running on is not presently connected to the TV.

As far as I know LGTVCompanion doesn't have that feature but I haven't followed the latest additions - @JPersson77 isn't this something that could be addressed by your fancy new "monitor topology" stuff (#75)?

**Comment by eotaekyong** [comment]
Your answer gave me a good idea of what that function is.
I found this useful when I have multiple input sources.

I'm eagerly hoping for a feature to be added to disable LG TV Companion when the TV and PC are not connected.

thank you.

**Comment by JPersson77** [comment]
Hi @eotaekyong did you try the "multi monitor topology" feature? The point of it is to do what you are looking for. But I have not tested it with usb-c to hdmi so curious to get your feedback

**Comment by eotaekyong** [comment]
The input source is only 1 laptop, the laptop and TV are connected via usb c via hdmi.

Power synchronization is a very good and nice feature, but I don't like the fact that the TV turns on when I use the laptop alone (turn on the laptop by removing the usbc to hdmi cable from the laptop).

"Handle power and screen off events only when display input source is set to hdmi"

But after checking the options above and turning on the laptop by myself (after removing the usbc to hdmi cable from the laptop and turning on the laptop), I noticed that the TV turns on.

**Comment by JPersson77** [comment]
Hi @eotaekyong but did you try the multi monitor topology feature? It adds to the feature of power syncronization so that power state of the display also sync with what is connected through hdmi (which is what you want i believe)

**Comment by JPersson77** [comment]
Hi @eotaekyong any updates on this?

**Comment by JPersson77** [comment]
Closing due to missing user feedback. Please feel to reopen as needed
