### ISSUE TITLE
LG Companion does not start up with windows

### ISSUE THREAD

**Issue by SCDoll12** [JPersson77/LGTVCompanion#98]
Hi,
Although my C2 will turn on automatically when Windows starts up, it won't blank the screen automatically unless I run or add LG Companion to staryup everytime I restart my PC even though LG Companion Daemon is already set to start up with windows. But then I need to minimize LG Companion every time I boot up.

Is there a way to have LG Companion start up without needing the app to display on screen every time I boot up? From my understanding LG Companion Daemon should already be managing the display sleep but doesn't seem to be working.

Thanks

**Comment by JPersson77** [comment]
Hi @SCDoll12 your understanding is correct. The daemon manages the user idle mode. The options UI is only used to configure the options and does not need to be open. So then we need to figure out what is going on in your system. Can you start by pasting the full log and the config.json to pasting or similar and paste the links here please. They are found in c:/programdata/lgtv companion

**Comment by SCDoll12** [comment]
Here is the link to the files. It works no problem in 1.8.7 but in 1.9.0 it stops working. I have try reinstalling and such and no luck.
https://1drv.ms/u/s!AsnGBuvQEtENkv5vdJvbMhQskOcNog?e=SNVrIA

**Comment by JPersson77** [comment]
Hi, nothing out of the ordinary in the log. It looks like the screen blanked properly so I assume you had lgtv companion running according to your issue desctiption

I notice you have the new fullscreen-prohibit-idle option enabled. Can you try disabling that option and see if that makes a difference?

Also if you open a command prompt at c:/program files/lgtv companion/ and execute "LGTVdaemon.exe -show" without quatesthe daemon will open a windows that will show some additional info on what prevents sleep.

**Comment by JPersson77** [comment]
Hi again @SCDoll12 , I think I can replicate what is causing your issue. It seems the fullscreen detection routine does not properly work when there are no windows at all on the desktop. As soon as there is something on the desktop, regardless of active or not, it works as per usual. Not entirely sure yet why this is happening but will try to patch. Can you maybe see if this is the issue you are seeing too?

**Comment by SCDoll12** [comment]
Hi, I will be away from my computer this week but if I get the chance I’ll try this sometime hopefully late this week or sometime next week and will let you know as soon as I get a chance.

Thanks for looking into this!

**Comment by JPersson77** [comment]
So I discovered the culprit. The geforce experience overlay is a fullscreen transparent window and this fools the heuristics in the api used when no other windows are open on the desktop. Can you confirm maybe that you are using geforce experience?

You can use nirsoft's WiinLister https://www.nirsoft.net/utils/winlister.html to see if an invisible overlay is causing your issue. Look for windows with the size of the current resolution, but not explorer.exe. Thankful for input to be able to work around potentially

![image](https://user-images.githubusercontent.com/77928210/212780281-1c3518c4-1815-4502-bc78-58f32ab61f23.png)

**Comment by SCDoll12** [comment]
Hi,

Oh that makes sense! I am definitely using GeForce Experience.

Never would have thought of that…that’s too bad that it thrills the heuristics in the api.

**Comment by JPersson77** [comment]
Allright, I'll see what can be done about it. Thanks for input!

**Comment by JPersson77** [comment]
@dechamps I noticed you have stumbled upon the quirks of the geforce experince overlay before (cool read and amazing tool at l https://github.com/dechamps/RudeWindowFixer ). Since you've looked at this in length already, what side-effects are we talking about by doing SetProp(hwnd, L”NonRudeHWND”, reinterpret_cast<HANDLE>(TRUE)) on the overlay?

**Comment by dechamps** [comment]
There are no harmful side-effects that I know of. I'm not sure it would change the outcome of your code however, depending on which Windows APIs it's using to get the fullscreen state.

**Comment by JPersson77** [comment]
Thanks for your reply! I just have a feeling at this time that SHQueryUserNotificationState() might rely on the rude window manager. Will do some testing then. Disabling the overlay in GFE, and thus removing the transparent window, does alleviate the issues noted above and the symptoms are exactly like what you have already discovered where the overlay gets to the top of the Z-order when there are no other windows open at the desktop and the HQueryUserNotificationState() then return QUNS_BUSY

**Comment by JPersson77** [comment]
A fix will be in the next release based on the above

**Comment by JPersson77** [comment]
New version is up (v2) so I'm closing this issue. https://github.com/JPersson77/LGTVCompanion/releases
