### ISSUE TITLE
TV Will Not Power Down

### ISSUE THREAD

**Issue by RoofDefenseSystems** [JPersson77/LGTVCompanion#99]
I have a very similar issue to the one found here:
https://github.com/JPersson77/LGTVCompanion/issues/85#issuecomment-1335980280_

The major difference is that while the pairing notification on the TV never appears it will power on, but not off. Checking the logs this is what I am seeing:

Sun 16:10:32 > Device1, repeating WOL broadcast started to MAC: A8:A2:37:69:1D:6E using IP address: 192.168.86.78
Sun 16:10:32 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:10:33 > IPC, windows monitor topology was changed. Device1:ON 
Sun 16:10:33 > Device1, omitted DisplayPowerOnThread().
Sun 16:10:34 > IPC, windows monitor topology was changed. Device1:ON 
Sun 16:10:34 > Device1, omitted DisplayPowerOnThread().
Sun 16:10:34 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:10:35 > IPC, windows monitor topology was changed. Device1:ON 
Sun 16:10:35 > Device1, omitted DisplayPowerOnThread().
Sun 16:10:35 > Device1, WARNING! DisplayPowerOnThread(): An existing connection was forcibly closed by the remote host
Sun 16:10:36 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:10:38 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:10:38 > Device1, WARNING! DisplayPowerOnThread(): An existing connection was forcibly closed by the remote host
Sun 16:10:40 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:10:42 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:10:44 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:10:45 > Device1, WARNING! DisplayPowerOnThread(): An existing connection was forcibly closed by the remote host
Sun 16:10:46 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:10:48 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:10:50 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:10:50 > Device1, WARNING! DisplayPowerOnThread(): An existing connection was forcibly closed by the remote host
Sun 16:10:52 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:10:54 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:10:56 > IPC, force power OFF: device1
Sun 16:10:56 > Device1, omitted DisplayPowerOffThread() (no pairing key).
Sun 16:10:56 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:10:56 > Device1, WARNING! DisplayPowerOnThread(): An existing connection was forcibly closed by the remote host
Sun 16:10:58 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:11:00 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:11:02 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:11:02 > Device1, WARNING! DisplayPowerOnThread(): An existing connection was forcibly closed by the remote host
Sun 16:11:04 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:11:06 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:11:08 > Device1, GetBestRoute2() selected interface index 4 LUID 1689399632855040 route protocol 2
Sun 16:11:09 > Device1, WARNING! DisplayPowerOnThread(): An existing connection was forcibly closed by the remote host

**Comment by JPersson77** [comment]
Hi, your log indicates that there has been no handshake between the PC and the TV (Sun 16:10:56 > Device1, omitted DisplayPowerOffThread() (no pairing key)) which is needed before the app is able to control the TV

Since you mention there never was a pairing dialogue the first thing you need to do is to doublecheck that the IP of the TV is correct in the configuration (maybe even delete the device and then add it again). Also paste the full log and the config.json please

**Comment by RoofDefenseSystems** [comment]
IP and MAC address are correct. Tried deleting the device several times. Uninstalled and reinstalled the app. 

[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/10421761/Log.txt)
[config.txt](https://github.com/JPersson77/LGTVCompanion/files/10421764/config.txt)

**Comment by JPersson77** [comment]
Hi, Thanks! I've had a look but unfortunately I need more verbose output in the log to understand the reply from your TV and figure out what is going on. I've added this to the development build just uploaded to Discord. https://discord.gg/7KkTPrP3fq (#development-builds). The build will simply print additional lines prefixed with [DEBUG] to the log with the responses from your display. Please use it and paste the log here again

Let me know if it's not possible for you to download from discord and I'll see if it can be hosted elsewhere.

**Comment by JPersson77** [comment]
Did you by any chance receive a firmware update recently? Your issue looks a little like these that popped up now: #102 #103

**Comment by JPersson77** [comment]
New version is up (v2) so I'm closing this issue. https://github.com/JPersson77/LGTVCompanion/releases
